/**
 * Font classes for the look generator (v1.430): every family the editor
 * can offer (the self-hosted catalog and the Google CDN list) sorted into
 * the five roles a pairing needs. The catalog itself only knows weights,
 * and random pairings without a class are ugly: two scripts on top of
 * each other, a monospace hero, a display face as body. The classes are
 * curated by hand; an unknown family counts as a sans.
 *
 *   display  loud poster and headline faces, heroes only
 *   sans     sans-serifs, heroes (heavy weights) and support lines
 *   serif    serifs and slabs, heroes and support lines
 *   script   handwriting and calligraphy, heroes only, never uppercase
 *   mono     monospace, an occasional support line
 */

export const FONT_CLASSES = {
	// --- self-hosted catalog ---
	Inter: 'sans',
	Roboto: 'sans',
	'Open Sans': 'sans',
	Lato: 'sans',
	Montserrat: 'sans',
	Poppins: 'sans',
	Raleway: 'sans',
	'Raleway Dots': 'display',
	Nunito: 'sans',
	'Nunito Sans': 'sans',
	'Work Sans': 'sans',
	Rubik: 'sans',
	Karla: 'sans',
	Mulish: 'sans',
	Cabin: 'sans',
	'DM Sans': 'sans',
	'Fira Sans': 'sans',
	Barlow: 'sans',
	'Barlow Condensed': 'sans',
	Archivo: 'sans',
	Oswald: 'sans',
	'Big Shoulders Display': 'display',
	'Josefin Sans': 'sans',
	Quicksand: 'sans',
	Comfortaa: 'sans',
	Fredoka: 'sans',
	'Exo 2': 'sans',
	'Space Grotesk': 'sans',
	Manrope: 'sans',
	Sora: 'sans',
	Outfit: 'sans',
	Figtree: 'sans',
	'Plus Jakarta Sans': 'sans',
	'Red Hat Display': 'sans',
	'IBM Plex Sans': 'sans',
	Kanit: 'sans',
	Teko: 'display',
	Anton: 'display',
	'Bebas Neue': 'display',
	Righteous: 'display',
	Abel: 'sans',
	'Playfair Display': 'serif',
	'DM Serif Display': 'serif',
	Merriweather: 'serif',
	Lora: 'serif',
	'PT Serif': 'serif',
	'Roboto Slab': 'serif',
	Bitter: 'serif',
	'Zilla Slab': 'serif',
	'Source Serif 4': 'serif',
	'Crimson Text': 'serif',
	'Libre Baskerville': 'serif',
	'Cormorant Garamond': 'serif',
	'EB Garamond': 'serif',
	Cinzel: 'serif',
	'Abril Fatface': 'display',
	'IBM Plex Serif': 'serif',
	Inconsolata: 'mono',
	'IBM Plex Mono': 'mono',
	'JetBrains Mono': 'mono',
	'Space Mono': 'mono',
	Lobster: 'script',
	Pacifico: 'script',
	'Oleo Script': 'script',
	'Dancing Script': 'script',
	Caveat: 'script',
	'Amatic SC': 'script',
	Bangers: 'display',
	'Great Vibes': 'script',
	'Indie Flower': 'script',
	'Permanent Marker': 'script',
	Sacramento: 'script',
	Satisfy: 'script',
	'Shadows Into Light': 'script',
	Playball: 'script',
	Bungee: 'display',
	'Bungee Shade': 'display',
	'Bungee Inline': 'display',
	'Bungee Outline': 'display',
	'Alfa Slab One': 'display',
	'Titan One': 'display',
	'Luckiest Guy': 'display',
	'Bowlby One SC': 'display',
	'Passion One': 'display',
	'Sigmar One': 'display',
	'Fugaz One': 'display',
	'Lilita One': 'display',
	Ultra: 'display',
	Rye: 'display',
	Shrikhand: 'display',
	Modak: 'display',
	'Rubik Mono One': 'display',
	Monoton: 'display',
	'Black Ops One': 'display',
	'Faster One': 'display',
	Bevan: 'display',
	Staatliches: 'display',
	'Archivo Black': 'display',
	'Bagel Fat One': 'display',
	Chewy: 'display',
	Creepster: 'display',
	'Freckle Face': 'display',
	'Rampart One': 'display',
	Audiowide: 'display',
	Orbitron: 'display',
	Michroma: 'display',
	'Poiret One': 'display',
	Megrim: 'display',
	Silkscreen: 'display',
	'Press Start 2P': 'display',
	'Yeseva One': 'display',
	Marcellus: 'serif',
	Italiana: 'serif',
	Prata: 'serif',
	'Bodoni Moda': 'serif',
	'Gilda Display': 'serif',
	Yellowtail: 'script',
	'Kaushan Script': 'script',
	Courgette: 'script',
	'Grand Hotel': 'script',
	Parisienne: 'script',
	Allura: 'script',
	'Lobster Two': 'script',
	'Berkshire Swash': 'script',
	'Caveat Brush': 'script',
	'Rock Salt': 'script',
	'Just Another Hand': 'script',
	'Gloria Hallelujah': 'script',
	// --- Google CDN list (only with the admin's opt-in) ---
	ABeeZee: 'sans',
	'Abhaya Libre': 'serif',
	Aclonica: 'display',
	'Advent Pro': 'sans',
	Alegreya: 'serif',
	'Alegreya Sans': 'sans',
	Aleo: 'serif',
	Alice: 'serif',
	Almarai: 'sans',
	Amaranth: 'sans',
	Amiri: 'serif',
	'Antic Slab': 'serif',
	'Architects Daughter': 'script',
	'Archivo Narrow': 'sans',
	Arimo: 'sans',
	Arvo: 'serif',
	Asap: 'sans',
	Assistant: 'sans',
	'Baloo 2': 'display',
	'Barlow Semi Condensed': 'sans',
	Baskervville: 'serif',
	Bein: 'sans',
	BioRhyme: 'serif',
	'Bree Serif': 'serif',
	Cairo: 'sans',
	Cardo: 'serif',
	'Carter One': 'display',
	Catamaran: 'sans',
	'Chakra Petch': 'sans',
	Changa: 'sans',
	'Cherry Cream Soda': 'display',
	Chivo: 'sans',
	'Cinzel Decorative': 'display',
	'Concert One': 'display',
	Cookie: 'script',
	'Courier Prime': 'mono',
	'Crete Round': 'serif',
	'Crimson Pro': 'serif',
	Cuprum: 'sans',
	'DM Mono': 'mono',
	'Dela Gothic One': 'display',
	Delius: 'script',
	'Didact Gothic': 'sans',
	Domine: 'serif',
	Dosis: 'sans',
	Economica: 'sans',
	'El Messiri': 'sans',
	'Encode Sans': 'sans',
	Enriqueta: 'serif',
	Exo: 'sans',
	Fahkwang: 'sans',
	'Fira Code': 'mono',
	'Fira Sans Condensed': 'sans',
	'Fjalla One': 'display',
	'Francois One': 'display',
	'Frank Ruhl Libre': 'serif',
	Fraunces: 'serif',
	'Fredericka the Great': 'display',
	Gelasio: 'serif',
	'Gochi Hand': 'script',
	Grandstander: 'display',
	'Grenze Gotisch': 'display',
	Gruppo: 'display',
	Handlee: 'script',
	Heebo: 'sans',
	Hind: 'sans',
	'Homemade Apple': 'script',
	Inder: 'sans',
	'Instrument Serif': 'serif',
	Italianno: 'script',
	'Josefin Slab': 'serif',
	Jost: 'sans',
	Kalam: 'script',
	Karma: 'serif',
	Khand: 'sans',
	Kreon: 'serif',
	Lexend: 'sans',
	'Libre Caslon Text': 'serif',
	'Libre Franklin': 'sans',
	Limelight: 'display',
	'Londrina Solid': 'display',
	Macondo: 'display',
	'Marck Script': 'script',
	Martel: 'serif',
	'Maven Pro': 'sans',
	Merienda: 'script',
	Mitr: 'sans',
	Monda: 'sans',
	'Montserrat Alternates': 'sans',
	Mukta: 'sans',
	'Nanum Gothic': 'sans',
	Neuton: 'serif',
	'News Cycle': 'sans',
	Niconne: 'script',
	'Noticia Text': 'serif',
	'Noto Sans': 'sans',
	'Noto Serif': 'serif',
	'Old Standard TT': 'serif',
	Overpass: 'sans',
	Oxygen: 'sans',
	'PT Sans': 'sans',
	'PT Sans Narrow': 'sans',
	Pangolin: 'script',
	'Pathway Gothic One': 'sans',
	'Patua One': 'display',
	'Paytone One': 'display',
	'Petit Formal Script': 'script',
	Philosopher: 'sans',
	Play: 'sans',
	'Playfair Display SC': 'serif',
	'Pontano Sans': 'sans',
	Prompt: 'sans',
	'Public Sans': 'sans',
	Quantico: 'sans',
	Questrial: 'sans',
	Rajdhani: 'sans',
	Recursive: 'sans',
	'Red Hat Text': 'sans',
	'Reem Kufi': 'sans',
	Rokkitt: 'serif',
	Rowdies: 'display',
	'Rozha One': 'serif',
	Ruda: 'sans',
	'Russo One': 'display',
	Saira: 'sans',
	Sarabun: 'sans',
	'Sawarabi Mincho': 'serif',
	'Secular One': 'display',
	'Shadows Into Light Two': 'script',
	Signika: 'sans',
	'Six Caps': 'display',
	'Source Code Pro': 'mono',
	'Special Elite': 'display',
	Spectral: 'serif',
	'Suez One': 'serif',
	Syncopate: 'display',
	Syne: 'display',
	Tajawal: 'sans',
	Tangerine: 'script',
	'Tenor Sans': 'sans',
	Tinos: 'serif',
	'Titillium Web': 'sans',
	Ubuntu: 'sans',
	'Ubuntu Mono': 'mono',
	Unbounded: 'display',
	'Unica One': 'display',
	'Varela Round': 'sans',
	Vidaloka: 'serif',
	Volkhov: 'serif',
	Vollkorn: 'serif',
	'Yanone Kaffeesatz': 'sans',
	Zeyada: 'script',
	'Zilla Slab Highlight': 'display',
	// --- system fonts ---
	Helvetica: 'sans',
	Arial: 'sans',
	Georgia: 'serif',
};

export const FONT_CLASS_NAMES = [
	'display',
	'sans',
	'serif',
	'script',
	'mono',
];

/** The class of a family; anything unknown (a custom upload) is a sans. */
export const fontClass = ( family ) => FONT_CLASSES[ family ] || 'sans';
