/** Sudoku: 4 x 4, 6 x 6 or 9 x 9, generated by the seed, holes by level, with the solution. */
import { SHAPES, cardFrame, label, outline } from '../common.js';
import { textEl } from '../../engine/svg.js';
import { seeded } from '../../engine/rng.js';

export const SUDOKU_SIZES = [
	{ value: 4, label: '4 x 4 (kids)' },
	{ value: 6, label: '6 x 6' },
	{ value: 9, label: '9 x 9' },
];
export const SUDOKU_LEVELS = [
	{ value: 'easy', label: 'Easy' },
	{ value: 'medium', label: 'Medium' },
	{ value: 'hard', label: 'Hard' },
];
const BOX = { 4: [ 2, 2 ], 6: [ 2, 3 ], 9: [ 3, 3 ] };
const HOLES = { easy: 0.42, medium: 0.52, hard: 0.62 };

/** A full valid grid (backtracking with a seeded candidate order) and the puzzle with holes. */
export function sudoku( n, level, seed ) {
	const rnd = seeded( seed || 1 );
	const [ bh, bw ] = BOX[ n ] || BOX[ 9 ];
	const grid = [ ...Array( n ) ].map( () => Array( n ).fill( 0 ) );
	const ok = ( r, c, v ) => {
		for ( let k = 0; k < n; k++ ) {
			if ( grid[ r ][ k ] === v || grid[ k ][ c ] === v ) {
				return false;
			}
		}
		const r0 = Math.floor( r / bh ) * bh;
		const c0 = Math.floor( c / bw ) * bw;
		for ( let y = r0; y < r0 + bh; y++ ) {
			for ( let x = c0; x < c0 + bw; x++ ) {
				if ( grid[ y ][ x ] === v ) {
					return false;
				}
			}
		}
		return true;
	};
	const fill = ( pos ) => {
		if ( pos === n * n ) {
			return true;
		}
		const r = Math.floor( pos / n );
		const c = pos % n;
		const cands = [ ...Array( n ) ].map( ( _, i ) => i + 1 );
		for ( let i = cands.length - 1; i > 0; i-- ) {
			const j = Math.floor( rnd() * ( i + 1 ) );
			[ cands[ i ], cands[ j ] ] = [ cands[ j ], cands[ i ] ];
		}
		for ( const v of cands ) {
			if ( ok( r, c, v ) ) {
				grid[ r ][ c ] = v;
				if ( fill( pos + 1 ) ) {
					return true;
				}
				grid[ r ][ c ] = 0;
			}
		}
		return false;
	};
	fill( 0 );
	const solution = grid.map( ( row ) => row.slice() );
	const cells = [ ...Array( n * n ) ].map( ( _, i ) => i );
	for ( let i = cells.length - 1; i > 0; i-- ) {
		const j = Math.floor( rnd() * ( i + 1 ) );
		[ cells[ i ], cells[ j ] ] = [ cells[ j ], cells[ i ] ];
	}
	const holes = Math.round( n * n * ( HOLES[ level ] || HOLES.easy ) );
	const puzzle = solution.map( ( row ) => row.slice() );
	for ( const i of cells.slice( 0, holes ) ) {
		puzzle[ Math.floor( i / n ) ][ i % n ] = 0;
	}
	return { solution, puzzle, holes, box: [ bh, bw ] };
}

export const ITEM = {
	id: 'sudoku',
	label: 'Sudoku',
	hint: 'A sudoku from four by four for the kids to nine by nine, three levels, generated by the seed, the solution on its own sheet.',
	group: 'games',
	uses: { text: true, names: false, photo: 'none', event: [ 'title' ] },
	textLabel: 'Title over the puzzle',
	placeholder: 'Party sudoku',
	sizes: [
		{ label: '120 mm (2 per A4)', d: 120 },
		{ label: '150 mm', d: 150 },
		{ label: '90 mm (4 per A4)', d: 90 },
	],
	repeat: false,
	render( item, ctx, env ) {
		const theme = ctx.theme;
		const t = ctx.t;
		const d = item.d || 120;
		const ink = theme.colors.ink;
		const n = [ 4, 6, 9 ].includes( +item.n ) ? +item.n : 9;
		const res = sudoku( n, item.level || 'easy', item.seed || 1 );
		const title = item.text || ctx.event.title || t( 'Sudoku' );
		const capH = d * 0.14;
		const sheet = ( solution ) => {
			const shape = SHAPES.rect( d, d + capH );
			const parts = [
				cardFrame( shape, theme, {
					band: 'top',
					bandSize: capH * 0.25,
					seed: 380,
				} ),
			];
			parts.push(
				label(
					title + ( solution ? ' · ' + t( 'Solution' ) : '' ),
					{ x: d * 0.06, y: capH * 0.3, w: d * 0.88, h: capH * 0.6 },
					{
						font: theme.displayFont,
						weight: 700,
						color: ink,
						maxSize: capH * 0.5,
						wrap: false,
					},
					env
				)
			);
			const margin = d * 0.05;
			const g = d - 2 * margin;
			const cell = g / n;
			const gy = capH;
			const [ bh, bw ] = res.box;
			for ( let r = 0; r < n; r++ ) {
				for ( let c = 0; c < n; c++ ) {
					const given = res.puzzle[ r ][ c ];
					const v = solution ? res.solution[ r ][ c ] : given;
					if ( ! v ) {
						continue;
					}
					parts.push(
						textEl(
							margin + ( c + 0.5 ) * cell,
							gy + ( r + 0.72 ) * cell,
							String( v ),
							{
								size: ( cell * 0.6 ).toFixed( 2 ),
								font: theme.textFont,
								weight: given ? 700 : 400,
								fill: given ? ink : theme.colors.accent,
								anchor: 'middle',
							}
						)
					);
				}
			}
			for ( let k = 0; k <= n; k++ ) {
				const thickRow = k % bh === 0;
				const thickCol = k % bw === 0;
				parts.push(
					`<line x1="${ margin.toFixed( 2 ) }" y1="${ (
						gy +
						k * cell
					).toFixed( 2 ) }" x2="${ ( margin + g ).toFixed(
						2
					) }" y2="${ ( gy + k * cell ).toFixed(
						2
					) }" stroke="${ ink }" stroke-width="${
						thickRow ? 0.7 : 0.2
					}"/>`
				);
				parts.push(
					`<line x1="${ ( margin + k * cell ).toFixed(
						2
					) }" y1="${ gy.toFixed( 2 ) }" x2="${ (
						margin +
						k * cell
					).toFixed( 2 ) }" y2="${ ( gy + g ).toFixed(
						2
					) }" stroke="${ ink }" stroke-width="${
						thickCol ? 0.7 : 0.2
					}"/>`
				);
			}
			parts.push( outline( shape, ink, 0.25 ) );
			return { inner: parts.join( '' ), w: d, h: d + capH };
		};
		const pieces = [ sheet( false ) ];
		if ( false !== item.solution ) {
			pieces.push( sheet( true ) );
		}
		return { pieces, warnings: [] };
	},
};
