/**
 * The schools: how a movement paints, as a recipe the society follows
 * with its own temperament.
 *
 * A school is data, never a script: which palette taste, which ground,
 * which compositions it likes, how large and how fast its hands move,
 * and a VOCABULARY per phase - what kinds of marks its painters reach
 * for while the picture opens, builds, develops and finishes. The
 * painters decide when, where and how big; the school decides the
 * grammar. Add a school, get a new kind of picture.
 *
 * Painterly schools speak through the editor's own brush engine: a
 * `brush` item names media heads (the editor's 18 media brushes) and a
 * paint style, `wet: true` asks for the physics island. The schools
 * that are not brushes (geometry, torn paper, op lines) keep the own
 * marks of flat/marks.js.
 *
 * `phases` are fractions of the plan's coverage target at which the
 * picture moves on.
 */

const OIL = [ 'oil-bristle', 'oil-filbert', 'oil-knife' ];
const ACRYL = [ 'acrylic-flat', 'acrylic-filbert', 'acrylic-knife' ];
const GOUACHE = [ 'gouache-flat', 'gouache-round', 'gouache-dry' ];
const WASH = [ 'wash-round', 'wash-flat', 'wash-mop' ];
const INK = [ 'ink-nib', 'ink-brushpen', 'ink-broad' ];
const CHARCOAL = [ 'charcoal-tip', 'charcoal-side', 'charcoal-soft' ];

const PH = { opening: 0.3, building: 0.62, developing: 0.88 };

export const SCHOOLS = [
	{
		id: 'impressionism',
		label: 'Impressionism',
		blurb: 'Broken color in soft light, laid on in short dabs of oil.',
		palette: 'highkey',
		ground: { paper: 'canvas', tone: 'light', grain: 0.3, wash: true },
		plan: {
			archetypes: {
				horizon: 3,
				field: 2,
				mass: 2,
				stack: 1,
				diagonal: 0.5,
				cascade: 0.3,
			},
			coverage: [ 0.85, 1 ],
			valueKeys: [ 'high', 'mid' ],
		},
		tempo: { rate: 1.1, painters: [ 5, 12 ], duration: [ 0.4, 1.2 ] },
		hand: { tremor: 0.35, haste: 0.55, overshoot: 0.15, hesitate: 0.1 },
		light: -2.3,
		vocab: {
			opening: [
				{
					kind: 'blockin',
					w: 5,
					size: 'mid',
					color: 'local',
					tips: GOUACHE,
					style: 'gouache',
					wet: true,
					ratio: [ 1.3, 2.1 ],
					opacity: [ 0.6, 0.85 ],
					flow: [ 0.8, 1 ],
					colorVar: 0.1,
					taper: 1,
					rows: [ 4, 7 ],
				},
				{
					kind: 'brush',
					w: 1,
					size: 'big',
					color: 'local',
					tips: GOUACHE,
					style: 'gouache',
					wet: true,
					ratio: [ 1.3, 2.1 ],
					elong: [ 0.9, 1.5 ],
					opacity: [ 0.7, 0.85 ],
					flow: [ 0.8, 1 ],
					colorVar: 0.1,
					gestures: [ 'slash', 'blob', 'arc' ],
					along: 'plan',
					count: [ 3, 6 ],
					taper: 1,
				},
			],
			building: [
				{
					kind: 'brush',
					w: 4,
					size: 'small',
					color: 'broken',
					tips: GOUACHE,
					style: 'gouache',
					wet: true,
					ratio: [ 1.4, 2.3 ],
					elong: [ 0.5, 0.9 ],
					opacity: [ 0.9, 1 ],
					flow: [ 0.8, 1 ],
					colorVar: 0.14,
					gestures: [ 'slash', 'hook' ],
					along: 'mass',
					count: [ 5, 10 ],
					alongVar: 0.5,
					taper: 1,
				},
				{
					kind: 'brush',
					w: 2,
					size: 'small',
					color: 'local',
					tips: OIL,
					style: 'oil',
					wet: true,
					ratio: [ 1.5, 2.4 ],
					elong: [ 0.5, 0.9 ],
					opacity: [ 0.9, 1 ],
					flow: [ 0.7, 0.9 ],
					colorVar: 0.1,
					gestures: [ 'slash' ],
					along: 'mass',
					count: [ 3, 6 ],
					alongVar: 0.4,
					taper: 1,
				},
			],
			developing: [
				{
					kind: 'brush',
					w: 4,
					size: 'small',
					color: 'broken',
					tips: GOUACHE,
					style: 'gouache',
					wet: true,
					ratio: [ 1.4, 2.3 ],
					elong: [ 0.5, 0.9 ],
					opacity: [ 0.95, 1 ],
					flow: [ 0.8, 1 ],
					colorVar: 0.16,
					gestures: [ 'slash', 'hook' ],
					along: 'mass',
					count: [ 5, 10 ],
					alongVar: 0.6,
					taper: 1,
				},
				{
					kind: 'brush',
					w: 2,
					size: 'accent',
					color: 'complement',
					tips: OIL,
					style: 'oil',
					wet: true,
					ratio: [ 1.4, 2.2 ],
					elong: [ 0.5, 0.9 ],
					opacity: [ 0.95, 1 ],
					gestures: [ 'slash' ],
					count: [ 3, 6 ],
					taper: 1,
				},
			],
			finishing: [
				{
					kind: 'brush',
					w: 3,
					size: 'accent',
					color: 'light',
					tips: OIL,
					style: 'oil',
					wet: true,
					ratio: [ 1.3, 2.2 ],
					elong: [ 0.5, 0.9 ],
					opacity: [ 1, 1 ],
					flow: [ 0.9, 1 ],
					colorVar: 0.06,
					gestures: [ 'slash' ],
					count: [ 3, 7 ],
					taper: 1,
				},
				{
					kind: 'brush',
					w: 1,
					size: 'accent',
					color: 'dark',
					tips: OIL,
					style: 'oil',
					wet: true,
					ratio: [ 1.6, 2.8 ],
					elong: [ 0.5, 1 ],
					opacity: [ 0.9, 1 ],
					gestures: [ 'hook', 'slash' ],
					count: [ 2, 4 ],
					taper: 1,
				},
			],
		},
		phases: PH,
		finish: { paper: 0.14, vignette: 0.08 },
	},
	{
		id: 'pointillism',
		label: 'Pointillism',
		blurb: 'The whole picture from tiny dots of pure color.',
		palette: 'optical',
		ground: { paper: 'canvas', tone: 'white', grain: 0.25 },
		plan: {
			archetypes: { horizon: 3, mass: 2, field: 1, stack: 1, duet: 1 },
			coverage: [ 0.8, 1 ],
			valueKeys: [ 'high', 'mid' ],
		},
		tempo: { rate: 2.2, painters: [ 8, 18 ], duration: [ 0.3, 0.9 ] },
		span: 160,
		hand: { tremor: 0.2, haste: 0.3 },
		vocab: {
			opening: [
				{
					kind: 'dots',
					w: 4,
					size: 'big',
					color: 'local',
					tip: 'round',
					n: [ 260, 420 ],
					dot: [ 0.006, 0.011 ],
					alpha: [ 0.9, 1 ],
					colorVar: 0.08,
					spread: 0.55,
				},
			],
			building: [
				{
					kind: 'dots',
					w: 4,
					size: 'mid',
					color: 'broken',
					tip: 'round',
					n: [ 160, 300 ],
					dot: [ 0.005, 0.01 ],
					alpha: [ 0.95, 1 ],
					colorVar: 0.1,
					spread: 0.65,
				},
			],
			developing: [
				{
					kind: 'dots',
					w: 4,
					size: 'small',
					color: 'broken',
					tip: 'round',
					n: [ 90, 180 ],
					dot: [ 0.004, 0.009 ],
					alpha: [ 0.95, 1 ],
					colorVar: 0.1,
					spread: 0.7,
				},
				{
					kind: 'dots',
					w: 2,
					size: 'small',
					color: 'complement',
					tip: 'round',
					n: [ 60, 120 ],
					dot: [ 0.004, 0.008 ],
					alpha: [ 0.95, 1 ],
					spread: 0.7,
				},
			],
			finishing: [
				{
					kind: 'dots',
					w: 3,
					size: 'accent',
					color: 'dark',
					tip: 'round',
					n: [ 40, 90 ],
					dot: [ 0.004, 0.008 ],
					alpha: [ 0.95, 1 ],
				},
			],
		},
		phases: PH,
		finish: { paper: 0.12, vignette: 0.05 },
	},
	{
		id: 'expressionism',
		label: 'Expressionism',
		blurb: 'Loud color, thick paint, black contours that will not sit still.',
		palette: 'pure',
		ground: { paper: 'canvas', tone: 'mid', grain: 0.35 },
		plan: {
			archetypes: {
				mass: 3,
				diagonal: 2,
				cluster: 2,
				duet: 1,
				cascade: 1,
				field: 1,
				single: 0.3,
			},
			coverage: [ 0.55, 0.9 ],
			valueKeys: [ 'mid', 'low' ],
		},
		tempo: { rate: 0.8, painters: [ 4, 9 ], duration: [ 0.3, 1 ] },
		hand: { tremor: 0.55, haste: 0.75, overshoot: 0.6, hesitate: 0.2 },
		light: -2.4,
		vocab: {
			opening: [
				{
					kind: 'blockin',
					w: 5,
					size: 'mid',
					color: 'local',
					tips: ACRYL,
					style: 'acrylic',
					wet: true,
					ratio: [ 1.8, 3.2 ],
					opacity: [ 0.6, 0.85 ],
					flow: [ 0.8, 1 ],
					colorVar: 0.1,
					taper: 2,
					rows: [ 4, 7 ],
				},
				{
					kind: 'brush',
					w: 1,
					size: 'big',
					color: 'local',
					tips: ACRYL,
					style: 'acrylic',
					wet: true,
					ratio: [ 1.8, 3.2 ],
					elong: [ 0.8, 1.4 ],
					opacity: [ 0.9, 1 ],
					flow: [ 0.8, 1 ],
					colorVar: 0.06,
					gestures: [ 'slash', 'zigzag', 'arc', 'hook' ],
					count: [ 1, 3 ],
					taper: 2,
				},
				{
					kind: 'shape',
					w: 1,
					size: 'big',
					color: 'local',
					shapes: [ 'poly' ],
					edge: 'ragged',
					rag: 0.8,
					alpha: [ 0.85, 1 ],
				},
			],
			building: [
				{
					kind: 'brush',
					w: 3,
					size: 'mid',
					color: 'local',
					tips: OIL,
					style: 'oil',
					wet: true,
					ratio: [ 1.6, 2.6 ],
					elong: [ 0.8, 1.4 ],
					opacity: [ 0.9, 1 ],
					flow: [ 0.8, 1 ],
					colorVar: 0.08,
					gestures: [ 'slash', 'zigzag', 'hook', 'scurve' ],
					count: [ 1, 3 ],
					taper: 2,
				},
				{
					kind: 'brush',
					w: 1.5,
					size: 'mid',
					color: 'complement',
					tips: ACRYL,
					style: 'acrylic',
					wet: true,
					ratio: [ 2, 3.5 ],
					elong: [ 0.8, 1.3 ],
					opacity: [ 0.9, 1 ],
					gestures: [ 'slash', 'arc' ],
					count: [ 1, 2 ],
					taper: 2,
				},
			],
			developing: [
				{
					kind: 'brushContour',
					w: 3,
					color: 'dark',
					tips: INK,
					style: 'ink',
					wet: true,
					width: [ 0.006, 0.014 ],
					opacity: [ 0.9, 1 ],
				},
				{
					kind: 'brush',
					w: 2,
					size: 'small',
					color: 'accent',
					tips: OIL,
					style: 'oil',
					wet: true,
					ratio: [ 1.8, 3 ],
					elong: [ 0.6, 1.1 ],
					opacity: [ 0.95, 1 ],
					gestures: [ 'slash', 'zigzag' ],
					count: [ 2, 4 ],
					taper: 1,
				},
			],
			finishing: [
				{
					kind: 'brushContour',
					w: 2,
					color: 'dark',
					tips: INK,
					style: 'ink',
					wet: true,
					width: [ 0.006, 0.014 ],
					opacity: [ 0.95, 1 ],
				},
				{
					kind: 'brush',
					w: 2,
					size: 'accent',
					color: 'light',
					tips: OIL,
					style: 'oil',
					wet: true,
					ratio: [ 1.6, 2.6 ],
					elong: [ 0.5, 1 ],
					opacity: [ 0.95, 1 ],
					gestures: [ 'slash' ],
					count: [ 2, 4 ],
					taper: 1,
				},
				{ kind: 'drip', w: 0.5, color: 'dark' },
			],
		},
		phases: PH,
		finish: { paper: 0.12, vignette: 0.12 },
	},
	{
		id: 'fauvism',
		label: 'Fauvism',
		blurb: 'Pure color in flat patches, and the white between them left alone.',
		palette: 'pure',
		ground: { paper: 'canvas', tone: 'white', grain: 0.3 },
		plan: {
			archetypes: { mass: 3, field: 2, horizon: 2, duet: 1, cluster: 1 },
			coverage: [ 0.6, 0.85 ],
			valueKeys: [ 'high', 'mid' ],
		},
		tempo: { rate: 0.8, painters: [ 3, 7 ], duration: [ 0.4, 1.2 ] },
		hand: { tremor: 0.4, haste: 0.5, overshoot: 0.2 },
		vocab: {
			opening: [
				{
					kind: 'blockin',
					w: 5,
					size: 'mid',
					color: 'local',
					tips: GOUACHE,
					style: 'gouache',
					wet: true,
					ratio: [ 2, 3.6 ],
					opacity: [ 0.6, 0.85 ],
					flow: [ 0.9, 1 ],
					taper: 1,
					colorVar: 0.1,
					rows: [ 4, 7 ],
				},
				{
					kind: 'brush',
					w: 1,
					size: 'big',
					color: 'local',
					tips: GOUACHE,
					style: 'gouache',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.95, 1 ],
					flow: [ 0.9, 1 ],
					gestures: [ 'slash', 'arc', 'blob' ],
					taper: 1,
				},
				{
					kind: 'shape',
					w: 1,
					size: 'big',
					color: 'local',
					shapes: [ 'poly' ],
					edge: 'ragged',
					rag: 1,
					alpha: [ 0.9, 1 ],
				},
			],
			building: [
				{
					kind: 'brush',
					w: 3,
					size: 'mid',
					color: 'any',
					tips: GOUACHE,
					style: 'gouache',
					wet: true,
					ratio: [ 4.7, 8.7 ],
					opacity: [ 0.95, 1 ],
					gestures: [ 'slash', 'blob', 'arc' ],
					taper: 1,
				},
				{
					kind: 'brush',
					w: 2,
					size: 'mid',
					color: 'complement',
					tips: ACRYL,
					style: 'acrylic',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.95, 1 ],
					gestures: [ 'slash', 'scurve' ],
					taper: 1,
				},
			],
			developing: [
				{
					kind: 'brushContour',
					w: 3,
					color: 'complement',
					tips: INK,
					style: 'ink',
					wet: true,
					width: [ 0.006, 0.014 ],
					opacity: [ 0.9, 1 ],
				},
				{
					kind: 'brush',
					w: 1,
					size: 'small',
					color: 'any',
					tips: GOUACHE,
					style: 'gouache',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.95, 1 ],
					gestures: [ 'slash' ],
				},
			],
			finishing: [
				{
					kind: 'brushContour',
					w: 2,
					color: 'dark',
					tips: INK,
					style: 'ink',
					wet: true,
					width: [ 0.006, 0.014 ],
					opacity: [ 0.9, 1 ],
				},
				{
					kind: 'brush',
					w: 1,
					size: 'accent',
					color: 'accent',
					tips: GOUACHE,
					style: 'gouache',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 1, 1 ],
					gestures: [ 'slash' ],
				},
			],
		},
		phases: PH,
		finish: { paper: 0.1, vignette: 0.06 },
	},
	{
		id: 'cubism',
		label: 'Cubism',
		blurb: 'One thing seen from many sides at once, in planes of umber and gray.',
		palette: 'earth',
		ground: { paper: 'canvas', tone: 'palette-light', grain: 0.35 },
		plan: {
			archetypes: {
				mass: 4,
				frame: 2,
				diagonal: 2,
				duet: 1,
				cluster: 1,
				horizon: 0.5,
			},
			coverage: [ 0.6, 0.9 ],
			valueKeys: [ 'mid' ],
		},
		tempo: { rate: 0.6, painters: [ 3, 7 ], duration: [ 0.4, 1.2 ] },
		hand: { tremor: 0.25, haste: 0.4 },
		axes: 3,
		vocab: {
			opening: [
				{
					kind: 'piece',
					w: 3,
					size: 'mid',
					color: 'local',
					edge: 'cut',
					place: 'source',
					treatments: [ 'posterize', 'edges', 'none' ],
					alpha: [ 0.9, 1 ],
					shadow: 0.15,
				},
				{
					kind: 'facet',
					w: 4,
					size: 'big',
					color: 'local',
					alpha: [ 0.75, 0.9 ],
					shading: 0.28,
				},
			],
			building: [
				{
					kind: 'piece',
					w: 2,
					size: 'small',
					color: 'local',
					edge: 'cut',
					treatments: [ 'posterize', 'edges' ],
					alpha: [ 0.9, 1 ],
					shadow: 0.15,
				},
				{
					kind: 'facet',
					w: 4,
					size: 'mid',
					color: 'any',
					alpha: [ 0.7, 0.9 ],
					shading: 0.3,
				},
				{
					kind: 'brush',
					w: 1.5,
					size: 'mid',
					color: 'dark',
					tips: CHARCOAL,
					style: 'charcoal',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.5, 0.8 ],
					gestures: [ 'slash', 'zigzag' ],
					taper: 1,
				},
			],
			developing: [
				{
					kind: 'facet',
					w: 2,
					size: 'small',
					color: 'any',
					alpha: [ 0.7, 0.9 ],
					shading: 0.35,
				},
				{
					kind: 'hatch',
					w: 2,
					size: 'small',
					color: 'dark',
					alpha: [ 0.5, 0.8 ],
				},
				{
					kind: 'edge',
					w: 2,
					color: 'dark',
					width: [ 0.002, 0.004 ],
					alpha: [ 0.7, 0.9 ],
				},
				{
					kind: 'cut',
					w: 0.6,
					size: 'small',
					color: 'light',
					print: 'text',
					paper: 'kraft',
				},
			],
			finishing: [
				{
					kind: 'edge',
					w: 3,
					color: 'dark',
					width: [ 0.002, 0.005 ],
					alpha: [ 0.8, 1 ],
				},
				{
					kind: 'shape',
					w: 1,
					size: 'accent',
					color: 'accent',
					shapes: [ 'rect', 'circle' ],
					edge: 'crisp',
					alpha: [ 0.9, 1 ],
				},
			],
		},
		phases: PH,
		finish: { paper: 0.18, vignette: 0.14 },
	},
	{
		id: 'classicism',
		label: 'Classicism',
		blurb: 'Golden proportion, warm shadow, light that arrives from one side.',
		palette: 'earth',
		ground: {
			paper: 'canvas',
			tone: 'palette-dark',
			grain: 0.4,
			wash: true,
		},
		plan: {
			archetypes: {
				mass: 3,
				duet: 2,
				frame: 2,
				horizon: 1,
				stack: 0.5,
				single: 1,
			},
			coverage: [ 0.5, 0.85 ],
			valueKeys: [ 'low', 'mid' ],
		},
		tempo: { rate: 0.5, painters: [ 2, 5 ], duration: [ 0.9, 2.4 ] },
		hand: { tremor: 0.15, haste: 0.25, hesitate: 0.3 },
		light: -2.6,
		vocab: {
			opening: [
				{
					kind: 'blockin',
					w: 4,
					size: 'mid',
					color: 'local',
					tips: OIL,
					style: 'oil',
					wet: true,
					ratio: [ 2.5, 4 ],
					opacity: [ 0.6, 0.85 ],
					flow: [ 0.8, 1 ],
					colorVar: 0.1,
					rows: [ 4, 6 ],
				},
				{
					kind: 'wash',
					w: 3,
					size: 'big',
					color: 'local',
					alpha: [ 0.3, 0.5 ],
					blend: 'source-over',
					rim: 0,
					edge: 0.05,
				},
				{
					kind: 'wash',
					w: 2,
					size: 'big',
					color: 'shadow',
					alpha: [ 0.25, 0.4 ],
					blend: 'multiply',
					rim: 0,
					edge: 0.05,
				},
			],
			building: [
				{
					kind: 'brush',
					w: 3,
					size: 'mid',
					color: 'local',
					tips: [ 'oil-filbert', 'gouache-round' ],
					style: 'oil',
					wet: true,
					ratio: [ 1.2, 1.9 ],
					elong: [ 0.7, 1.2 ],
					opacity: [ 0.35, 0.55 ],
					flow: [ 0.5, 0.8 ],
					colorVar: 0.04,
					gestures: [ 'arc', 'blob' ],
					count: [ 2, 4 ],
					taper: 1,
					hardness: 60,
				},
				{
					kind: 'brush',
					w: 2,
					size: 'mid',
					color: 'shadow',
					tips: [ 'oil-filbert' ],
					style: 'oil',
					wet: true,
					ratio: [ 1.2, 1.9 ],
					elong: [ 0.7, 1.2 ],
					opacity: [ 0.3, 0.45 ],
					flow: [ 0.4, 0.7 ],
					gestures: [ 'arc', 'blob' ],
					count: [ 2, 3 ],
					taper: 1,
					hardness: 55,
				},
				{
					kind: 'brush',
					w: 2,
					size: 'mid',
					color: 'local',
					tips: [ 'oil-filbert', 'gouache-round' ],
					style: 'smudge',
					wet: true,
					ratio: [ 1.3, 2 ],
					opacity: [ 1, 1 ],
					gestures: [ 'arc', 'scurve' ],
					count: [ 1, 2 ],
					taper: 1,
					hardness: 50,
				},
			],
			developing: [
				{
					kind: 'brush',
					w: 3,
					size: 'small',
					color: 'lit',
					tips: [ 'oil-filbert', 'oil-bristle' ],
					style: 'oil',
					wet: true,
					ratio: [ 1.3, 2.2 ],
					elong: [ 0.6, 1 ],
					opacity: [ 0.45, 0.7 ],
					flow: [ 0.6, 0.9 ],
					gestures: [ 'arc', 'slash' ],
					count: [ 2, 4 ],
					taper: 1,
					hardness: 70,
				},
				{
					kind: 'glaze',
					w: 1,
					region: 'mass',
					color: 'accent',
					alpha: [ 0.08, 0.16 ],
					blend: 'multiply',
					soft: true,
				},
				{
					kind: 'brush',
					w: 1,
					size: 'mid',
					color: 'local',
					tips: [ 'oil-filbert' ],
					style: 'smudge',
					wet: true,
					ratio: [ 1.3, 2 ],
					opacity: [ 1, 1 ],
					gestures: [ 'arc' ],
					taper: 1,
					hardness: 50,
				},
			],
			finishing: [
				{
					kind: 'brush',
					w: 3,
					size: 'accent',
					color: 'light',
					tips: [ 'oil-filbert', 'oil-bristle' ],
					style: 'oil',
					wet: true,
					ratio: [ 1.6, 2.6 ],
					elong: [ 0.5, 1 ],
					opacity: [ 0.8, 1 ],
					gestures: [ 'arc', 'hook' ],
					count: [ 2, 4 ],
					taper: 1,
				},
				{
					kind: 'wash',
					w: 1,
					size: 'small',
					color: 'dark',
					alpha: [ 0.25, 0.4 ],
					blend: 'multiply',
					rim: 0.1,
				},
			],
		},
		phases: PH,
		finish: { paper: 0.1, vignette: 0.26 },
	},
	{
		id: 'bauhaus',
		label: 'Bauhaus',
		blurb: 'Circle, bar and triangle in primary colors, balanced on a diagonal.',
		palette: 'primaries',
		paletteStrict: true,
		ground: { paper: 'paper', tone: 'white', grain: 0.2 },
		plan: {
			archetypes: {
				diagonal: 3,
				mass: 2,
				grid: 2,
				duet: 2,
				single: 1,
				field: 0.5,
				cluster: 0.5,
			},
			coverage: [ 0.25, 0.6 ],
			valueKeys: [ 'high' ],
		},
		tempo: { rate: 0.4, painters: [ 2, 5 ], duration: [ 0.6, 1.6 ] },
		hand: { tremor: 0.05, haste: 0.3 },
		vocab: {
			opening: [
				{
					kind: 'shape',
					w: 4,
					size: 'big',
					color: 'local',
					shapes: [ 'circle', 'bar', 'rect', 'tri' ],
					edge: 'print',
					alpha: [ 0.92, 1 ],
					blend: 'multiply',
					align: 'plan',
				},
			],
			building: [
				{
					kind: 'shape',
					w: 4,
					size: 'mid',
					color: 'any',
					shapes: [ 'circle', 'bar', 'tri', 'ring', 'wedge' ],
					edge: 'print',
					alpha: [ 0.9, 1 ],
					blend: 'multiply',
					align: 'plan',
				},
				{
					kind: 'line',
					w: 1.5,
					size: 'big',
					color: 'dark',
					width: [ 0.002, 0.006 ],
					align: 'plan',
				},
			],
			developing: [
				{
					kind: 'shape',
					w: 2,
					size: 'small',
					color: 'any',
					shapes: [ 'circle', 'bar', 'ring' ],
					edge: 'print',
					alpha: [ 0.9, 1 ],
					blend: 'multiply',
					align: 'plan',
				},
				{
					kind: 'line',
					w: 2,
					size: 'mid',
					color: 'dark',
					width: [ 0.0015, 0.004 ],
					align: 'plan',
				},
			],
			finishing: [
				{
					kind: 'shape',
					w: 2,
					size: 'accent',
					color: 'dark',
					shapes: [ 'circle', 'bar' ],
					edge: 'crisp',
					alpha: [ 1, 1 ],
				},
				{
					kind: 'line',
					w: 1,
					size: 'small',
					color: 'accent',
					width: [ 0.002, 0.004 ],
					align: 'plan',
				},
			],
		},
		phases: PH,
		finish: { paper: 0.14, vignette: 0.04 },
	},
	{
		id: 'suprematism',
		label: 'Suprematism',
		blurb: 'Black and red forms floating on white, weightless and tilted.',
		palette: 'primaries',
		paletteStrict: true,
		ground: { paper: 'paper', tone: 'white', grain: 0.2 },
		plan: {
			archetypes: {
				diagonal: 4,
				single: 2,
				duet: 2,
				cascade: 1,
				mass: 1,
			},
			coverage: [ 0.12, 0.4 ],
			valueKeys: [ 'high' ],
		},
		tempo: { rate: 0.35, painters: [ 2, 4 ], duration: [ 0.6, 1.6 ] },
		hand: { tremor: 0.05, haste: 0.3 },
		vocab: {
			opening: [
				{
					kind: 'shape',
					w: 4,
					size: 'big',
					color: 'dark',
					shapes: [ 'rect', 'bar' ],
					edge: 'crisp',
					alpha: [ 1, 1 ],
					align: 'plan',
				},
			],
			building: [
				{
					kind: 'shape',
					w: 3,
					size: 'mid',
					color: 'accent',
					shapes: [ 'bar', 'rect', 'tri' ],
					edge: 'crisp',
					alpha: [ 1, 1 ],
					align: 'plan',
				},
				{
					kind: 'shape',
					w: 2,
					size: 'mid',
					color: 'dark',
					shapes: [ 'bar', 'rect' ],
					edge: 'crisp',
					alpha: [ 1, 1 ],
					align: 'plan',
				},
			],
			developing: [
				{
					kind: 'shape',
					w: 3,
					size: 'small',
					color: 'any',
					shapes: [ 'bar', 'rect', 'circle' ],
					edge: 'crisp',
					alpha: [ 1, 1 ],
					align: 'plan',
				},
			],
			finishing: [
				{
					kind: 'shape',
					w: 2,
					size: 'accent',
					color: 'dark',
					shapes: [ 'bar' ],
					edge: 'crisp',
					alpha: [ 1, 1 ],
					align: 'plan',
				},
			],
		},
		phases: PH,
		finish: { paper: 0.12, vignette: 0.03 },
	},
	{
		id: 'destijl',
		label: 'De Stijl',
		blurb: 'Black rules dividing white, a few cells in red, yellow and blue.',
		palette: 'primaries',
		paletteStrict: true,
		ground: { paper: 'paper', tone: 'white', grain: 0.15 },
		plan: {
			archetypes: { grid: 1 },
			coverage: [ 0.9, 1 ],
			valueKeys: [ 'high' ],
		},
		tempo: { rate: 0.5, painters: [ 2, 4 ], duration: [ 0.5, 1.4 ] },
		hand: { tremor: 0.03, haste: 0.3 },
		vocab: {
			opening: [
				{
					kind: 'gridline',
					w: 4,
					color: 'dark',
					width: [ 0.008, 0.02 ],
				},
			],
			building: [
				{
					kind: 'gridline',
					w: 3,
					color: 'dark',
					width: [ 0.006, 0.016 ],
				},
				{ kind: 'cell', w: 2, color: 'any' },
			],
			developing: [
				{ kind: 'cell', w: 3, color: 'any' },
				{
					kind: 'gridline',
					w: 1,
					color: 'dark',
					width: [ 0.004, 0.01 ],
				},
			],
			finishing: [ { kind: 'cell', w: 1, color: 'dark' } ],
		},
		phases: PH,
		finish: { paper: 0.1, vignette: 0.02 },
	},
	{
		id: 'action',
		label: 'Action painting',
		blurb: 'The whole arm in every stroke, drips and splatter where it ended.',
		palette: 'vivid',
		ground: { paper: 'canvas', tone: 'light', grain: 0.45 },
		plan: {
			archetypes: {
				field: 3,
				diagonal: 2,
				mass: 1,
				cluster: 1,
				vortex: 1,
				single: 0.5,
			},
			coverage: [ 0.6, 0.95 ],
			valueKeys: [ 'mid', 'high' ],
		},
		tempo: { rate: 0.9, painters: [ 3, 7 ], duration: [ 0.25, 0.8 ] },
		hand: { tremor: 0.5, haste: 0.9, overshoot: 0.8, hesitate: 0.1 },
		vocab: {
			opening: [
				{
					kind: 'brush',
					w: 2,
					size: 'big',
					color: 'any',
					tips: WASH,
					style: 'watercolor',
					wet: true,
					ratio: [ 4.3, 7.4 ],
					opacity: [ 0.5, 0.8 ],
					flow: [ 0.8, 1 ],
					gestures: [ 'blob', 'arc' ],
					taper: 1,
				},
				{
					kind: 'brush',
					w: 3,
					size: 'big',
					color: 'any',
					tips: ACRYL,
					style: 'acrylic',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.9, 1 ],
					flow: [ 0.7, 1 ],
					gestures: [ 'slash', 'arc', 'scurve', 'zigzag', 'loop' ],
				},
			],
			building: [
				{
					kind: 'brush',
					w: 4,
					size: 'big',
					color: 'dark',
					tips: ACRYL,
					style: 'acrylic',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.95, 1 ],
					flow: [ 0.7, 1 ],
					gestures: [ 'slash', 'hook', 'arc', 'scurve' ],
				},
				{
					kind: 'brush',
					w: 2,
					size: 'mid',
					color: 'any',
					tips: OIL,
					style: 'oil',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.9, 1 ],
					gestures: [ 'slash', 'zigzag' ],
				},
				{ kind: 'splatter', w: 1.5, size: 'mid', color: 'any' },
			],
			developing: [
				{
					kind: 'brush',
					w: 2,
					size: 'mid',
					color: 'light',
					tips: ACRYL,
					style: 'acrylic',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.95, 1 ],
					gestures: [ 'slash', 'arc' ],
				},
				{ kind: 'splatter', w: 2, size: 'mid', color: 'dark' },
				{ kind: 'drip', w: 1.5, color: 'any' },
				{
					kind: 'brush',
					w: 1,
					size: 'mid',
					color: 'any',
					tips: [ 'oil-filbert' ],
					style: 'smudge',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 1, 1 ],
					gestures: [ 'slash', 'scurve' ],
				},
			],
			finishing: [
				{
					kind: 'brush',
					w: 2,
					size: 'accent',
					color: 'accent',
					tips: ACRYL,
					style: 'acrylic',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 1, 1 ],
					gestures: [ 'slash', 'hook' ],
					taper: 1,
				},
				{ kind: 'splatter', w: 2, size: 'small', color: 'dark' },
				{ kind: 'drip', w: 1, color: 'dark' },
			],
		},
		phases: PH,
		finish: { paper: 0.14, vignette: 0.06 },
	},
	{
		id: 'colorfield',
		label: 'Color Field',
		blurb: 'Bands of luminous color, breathing at their edges.',
		palette: 'luminous',
		ground: { paper: 'canvas', tone: 'palette-dark', grain: 0.3 },
		plan: {
			archetypes: { stack: 5, single: 1, frame: 1 },
			coverage: [ 0.9, 1 ],
			valueKeys: [ 'mid', 'low' ],
		},
		tempo: { rate: 0.4, painters: [ 2, 3 ], duration: [ 1.2, 3 ] },
		hand: { tremor: 0.1, haste: 0.2 },
		vocab: {
			opening: [
				{
					kind: 'band',
					w: 4,
					color: 'local',
					alpha: [ 0.25, 0.4 ],
					soft: 5,
				},
			],
			building: [
				{
					kind: 'band',
					w: 3,
					color: 'local',
					alpha: [ 0.2, 0.35 ],
					soft: 6,
				},
				{
					kind: 'brush',
					w: 3,
					size: 'big',
					color: 'local',
					tips: WASH,
					style: 'watercolor',
					wet: true,
					ratio: [ 3.2, 5.2 ],
					opacity: [ 0.3, 0.5 ],
					flow: [ 0.8, 1 ],
					gestures: [ 'slash', 'scurve' ],
					along: 'plan',
					taper: 1,
				},
				{
					kind: 'glaze',
					w: 1,
					region: 'all',
					color: 'any',
					alpha: [ 0.06, 0.12 ],
					blend: 'multiply',
				},
			],
			developing: [
				{
					kind: 'band',
					w: 3,
					color: 'lit',
					alpha: [ 0.15, 0.3 ],
					soft: 7,
				},
				{
					kind: 'brush',
					w: 2,
					size: 'big',
					color: 'lit',
					tips: WASH,
					style: 'watercolor',
					wet: true,
					ratio: [ 3.2, 5.2 ],
					opacity: [ 0.25, 0.45 ],
					gestures: [ 'slash' ],
					along: 'plan',
					taper: 1,
				},
			],
			finishing: [
				{
					kind: 'band',
					w: 2,
					color: 'light',
					alpha: [ 0.1, 0.2 ],
					soft: 8,
				},
			],
		},
		phases: PH,
		finish: { paper: 0.18, vignette: 0.1 },
	},
	{
		id: 'minimalism',
		label: 'Minimalism',
		blurb: 'One shape, one line, and the room around them.',
		palette: 'mono',
		paletteStrict: true,
		ground: { paper: 'paper', tone: 'white', grain: 0.12 },
		plan: {
			archetypes: {
				single: 4,
				duet: 2,
				stack: 1,
				diagonal: 1,
				horizon: 1,
			},
			coverage: [ 0.05, 0.25 ],
			valueKeys: [ 'high' ],
		},
		tempo: { rate: 0.25, painters: [ 1, 3 ], duration: [ 0.8, 2 ] },
		hand: { tremor: 0.03, haste: 0.3 },
		vocab: {
			opening: [
				{
					kind: 'shape',
					w: 4,
					size: 'big',
					color: 'local',
					shapes: [ 'rect', 'circle', 'bar' ],
					edge: 'crisp',
					alpha: [ 1, 1 ],
					align: 'plan',
				},
			],
			building: [
				{
					kind: 'line',
					w: 3,
					size: 'big',
					color: 'dark',
					width: [ 0.002, 0.005 ],
					align: 'plan',
				},
				{
					kind: 'shape',
					w: 1,
					size: 'mid',
					color: 'accent',
					shapes: [ 'circle', 'bar' ],
					edge: 'crisp',
					alpha: [ 1, 1 ],
					align: 'plan',
				},
			],
			developing: [
				{
					kind: 'line',
					w: 2,
					size: 'mid',
					color: 'dark',
					width: [ 0.0015, 0.003 ],
					align: 'plan',
				},
			],
			finishing: [
				{
					kind: 'shape',
					w: 1,
					size: 'accent',
					color: 'dark',
					shapes: [ 'circle' ],
					edge: 'crisp',
					alpha: [ 1, 1 ],
				},
			],
		},
		phases: PH,
		finish: { paper: 0.1, vignette: 0.02 },
	},
	{
		id: 'opart',
		label: 'Op Art',
		blurb: 'Black lines that bend the eye, drawn one after another.',
		palette: 'mono',
		paletteStrict: true,
		ground: { paper: 'paper', tone: 'white', grain: 0.08 },
		plan: {
			archetypes: { vortex: 3, field: 3, single: 1 },
			coverage: [ 0.6, 1 ],
			valueKeys: [ 'high' ],
		},
		tempo: { rate: 1.2, painters: [ 2, 4 ], duration: [ 0.3, 0.9 ] },
		hand: { tremor: 0.02, haste: 0.4 },
		vocab: {
			opening: [
				{
					kind: 'opline',
					w: 4,
					color: 'dark',
					width: [ 0.004, 0.012 ],
				},
			],
			building: [
				{
					kind: 'opline',
					w: 4,
					color: 'dark',
					width: [ 0.004, 0.012 ],
				},
			],
			developing: [
				{ kind: 'opline', w: 4, color: 'dark', width: [ 0.003, 0.01 ] },
				{
					kind: 'shape',
					w: 0.5,
					size: 'mid',
					color: 'accent',
					shapes: [ 'circle', 'rect' ],
					edge: 'crisp',
					alpha: [ 1, 1 ],
				},
			],
			finishing: [
				{
					kind: 'opline',
					w: 2,
					color: 'dark',
					width: [ 0.003, 0.008 ],
				},
			],
		},
		phases: PH,
		finish: { paper: 0.06, vignette: 0.02 },
	},
	{
		id: 'sumi',
		label: 'Ink wash',
		blurb: 'A few decisive strokes of black ink, and the paper left to breathe.',
		palette: 'ink',
		paletteStrict: true,
		ground: { paper: 'paper', tone: 'palette-light', grain: 0.4 },
		plan: {
			archetypes: {
				single: 3,
				duet: 2,
				horizon: 2,
				diagonal: 1,
				cascade: 1,
			},
			coverage: [ 0.12, 0.4 ],
			valueKeys: [ 'high' ],
		},
		tempo: { rate: 0.3, painters: [ 1, 3 ], duration: [ 0.5, 1.4 ] },
		hand: { tremor: 0.3, haste: 0.7, overshoot: 0.7, hesitate: 0.5 },
		vocab: {
			opening: [
				{
					kind: 'brush',
					w: 4,
					size: 'big',
					color: 'dark',
					tips: INK,
					style: 'ink',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.8, 1 ],
					flow: [ 0.5, 1 ],
					gestures: [ 'arc', 'slash', 'hook', 'scurve' ],
					taper: 4,
				},
				{
					kind: 'brush',
					w: 1.5,
					size: 'big',
					color: 'shadow',
					tips: WASH,
					style: 'watercolor',
					wet: true,
					ratio: [ 1.2, 1.9 ],
					elong: [ 0.6, 1 ],
					opacity: [ 0.15, 0.35 ],
					flow: [ 0.9, 1 ],
					gestures: [ 'blob', 'arc' ],
					taper: 1,
				},
			],
			building: [
				{
					kind: 'brush',
					w: 3,
					size: 'mid',
					color: 'dark',
					tips: INK,
					style: 'ink',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.7, 1 ],
					flow: [ 0.4, 1 ],
					gestures: [ 'hook', 'slash', 'arc' ],
					taper: 4,
				},
				{
					kind: 'brush',
					w: 1,
					size: 'mid',
					color: 'shadow',
					tips: WASH,
					style: 'watercolor',
					wet: true,
					ratio: [ 1.2, 1.9 ],
					elong: [ 0.6, 1 ],
					opacity: [ 0.1, 0.25 ],
					gestures: [ 'blob' ],
					taper: 1,
				},
				{
					kind: 'dots',
					w: 1,
					size: 'small',
					color: 'dark',
					tip: 'sumi',
					n: [ 4, 12 ],
					dot: [ 0.01, 0.03 ],
					alpha: [ 0.7, 1 ],
				},
			],
			developing: [
				{
					kind: 'brush',
					w: 2,
					size: 'small',
					color: 'dark',
					tips: INK,
					style: 'ink',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.6, 0.95 ],
					flow: [ 0.3, 0.8 ],
					gestures: [ 'hook', 'slash' ],
					taper: 4,
				},
			],
			finishing: [
				{ kind: 'seal', w: 3, color: 'accent' },
				{
					kind: 'brush',
					w: 1,
					size: 'accent',
					color: 'dark',
					tips: [ 'ink-nib' ],
					style: 'ink',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.9, 1 ],
					gestures: [ 'slash' ],
					taper: 3,
				},
			],
		},
		phases: PH,
		finish: { paper: 0.22, vignette: 0.05 },
	},
	{
		id: 'informel',
		label: 'Art Informel',
		blurb: 'Stains, crusts and scratches; the matter is the subject.',
		palette: 'muted',
		ground: {
			paper: 'panel',
			tone: 'palette-light',
			grain: 0.55,
			wash: true,
		},
		plan: {
			archetypes: {
				field: 3,
				cluster: 2,
				mass: 2,
				diagonal: 1,
				horizon: 1,
				single: 0.5,
			},
			coverage: [ 0.6, 0.95 ],
			valueKeys: [ 'mid', 'low' ],
		},
		tempo: { rate: 0.7, painters: [ 3, 7 ], duration: [ 0.4, 1.4 ] },
		hand: { tremor: 0.6, haste: 0.5, overshoot: 0.3, hesitate: 0.4 },
		vocab: {
			opening: [
				{
					kind: 'brush',
					w: 3,
					size: 'big',
					color: 'local',
					tips: WASH,
					style: 'watercolor',
					wet: true,
					ratio: [ 3.7, 6.5 ],
					opacity: [ 0.35, 0.6 ],
					flow: [ 0.8, 1 ],
					gestures: [ 'blob', 'arc', 'zigzag' ],
					taper: 1,
				},
				{
					kind: 'brush',
					w: 1,
					size: 'big',
					color: 'local',
					tips: CHARCOAL,
					style: 'charcoal',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.6, 0.9 ],
					gestures: [ 'blob', 'arc', 'zigzag' ],
				},
			],
			building: [
				{
					kind: 'brush',
					w: 3,
					size: 'mid',
					color: 'any',
					tips: CHARCOAL,
					style: 'charcoal',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.7, 1 ],
					colorVar: 0.08,
					gestures: [ 'blob', 'zigzag', 'scurve', 'arc' ],
				},
				{
					kind: 'brush',
					w: 2,
					size: 'mid',
					color: 'shadow',
					tips: WASH,
					style: 'watercolor',
					wet: true,
					ratio: [ 3.7, 6.5 ],
					opacity: [ 0.3, 0.5 ],
					gestures: [ 'blob', 'arc' ],
					taper: 1,
				},
				{ kind: 'scrape', w: 1, size: 'mid' },
			],
			developing: [
				{
					kind: 'line',
					w: 3,
					size: 'mid',
					color: 'light',
					width: [ 0.001, 0.003 ],
					wobble: 0.8,
				},
				{ kind: 'drip', w: 1, color: 'dark' },
				{ kind: 'splatter', w: 1, size: 'small', color: 'dark' },
				{
					kind: 'brush',
					w: 2,
					size: 'small',
					color: 'dark',
					tips: CHARCOAL,
					style: 'charcoal',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.8, 1 ],
					gestures: [ 'zigzag', 'slash' ],
				},
			],
			finishing: [
				{
					kind: 'brush',
					w: 2,
					size: 'accent',
					color: 'accent',
					tips: OIL,
					style: 'oil',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.95, 1 ],
					gestures: [ 'slash', 'blob' ],
				},
				{
					kind: 'line',
					w: 2,
					size: 'small',
					color: 'light',
					width: [ 0.001, 0.002 ],
					wobble: 1,
				},
			],
		},
		phases: PH,
		finish: { paper: 0.28, vignette: 0.16 },
	},
	{
		id: 'biomorphic',
		label: 'Biomorphic',
		blurb: 'Playful organisms, black threads and stars on a tinted ground.',
		palette: 'vivid',
		ground: { paper: 'paper', tone: 'tinted', grain: 0.3, wash: true },
		plan: {
			archetypes: { field: 3, duet: 2, cluster: 2, mass: 1, single: 1 },
			coverage: [ 0.25, 0.5 ],
			valueKeys: [ 'high', 'mid' ],
		},
		tempo: { rate: 0.6, painters: [ 3, 6 ], duration: [ 0.4, 1.2 ] },
		hand: { tremor: 0.25, haste: 0.4, overshoot: 0.1 },
		vocab: {
			opening: [
				{
					kind: 'blob',
					w: 4,
					size: 'mid',
					color: 'any',
					alpha: [ 0.95, 1 ],
				},
				{
					kind: 'blob',
					w: 2,
					size: 'big',
					color: 'dark',
					alpha: [ 0.95, 1 ],
				},
			],
			building: [
				{
					kind: 'blob',
					w: 3,
					size: 'small',
					color: 'any',
					alpha: [ 0.95, 1 ],
				},
				{
					kind: 'thread',
					w: 3,
					color: 'dark',
					width: [ 0.002, 0.004 ],
				},
				{ kind: 'star', w: 1, color: 'dark' },
			],
			developing: [
				{
					kind: 'thread',
					w: 3,
					color: 'dark',
					width: [ 0.0015, 0.0035 ],
				},
				{ kind: 'star', w: 2, color: 'dark' },
				{
					kind: 'shape',
					w: 2,
					size: 'accent',
					color: 'any',
					shapes: [ 'circle' ],
					edge: 'crisp',
					alpha: [ 1, 1 ],
				},
				{ kind: 'eye', w: 1, color: 'dark' },
			],
			finishing: [
				{ kind: 'star', w: 2, color: 'dark' },
				{
					kind: 'shape',
					w: 1,
					size: 'accent',
					color: 'accent',
					shapes: [ 'circle' ],
					edge: 'crisp',
					alpha: [ 1, 1 ],
				},
			],
		},
		phases: PH,
		finish: { paper: 0.14, vignette: 0.06 },
	},
	{
		id: 'collage',
		label: 'Collage',
		blurb: 'Torn paper, printed matter and a red circle, pasted where they landed.',
		palette: 'muted',
		ground: { paper: 'kraft', tone: 'palette-light', grain: 0.6 },
		plan: {
			archetypes: {
				cluster: 3,
				diagonal: 2,
				frame: 2,
				mass: 2,
				duet: 1,
				single: 0.5,
				grid: 0.5,
			},
			coverage: [ 0.4, 0.8 ],
			valueKeys: [ 'high', 'mid' ],
		},
		tempo: { rate: 0.55, painters: [ 2, 6 ], duration: [ 0.5, 1.4 ] },
		hand: { tremor: 0.1, haste: 0.3 },
		vocab: {
			opening: [
				{
					kind: 'piece',
					w: 3,
					size: 'big',
					color: 'local',
					edge: 'torn',
					treatments: [ 'none', 'posterize', 'duotone' ],
					alpha: [ 0.9, 1 ],
					shadow: 0.6,
				},
				{
					kind: 'cut',
					w: 4,
					size: 'big',
					color: 'light',
					prints: [ 'text', 'none', 'stripes' ],
					paper: 'kraft',
				},
			],
			building: [
				{
					kind: 'piece',
					w: 3,
					size: 'mid',
					color: 'local',
					edge: 'torn',
					treatments: [ 'none', 'posterize', 'duotone', 'halftone' ],
					alpha: [ 0.9, 1 ],
					shadow: 0.6,
				},
				{
					kind: 'cut',
					w: 4,
					size: 'mid',
					color: 'any',
					prints: [ 'text', 'halftone', 'none', 'none' ],
					paper: 'paper',
				},
				{
					kind: 'shape',
					w: 1.5,
					size: 'mid',
					color: 'dark',
					shapes: [ 'bar', 'rect' ],
					edge: 'print',
					alpha: [ 0.9, 1 ],
					blend: 'multiply',
				},
			],
			developing: [
				{
					kind: 'piece',
					w: 2,
					size: 'small',
					color: 'local',
					treatments: [ 'halftone', 'threshold', 'none' ],
					alpha: [ 0.9, 1 ],
					shadow: 0.5,
				},
				{
					kind: 'cut',
					w: 3,
					size: 'small',
					color: 'any',
					prints: [ 'halftone', 'text', 'none' ],
					paper: 'paper',
				},
				{
					kind: 'shape',
					w: 2,
					size: 'small',
					color: 'accent',
					shapes: [ 'circle', 'bar' ],
					edge: 'print',
					alpha: [ 0.9, 1 ],
					blend: 'multiply',
				},
				{
					kind: 'brush',
					w: 1,
					size: 'mid',
					color: 'dark',
					tips: INK,
					style: 'ink',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.9, 1 ],
					gestures: [ 'slash', 'scurve' ],
					taper: 2,
				},
			],
			finishing: [
				{
					kind: 'shape',
					w: 3,
					size: 'accent',
					color: 'accent',
					shapes: [ 'circle' ],
					edge: 'print',
					alpha: [ 0.95, 1 ],
					blend: 'multiply',
				},
				{
					kind: 'hatch',
					w: 1,
					size: 'small',
					color: 'dark',
					alpha: [ 0.6, 0.9 ],
				},
			],
		},
		phases: PH,
		finish: { paper: 0.25, vignette: 0.1 },
	},
	{
		id: 'futurism',
		label: 'Futurism',
		blurb: 'Lines of force, forms repeated as they move, speed made visible.',
		palette: 'vivid',
		ground: { paper: 'canvas', tone: 'mid', grain: 0.3, wash: true },
		plan: {
			archetypes: {
				vortex: 3,
				diagonal: 3,
				cascade: 1,
				mass: 1,
				field: 1,
			},
			coverage: [ 0.55, 0.9 ],
			valueKeys: [ 'mid', 'low' ],
		},
		tempo: { rate: 0.9, painters: [ 3, 7 ], duration: [ 0.3, 1 ] },
		hand: { tremor: 0.2, haste: 0.8, overshoot: 0.5 },
		vocab: {
			opening: [
				{ kind: 'ray', w: 4, color: 'local', alpha: [ 0.6, 0.9 ] },
				{
					kind: 'shape',
					w: 1.5,
					size: 'big',
					color: 'local',
					shapes: [ 'wedge', 'tri' ],
					edge: 'crisp',
					alpha: [ 0.8, 0.95 ],
					align: 'plan',
				},
			],
			building: [
				{
					kind: 'piece',
					w: 2,
					size: 'mid',
					color: 'local',
					edge: 'cut',
					place: 'source',
					treatments: [ 'edges', 'posterize', 'glitch' ],
					alpha: [ 0.9, 1 ],
					shadow: 0.15,
				},
				{
					kind: 'echoes',
					w: 4,
					size: 'mid',
					color: 'any',
					shapes: [ 'wedge', 'tri', 'bar', 'circle' ],
					alpha: [ 0.7, 0.9 ],
				},
				{
					kind: 'brush',
					w: 2,
					size: 'big',
					color: 'light',
					tips: ACRYL,
					style: 'acrylic',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.8, 1 ],
					gestures: [ 'slash' ],
					along: 'plan',
					taper: 3,
				},
			],
			developing: [
				{
					kind: 'echoes',
					w: 3,
					size: 'small',
					color: 'any',
					shapes: [ 'wedge', 'bar' ],
					alpha: [ 0.7, 0.9 ],
				},
				{
					kind: 'brush',
					w: 2,
					size: 'mid',
					color: 'dark',
					tips: ACRYL,
					style: 'acrylic',
					wet: true,
					ratio: [ 2, 3.6 ],
					elong: [ 0.7, 1.3 ],
					opacity: [ 0.9, 1 ],
					gestures: [ 'slash', 'zigzag' ],
					taper: 2,
				},
			],
			finishing: [
				{ kind: 'ray', w: 3, color: 'light', alpha: [ 0.7, 1 ] },
				{
					kind: 'shape',
					w: 1,
					size: 'accent',
					color: 'accent',
					shapes: [ 'circle', 'wedge' ],
					edge: 'crisp',
					alpha: [ 1, 1 ],
				},
			],
		},
		phases: PH,
		finish: { paper: 0.12, vignette: 0.14 },
	},
	{
		id: 'postimpressionism',
		label: 'Post-Impressionism',
		blurb: 'Thick directional strokes that swirl around every form, color as feeling.',
		palette: 'vivid',
		ground: { paper: 'canvas', tone: 'tinted', grain: 0.3, wash: true },
		plan: {
			archetypes: {
				vortex: 3,
				horizon: 2,
				mass: 2,
				cascade: 1,
				field: 1,
			},
			coverage: [ 0.85, 1 ],
			valueKeys: [ 'mid', 'high' ],
		},
		tempo: { rate: 0.8, painters: [ 4, 9 ], duration: [ 0.5, 1.1 ] },
		hand: { tremor: 0.2, haste: 0.6, overshoot: 0.1 },
		vocab: {
			opening: [
				{
					kind: 'blockin',
					w: 5,
					size: 'mid',
					color: 'local',
					tips: OIL,
					style: 'oil',
					wet: true,
					ratio: [ 3, 5 ],
					opacity: [ 0.6, 0.85 ],
					flow: [ 0.85, 1 ],
					colorVar: 0.1,
					taper: 2,
					rows: [ 4, 7 ],
				},
				{
					kind: 'brush',
					w: 1,
					size: 'big',
					color: 'local',
					tips: OIL,
					style: 'oil',
					wet: true,
					ratio: [ 3, 5 ],
					count: [ 2, 4 ],
					opacity: [ 0.9, 1 ],
					flow: [ 0.85, 1 ],
					colorVar: 0.1,
					gestures: [ 'scurve', 'hook', 'arc' ],
					taper: 2,
				},
			],
			building: [
				{
					kind: 'brush',
					w: 5,
					size: 'mid',
					color: 'broken',
					tips: OIL,
					style: 'oil',
					wet: true,
					ratio: [ 3, 5 ],
					count: [ 3, 6 ],
					opacity: [ 0.9, 1 ],
					flow: [ 0.85, 1 ],
					colorVar: 0.12,
					gestures: [ 'scurve', 'hook', 'arc', 'comma' ],
					taper: 2,
					along: 'mass',
				},
				{
					kind: 'brush',
					w: 2,
					size: 'small',
					color: 'complement',
					tips: OIL,
					style: 'oil',
					wet: true,
					ratio: [ 3, 4.5 ],
					count: [ 3, 5 ],
					opacity: [ 0.85, 1 ],
					colorVar: 0.1,
					gestures: [ 'comma', 'hook' ],
					taper: 2,
				},
			],
			developing: [
				{
					kind: 'brush',
					w: 4,
					size: 'small',
					color: 'broken',
					tips: OIL,
					style: 'oil',
					wet: true,
					ratio: [ 3, 4.5 ],
					count: [ 4, 8 ],
					opacity: [ 0.9, 1 ],
					colorVar: 0.14,
					gestures: [ 'comma', 'scurve', 'hook' ],
					taper: 2,
					along: 'mass',
				},
				{
					kind: 'brush',
					w: 1.5,
					size: 'small',
					color: 'dark',
					tips: OIL,
					style: 'oil',
					ratio: [ 3, 5 ],
					count: [ 1, 2 ],
					opacity: [ 0.8, 0.95 ],
					gestures: [ 'arc', 'scurve' ],
					taper: 2,
				},
			],
			finishing: [
				{
					kind: 'brush',
					w: 3,
					size: 'accent',
					color: 'lit',
					tips: OIL,
					style: 'oil',
					wet: true,
					ratio: [ 2.5, 4 ],
					count: [ 2, 5 ],
					opacity: [ 0.95, 1 ],
					colorVar: 0.1,
					gestures: [ 'comma', 'hook' ],
					taper: 2,
				},
			],
		},
		phases: PH,
		span: 140,
		finish: { paper: 0.12, vignette: 0.1 },
	},
	{
		id: 'orphism',
		label: 'Orphism',
		blurb: 'Discs of pure color in concentric rings, light turning into rhythm.',
		palette: 'luminous',
		ground: { paper: 'canvas', tone: 'light', grain: 0.15 },
		plan: {
			archetypes: { vortex: 3, duet: 2, cluster: 2, field: 1, single: 1 },
			coverage: [ 0.6, 0.95 ],
			valueKeys: [ 'high', 'mid' ],
		},
		tempo: { rate: 0.45, painters: [ 3, 6 ], duration: [ 0.6, 1.4 ] },
		hand: { tremor: 0.05, haste: 0.3 },
		vocab: {
			opening: [
				{
					kind: 'orbit',
					w: 4,
					size: 'big',
					color: 'local',
					rings: [ 4, 7 ],
					halves: 0.6,
					alpha: [ 0.85, 0.95 ],
					blend: 'multiply',
				},
			],
			building: [
				{
					kind: 'orbit',
					w: 4,
					size: 'mid',
					color: 'any',
					rings: [ 3, 6 ],
					halves: 0.5,
					alpha: [ 0.85, 0.95 ],
					blend: 'multiply',
				},
				{
					kind: 'shape',
					w: 2,
					size: 'mid',
					color: 'secondary',
					shapes: [ 'wedge', 'circle' ],
					edge: 'crisp',
					alpha: [ 0.7, 0.9 ],
					blend: 'multiply',
				},
			],
			developing: [
				{
					kind: 'orbit',
					w: 3,
					size: 'small',
					color: 'accent',
					rings: [ 3, 5 ],
					halves: 0.5,
					alpha: [ 0.9, 1 ],
					blend: 'multiply',
				},
				{
					kind: 'shape',
					w: 2,
					size: 'small',
					color: 'any',
					shapes: [ 'wedge' ],
					edge: 'crisp',
					alpha: [ 0.7, 0.9 ],
					blend: 'multiply',
				},
			],
			finishing: [
				{
					kind: 'orbit',
					w: 2,
					size: 'accent',
					color: 'light',
					rings: [ 2, 4 ],
					halves: 0.3,
					alpha: [ 0.9, 1 ],
				},
			],
		},
		phases: PH,
		finish: { paper: 0.1, vignette: 0.05 },
	},
	{
		id: 'popart',
		label: 'Pop Art',
		blurb: 'Flat color, a black keyline, a screen of dots - printed, not painted.',
		palette: 'primaries',
		ground: { paper: 'paper', tone: 'white', grain: 0.1 },
		plan: {
			archetypes: { mass: 3, frame: 2, grid: 2, duet: 1, single: 1 },
			coverage: [ 0.6, 0.9 ],
			valueKeys: [ 'high' ],
		},
		tempo: { rate: 0.5, painters: [ 3, 6 ], duration: [ 0.5, 1.2 ] },
		hand: { tremor: 0.05, haste: 0.4 },
		vocab: {
			opening: [
				{
					kind: 'piece',
					w: 3,
					size: 'big',
					color: 'local',
					edge: 'cut',
					place: 'source',
					treatments: [ 'halftone', 'posterize', 'duotone' ],
					alpha: [ 0.95, 1 ],
					shadow: 0.2,
				},
				{
					kind: 'shape',
					w: 4,
					size: 'big',
					color: 'local',
					shapes: [ 'rect', 'circle', 'poly' ],
					edge: 'print',
					alpha: [ 0.95, 1 ],
					align: 'plan',
				},
			],
			building: [
				{
					kind: 'piece',
					w: 2,
					size: 'mid',
					color: 'local',
					edge: 'cut',
					treatments: [ 'halftone', 'duotone' ],
					alpha: [ 0.95, 1 ],
					shadow: 0.2,
				},
				{
					kind: 'halftone',
					w: 4,
					size: 'mid',
					color: 'secondary',
					pitch: [ 0.012, 0.022 ],
					minR: 0.1,
					maxR: 0.55,
					alpha: [ 0.9, 1 ],
					blend: 'multiply',
				},
				{
					kind: 'shape',
					w: 3,
					size: 'mid',
					color: 'any',
					shapes: [ 'circle', 'bar', 'poly' ],
					edge: 'print',
					alpha: [ 0.95, 1 ],
				},
				{
					kind: 'contour',
					w: 2,
					size: 'mid',
					color: 'dark',
					width: [ 0.006, 0.012 ],
				},
			],
			developing: [
				{
					kind: 'halftone',
					w: 3,
					size: 'small',
					color: 'accent',
					pitch: [ 0.01, 0.018 ],
					minR: 0.15,
					maxR: 0.5,
					alpha: [ 0.9, 1 ],
					blend: 'multiply',
				},
				{
					kind: 'contour',
					w: 3,
					size: 'small',
					color: 'dark',
					width: [ 0.005, 0.01 ],
				},
				{ kind: 'star', w: 0.6, size: 'small', color: 'accent' },
			],
			finishing: [
				{
					kind: 'contour',
					w: 2,
					size: 'accent',
					color: 'dark',
					width: [ 0.005, 0.009 ],
				},
				{
					kind: 'shape',
					w: 1,
					size: 'accent',
					color: 'light',
					shapes: [ 'circle' ],
					edge: 'crisp',
					alpha: [ 1, 1 ],
				},
			],
		},
		phases: PH,
		finish: { paper: 0.06, vignette: 0 },
	},
	{
		id: 'streetart',
		label: 'Street Art',
		blurb: 'Spray and drip on a dark wall, a stencil, a quick tag in ink.',
		palette: 'vivid',
		ground: { paper: 'canvas', tone: 'palette-dark', grain: 0.5 },
		plan: {
			archetypes: {
				diagonal: 3,
				cluster: 2,
				mass: 2,
				cascade: 1,
				field: 1,
			},
			coverage: [ 0.5, 0.9 ],
			valueKeys: [ 'low', 'mid' ],
		},
		tempo: { rate: 0.8, painters: [ 3, 7 ], duration: [ 0.3, 0.9 ] },
		hand: { tremor: 0.3, haste: 0.8, overshoot: 0.2 },
		vocab: {
			opening: [
				{
					kind: 'spray',
					w: 4,
					size: 'big',
					color: 'local',
					width: [ 0.05, 0.1 ],
					n: [ 400, 700 ],
					dot: [ 0.004, 0.007 ],
					alpha: [ 0.7, 0.9 ],
				},
				{
					kind: 'shape',
					w: 2,
					size: 'big',
					color: 'light',
					shapes: [ 'rect', 'poly' ],
					edge: 'ragged',
					alpha: [ 0.85, 1 ],
				},
			],
			building: [
				{
					kind: 'piece',
					w: 2,
					size: 'mid',
					color: 'local',
					edge: 'torn',
					treatments: [ 'threshold', 'posterize', 'glitch' ],
					alpha: [ 0.85, 1 ],
					shadow: 0.3,
				},
				{
					kind: 'spray',
					w: 4,
					size: 'mid',
					color: 'any',
					width: [ 0.03, 0.07 ],
					n: [ 250, 500 ],
					dot: [ 0.003, 0.006 ],
					alpha: [ 0.75, 0.95 ],
				},
				{
					kind: 'shape',
					w: 2,
					size: 'mid',
					color: 'accent',
					shapes: [ 'poly', 'circle', 'bar' ],
					edge: 'print',
					alpha: [ 0.9, 1 ],
				},
				{ kind: 'drip', w: 2, size: 'small', color: 'any' },
				{
					kind: 'brush',
					w: 2,
					size: 'mid',
					color: 'dark',
					tips: INK,
					style: 'ink',
					ratio: [ 6, 10 ],
					count: [ 1, 3 ],
					opacity: [ 0.9, 1 ],
					gestures: [ 'zigzag', 'scurve', 'slash' ],
					taper: 1,
				},
			],
			developing: [
				{
					kind: 'piece',
					w: 1.5,
					size: 'small',
					color: 'local',
					edge: 'torn',
					treatments: [ 'threshold', 'glitch' ],
					alpha: [ 0.85, 1 ],
					shadow: 0.3,
				},
				{
					kind: 'spray',
					w: 3,
					size: 'small',
					color: 'light',
					width: [ 0.02, 0.04 ],
					n: [ 150, 300 ],
					dot: [ 0.003, 0.005 ],
					alpha: [ 0.8, 1 ],
				},
				{ kind: 'drip', w: 2, size: 'small', color: 'accent' },
				{
					kind: 'brush',
					w: 2,
					size: 'small',
					color: 'light',
					tips: INK,
					style: 'ink',
					ratio: [ 6, 10 ],
					count: [ 1, 2 ],
					opacity: [ 0.9, 1 ],
					gestures: [ 'zigzag', 'hook' ],
					taper: 1,
				},
			],
			finishing: [
				{
					kind: 'spray',
					w: 2,
					size: 'accent',
					color: 'accent',
					width: [ 0.015, 0.03 ],
					n: [ 120, 220 ],
					dot: [ 0.003, 0.005 ],
					alpha: [ 0.9, 1 ],
				},
				{ kind: 'splatter', w: 1, size: 'small', color: 'light' },
			],
		},
		phases: PH,
		finish: { paper: 0.2, vignette: 0.15 },
	},
	{
		id: 'artnouveau',
		label: 'Art Nouveau',
		blurb: 'Whiplash curves, tendrils and flat pale shapes in a dark contour.',
		palette: 'muted',
		ground: { paper: 'paper', tone: 'palette-light', grain: 0.25 },
		plan: {
			archetypes: { frame: 3, vortex: 2, cascade: 2, mass: 1, duet: 1 },
			coverage: [ 0.5, 0.85 ],
			valueKeys: [ 'mid', 'high' ],
		},
		tempo: { rate: 0.5, painters: [ 3, 6 ], duration: [ 0.7, 1.6 ] },
		hand: { tremor: 0.08, haste: 0.35 },
		vocab: {
			opening: [
				{
					kind: 'shape',
					w: 3,
					size: 'big',
					color: 'local',
					shapes: [ 'poly', 'circle' ],
					edge: 'crisp',
					alpha: [ 0.8, 0.95 ],
					blend: 'multiply',
				},
				{
					kind: 'tendril',
					w: 3,
					size: 'big',
					color: 'dark',
					width: [ 0.008, 0.014 ],
					alpha: [ 0.9, 1 ],
				},
			],
			building: [
				{
					kind: 'tendril',
					w: 5,
					size: 'mid',
					color: 'dark',
					width: [ 0.005, 0.011 ],
					alpha: [ 0.9, 1 ],
				},
				{
					kind: 'shape',
					w: 3,
					size: 'mid',
					color: 'secondary',
					shapes: [ 'poly', 'circle', 'wedge' ],
					edge: 'crisp',
					alpha: [ 0.75, 0.95 ],
					blend: 'multiply',
				},
				{
					kind: 'contour',
					w: 2,
					size: 'mid',
					color: 'dark',
					width: [ 0.004, 0.008 ],
				},
			],
			developing: [
				{
					kind: 'tendril',
					w: 4,
					size: 'small',
					color: 'dark',
					width: [ 0.004, 0.008 ],
					alpha: [ 0.9, 1 ],
				},
				{
					kind: 'dots',
					w: 1.5,
					size: 'small',
					color: 'accent',
					n: [ 8, 16 ],
					dot: [ 0.008, 0.016 ],
					tip: 'round',
					alpha: [ 0.9, 1 ],
				},
				{
					kind: 'shape',
					w: 1,
					size: 'small',
					color: 'light',
					shapes: [ 'circle' ],
					edge: 'crisp',
					alpha: [ 0.8, 1 ],
				},
			],
			finishing: [
				{
					kind: 'tendril',
					w: 3,
					size: 'accent',
					color: 'accent',
					width: [ 0.003, 0.006 ],
					alpha: [ 0.9, 1 ],
				},
			],
		},
		phases: PH,
		finish: { paper: 0.12, vignette: 0.06 },
	},
	{
		id: 'mosaic',
		label: 'Mosaic',
		blurb: 'Little stones in rows that follow the form, gold among them.',
		palette: 'earth',
		ground: { paper: 'canvas', tone: 'mid', grain: 0.4 },
		plan: {
			archetypes: { mass: 3, field: 2, horizon: 1, frame: 1, single: 1 },
			coverage: [ 0.8, 1 ],
			valueKeys: [ 'mid', 'low' ],
		},
		tempo: { rate: 0.5, painters: [ 3, 6 ], duration: [ 0.8, 1.8 ] },
		hand: { tremor: 0.05, haste: 0.3 },
		vocab: {
			opening: [
				{
					kind: 'tesserae',
					w: 4,
					size: 'big',
					color: 'local',
					stone: [ 0.018, 0.026 ],
					gold: 0.04,
					colorVar: 0.07,
				},
			],
			building: [
				{
					kind: 'tesserae',
					w: 5,
					size: 'mid',
					color: 'local',
					stone: [ 0.016, 0.024 ],
					gold: 0.06,
					colorVar: 0.08,
					along: 'mass',
				},
				{
					kind: 'tesserae',
					w: 2,
					size: 'mid',
					color: 'secondary',
					stone: [ 0.016, 0.022 ],
					gold: 0.1,
					colorVar: 0.06,
				},
			],
			developing: [
				{
					kind: 'tesserae',
					w: 4,
					size: 'small',
					color: 'broken',
					stone: [ 0.014, 0.02 ],
					gold: 0.08,
					colorVar: 0.08,
				},
				{
					kind: 'tesserae',
					w: 2,
					size: 'small',
					color: 'dark',
					stone: [ 0.014, 0.02 ],
					gold: 0,
					colorVar: 0.05,
				},
			],
			finishing: [
				{
					kind: 'tesserae',
					w: 3,
					size: 'accent',
					color: 'accent',
					stone: [ 0.012, 0.018 ],
					gold: 0.3,
					colorVar: 0.05,
				},
			],
		},
		phases: PH,
		span: 130,
		finish: { paper: 0.1, vignette: 0.12 },
	},
	{
		id: 'stainedglass',
		label: 'Stained Glass',
		blurb: 'Cells of glowing color in a net of black lead.',
		palette: 'luminous',
		ground: { paper: 'paper', tone: 'dark', grain: 0.2 },
		plan: {
			archetypes: { grid: 2, mass: 3, frame: 2, duet: 1, single: 1 },
			coverage: [ 0.55, 0.85 ],
			valueKeys: [ 'mid' ],
		},
		tempo: { rate: 0.22, painters: [ 2, 4 ], duration: [ 1, 2.2 ] },
		hand: { tremor: 0.03, haste: 0.3 },
		vocab: {
			opening: [
				{
					kind: 'lead',
					w: 4,
					size: 'big',
					color: 'local',
					cells: [ 6, 10 ],
					leadW: [ 0.006, 0.009 ],
					alpha: [ 0.85, 0.95 ],
					blend: 'screen',
				},
			],
			building: [
				{
					kind: 'lead',
					w: 2,
					size: 'big',
					color: 'any',
					cells: [ 4, 8 ],
					leadW: [ 0.005, 0.008 ],
					alpha: [ 0.85, 0.95 ],
					blend: 'screen',
				},
				{
					kind: 'shape',
					w: 1,
					size: 'mid',
					color: 'accent',
					shapes: [ 'circle', 'wedge' ],
					edge: 'crisp',
					alpha: [ 0.8, 0.95 ],
					blend: 'screen',
				},
			],
			developing: [
				{
					kind: 'lead',
					w: 1.2,
					size: 'small',
					color: 'secondary',
					cells: [ 3, 6 ],
					leadW: [ 0.004, 0.007 ],
					alpha: [ 0.85, 0.95 ],
					blend: 'screen',
				},
				{
					kind: 'line',
					w: 1.5,
					size: 'mid',
					color: 'dark',
					width: [ 0.005, 0.008 ],
				},
			],
			finishing: [
				{
					kind: 'lead',
					w: 0.8,
					size: 'accent',
					color: 'light',
					cells: [ 3, 5 ],
					leadW: [ 0.004, 0.006 ],
					alpha: [ 0.9, 1 ],
					blend: 'screen',
				},
			],
		},
		phases: PH,
		finish: { paper: 0.06, vignette: 0.2 },
	},
	{
		id: 'woodcut',
		label: 'Woodcut',
		blurb: 'Black carved marks on white paper, one color allowed.',
		palette: 'ink',
		paletteStrict: true,
		ground: { paper: 'paper', tone: 'white', grain: 0.25 },
		plan: {
			archetypes: { mass: 3, single: 2, horizon: 2, duet: 1, frame: 1 },
			coverage: [ 0.45, 0.8 ],
			valueKeys: [ 'high' ],
		},
		tempo: { rate: 0.55, painters: [ 2, 5 ], duration: [ 0.5, 1.3 ] },
		hand: { tremor: 0.12, haste: 0.5 },
		vocab: {
			opening: [
				{
					kind: 'shape',
					w: 3,
					size: 'big',
					color: 'dark',
					shapes: [ 'poly', 'rect' ],
					edge: 'ragged',
					rag: 0.6,
					alpha: [ 0.95, 1 ],
				},
				{
					kind: 'hatch',
					w: 3,
					size: 'big',
					color: 'dark',
					alpha: [ 0.9, 1 ],
				},
			],
			building: [
				{
					kind: 'hatch',
					w: 5,
					size: 'mid',
					color: 'dark',
					alpha: [ 0.9, 1 ],
				},
				{
					kind: 'shape',
					w: 2,
					size: 'mid',
					color: 'dark',
					shapes: [ 'poly', 'bar' ],
					edge: 'ragged',
					rag: 0.7,
					alpha: [ 0.95, 1 ],
				},
				{
					kind: 'brush',
					w: 2,
					size: 'mid',
					color: 'dark',
					tips: INK,
					style: 'ink',
					ratio: [ 4, 7 ],
					count: [ 2, 4 ],
					opacity: [ 0.95, 1 ],
					gestures: [ 'arc', 'slash', 'hook' ],
					taper: 3,
				},
			],
			developing: [
				{
					kind: 'hatch',
					w: 4,
					size: 'small',
					color: 'dark',
					alpha: [ 0.9, 1 ],
				},
				{
					kind: 'brush',
					w: 2,
					size: 'small',
					color: 'dark',
					tips: INK,
					style: 'ink',
					ratio: [ 4, 7 ],
					count: [ 2, 4 ],
					opacity: [ 0.95, 1 ],
					gestures: [ 'comma', 'arc' ],
					taper: 3,
				},
				{
					kind: 'shape',
					w: 1,
					size: 'small',
					color: 'accent',
					shapes: [ 'poly', 'circle' ],
					edge: 'print',
					alpha: [ 0.9, 1 ],
				},
			],
			finishing: [
				{
					kind: 'brush',
					w: 2,
					size: 'accent',
					color: 'dark',
					tips: INK,
					style: 'ink',
					ratio: [ 4, 6 ],
					count: [ 1, 3 ],
					opacity: [ 1, 1 ],
					gestures: [ 'comma' ],
					taper: 3,
				},
			],
		},
		phases: PH,
		finish: { paper: 0.18, vignette: 0.03 },
	},
	{
		id: 'constructivism',
		label: 'Constructivism',
		blurb: 'Red and black bars on a diagonal, a circle, the picture as a machine.',
		palette: 'primaries',
		paletteStrict: true,
		ground: { paper: 'paper', tone: 'palette-light', grain: 0.2 },
		plan: {
			archetypes: {
				diagonal: 4,
				cascade: 2,
				duet: 1,
				grid: 1,
				single: 1,
			},
			coverage: [ 0.3, 0.65 ],
			valueKeys: [ 'high' ],
		},
		tempo: { rate: 0.4, painters: [ 2, 5 ], duration: [ 0.6, 1.5 ] },
		hand: { tremor: 0.03, haste: 0.3 },
		vocab: {
			opening: [
				{
					kind: 'shape',
					w: 4,
					size: 'big',
					color: 'accent',
					shapes: [ 'bar', 'tri' ],
					edge: 'print',
					alpha: [ 0.95, 1 ],
					blend: 'multiply',
					align: 'plan',
				},
				{
					kind: 'shape',
					w: 2,
					size: 'big',
					color: 'dark',
					shapes: [ 'bar', 'circle' ],
					edge: 'print',
					alpha: [ 0.95, 1 ],
					blend: 'multiply',
					align: 'plan',
				},
			],
			building: [
				{
					kind: 'piece',
					w: 2,
					size: 'mid',
					color: 'local',
					edge: 'cut',
					treatments: [ 'threshold', 'duotone', 'posterize' ],
					alpha: [ 0.95, 1 ],
					shadow: 0.2,
				},
				{
					kind: 'shape',
					w: 4,
					size: 'mid',
					color: 'dark',
					shapes: [ 'bar', 'wedge', 'ring' ],
					edge: 'print',
					alpha: [ 0.95, 1 ],
					blend: 'multiply',
					align: 'plan',
				},
				{
					kind: 'shape',
					w: 3,
					size: 'mid',
					color: 'accent',
					shapes: [ 'bar', 'circle', 'tri' ],
					edge: 'print',
					alpha: [ 0.95, 1 ],
					blend: 'multiply',
					align: 'plan',
				},
				{
					kind: 'line',
					w: 2,
					size: 'big',
					color: 'dark',
					width: [ 0.002, 0.005 ],
					align: 'plan',
				},
			],
			developing: [
				{
					kind: 'shape',
					w: 3,
					size: 'small',
					color: 'dark',
					shapes: [ 'bar', 'circle' ],
					edge: 'print',
					alpha: [ 0.95, 1 ],
					blend: 'multiply',
					align: 'plan',
				},
				{
					kind: 'hatch',
					w: 1.5,
					size: 'small',
					color: 'dark',
					alpha: [ 0.8, 1 ],
				},
				{
					kind: 'line',
					w: 2,
					size: 'mid',
					color: 'accent',
					width: [ 0.002, 0.004 ],
					align: 'plan',
				},
			],
			finishing: [
				{
					kind: 'shape',
					w: 2,
					size: 'accent',
					color: 'dark',
					shapes: [ 'circle', 'bar' ],
					edge: 'crisp',
					alpha: [ 1, 1 ],
				},
			],
		},
		phases: PH,
		finish: { paper: 0.12, vignette: 0.03 },
	},
	{
		id: 'ukiyoe',
		label: 'Ukiyo-e',
		blurb: 'Flat planes of color in a fine black keyline, a wave that curls.',
		palette: 'muted',
		ground: { paper: 'paper', tone: 'light', grain: 0.35 },
		plan: {
			archetypes: {
				horizon: 3,
				cascade: 2,
				diagonal: 2,
				mass: 1,
				single: 1,
			},
			coverage: [ 0.6, 0.9 ],
			valueKeys: [ 'mid', 'high' ],
		},
		tempo: { rate: 0.45, painters: [ 3, 6 ], duration: [ 0.7, 1.5 ] },
		hand: { tremor: 0.06, haste: 0.35 },
		vocab: {
			opening: [
				{
					kind: 'shape',
					w: 4,
					size: 'big',
					color: 'local',
					shapes: [ 'poly', 'rect' ],
					edge: 'print',
					alpha: [ 0.9, 1 ],
					blend: 'multiply',
					align: 'plan',
				},
				{
					kind: 'band',
					w: 1.5,
					color: 'secondary',
					alpha: [ 0.8, 0.95 ],
					soft: 0.2,
				},
			],
			building: [
				{
					kind: 'shape',
					w: 3,
					size: 'mid',
					color: 'any',
					shapes: [ 'poly', 'wedge' ],
					edge: 'print',
					alpha: [ 0.9, 1 ],
					blend: 'multiply',
				},
				{
					kind: 'tendril',
					w: 3,
					size: 'mid',
					color: 'dark',
					width: [ 0.003, 0.006 ],
					alpha: [ 0.95, 1 ],
				},
				{
					kind: 'contour',
					w: 3,
					size: 'mid',
					color: 'dark',
					width: [ 0.002, 0.004 ],
				},
			],
			developing: [
				{
					kind: 'contour',
					w: 4,
					size: 'small',
					color: 'dark',
					width: [ 0.0015, 0.003 ],
				},
				{
					kind: 'tendril',
					w: 2,
					size: 'small',
					color: 'light',
					width: [ 0.003, 0.005 ],
					alpha: [ 0.9, 1 ],
				},
				{
					kind: 'dots',
					w: 1,
					size: 'small',
					color: 'light',
					n: [ 6, 14 ],
					dot: [ 0.006, 0.012 ],
					tip: 'round',
					alpha: [ 0.9, 1 ],
				},
			],
			finishing: [
				{
					kind: 'contour',
					w: 3,
					size: 'accent',
					color: 'dark',
					width: [ 0.0015, 0.003 ],
				},
				{ kind: 'seal', w: 0.8, color: 'accent' },
			],
		},
		phases: PH,
		finish: { paper: 0.16, vignette: 0.04 },
	},
];

export const schoolById = ( id ) =>
	SCHOOLS.find( ( s ) => s.id === id ) || SCHOOLS[ 0 ];

/** Pick one vocabulary item by weight. */
export function pickVocab( items, rng, weightOf = null ) {
	if ( ! items || ! items.length ) {
		return null;
	}
	const wf = weightOf || ( ( it ) => it.w || 1 );
	const sum = items.reduce( ( a, b ) => a + wf( b ), 0 );
	if ( sum <= 0 ) {
		return items[ Math.floor( rng() * items.length ) % items.length ];
	}
	let r = rng() * sum;
	for ( const it of items ) {
		r -= wf( it );
		if ( r <= 0 ) {
			return it;
		}
	}
	return items[ items.length - 1 ];
}

/** Gesture scale (frame units) for a size class. */
export function sizeFor( cls, rng, mul = 1 ) {
	const R = {
		big: [ 0.16, 0.34 ],
		mid: [ 0.07, 0.15 ],
		small: [ 0.03, 0.07 ],
		accent: [ 0.012, 0.035 ],
	}[ cls ] || [ 0.05, 0.12 ];
	return ( R[ 0 ] + rng() * ( R[ 1 ] - R[ 0 ] ) ) * mul;
}

/** A value from a [lo, hi] range or a plain number. */
export const range = ( v, rng, dflt = 1 ) =>
	Array.isArray( v )
		? v[ 0 ] + rng() * ( v[ 1 ] - v[ 0 ] )
		: Number.isFinite( v )
		? v
		: dflt;
