// English keys; German, Spanish, French, Italian, Brazilian Portuguese, Dutch.
export const FORCE_STRINGS = {
	Ferrofluid: [
		'Ferrofluid',
		'Ferrofluido',
		'Ferrofluide',
		'Ferrofluido',
		'Ferrofluido',
		'Ferrovloeistof',
	],
	'Indicator ink': [
		'Indikatortinte',
		'Tinta indicadora',
		'Encre indicatrice',
		'Inchiostro indicatore',
		'Tinta indicadora',
		'Indicatorinkt',
	],
	Acid: [ 'Säure', 'Ácido', 'Acide', 'Acido', 'Ácido', 'Zuur' ],
	Base: [ 'Lauge', 'Base', 'Base', 'Base', 'Base', 'Base' ],
	'Heat source': [
		'Wärmequelle',
		'Fuente de calor',
		'Source de chaleur',
		'Fonte di calore',
		'Fonte de calor',
		'Warmtebron',
	],
	'Cold source': [
		'Kältequelle',
		'Fuente de frío',
		'Source de froid',
		'Fonte di freddo',
		'Fonte de frio',
		'Koudebron',
	],
	Magnet: [ 'Magnet', 'Imán', 'Aimant', 'Magnete', 'Ímã', 'Magneet' ],
	'Remove source': [
		'Quelle entfernen',
		'Eliminar fuente',
		'Supprimer la source',
		'Rimuovi fonte',
		'Remover fonte',
		'Bron verwijderen',
	],
	Sources: [ 'Quellen', 'Fuentes', 'Sources', 'Fonti', 'Fontes', 'Bronnen' ],
	'Selected source': [
		'Gewählte Quelle',
		'Fuente seleccionada',
		'Source sélectionnée',
		'Fonte selezionata',
		'Fonte selecionada',
		'Geselecteerde bron',
	],
	'New source': [
		'Neue Quelle',
		'Nueva fuente',
		'Nouvelle source',
		'Nuova fonte',
		'Nova fonte',
		'Nieuwe bron',
	],
	'Source size': [
		'Größe der Quelle',
		'Tamaño de la fuente',
		'Taille de la source',
		'Dimensione della fonte',
		'Tamanho da fonte',
		'Brongrootte',
	],
	'Source strength': [
		'Stärke der Quelle',
		'Intensidad de la fuente',
		'Intensité de la source',
		'Intensità della fonte',
		'Intensidade da fonte',
		'Bronsterkte',
	],
	'Magnet distance': [
		'Magnetabstand',
		'Distancia del imán',
		'Distance de l’aimant',
		'Distanza del magnete',
		'Distância do ímã',
		'Magneetafstand',
	],
	'Show source handles': [
		'Quellengriffe anzeigen',
		'Mostrar controles de las fuentes',
		'Afficher les poignées des sources',
		'Mostra maniglie delle fonti',
		'Mostrar alças das fontes',
		'Brongrepen tonen',
	],
	'Remove selected source': [
		'Gewählte Quelle entfernen',
		'Eliminar fuente seleccionada',
		'Supprimer la source sélectionnée',
		'Rimuovi fonte selezionata',
		'Remover fonte selecionada',
		'Geselecteerde bron verwijderen',
	],
	'Reagent concentration': [
		'Reagenzkonzentration',
		'Concentración del reactivo',
		'Concentration du réactif',
		'Concentrazione del reagente',
		'Concentração do reagente',
		'Reagensconcentratie',
	],
	'Buffer capacity': [
		'Pufferkapazität',
		'Capacidad amortiguadora',
		'Capacité tampon',
		'Capacità tampone',
		'Capacidade tampão',
		'Buffercapaciteit',
	],
	'Oil color mixing': [
		'Farbvermischung im Öl',
		'Mezcla de colores en aceite',
		'Mélange des couleurs dans l’huile',
		'Miscelazione dei colori nell’olio',
		'Mistura de cores no óleo',
		'Kleurmenging in olie',
	],
	'Ambient temperature (°C)': [
		'Umgebungstemperatur (°C)',
		'Temperatura ambiente (°C)',
		'Température ambiante (°C)',
		'Temperatura ambiente (°C)',
		'Temperatura ambiente (°C)',
		'Omgevingstemperatuur (°C)',
	],
	Acidic: [ 'Sauer', 'Ácido', 'Acide', 'Acido', 'Ácido', 'Zuur' ],
	Alkaline: [ 'Basisch', 'Básico', 'Basique', 'Basico', 'Básico', 'Basisch' ],
	Neutral: [ 'Neutral', 'Neutro', 'Neutre', 'Neutro', 'Neutro', 'Neutraal' ],
	'Click to place a source · drag its handle to move it': [
		'Klicken setzt eine Quelle · am Griff ziehen verschiebt sie',
		'Haz clic para colocar una fuente · arrastra su control para moverla',
		'Cliquez pour placer une source · faites glisser sa poignée pour la déplacer',
		'Fai clic per posizionare una fonte · trascina la maniglia per spostarla',
		'Clique para posicionar uma fonte · arraste a alça para movê-la',
		'Klik om een bron te plaatsen · versleep de greep om deze te verplaatsen',
	],
	'Click a source handle to remove it': [
		'Auf einen Quellengriff klicken, um die Quelle zu entfernen',
		'Haz clic en el control de una fuente para eliminarla',
		'Cliquez sur la poignée d’une source pour la supprimer',
		'Fai clic sulla maniglia di una fonte per rimuoverla',
		'Clique na alça de uma fonte para removê-la',
		'Klik op een brongreep om de bron te verwijderen',
	],
	'Sources stay active after release. Select a handle to adjust or move it.':
		[
			'Quellen bleiben nach dem Loslassen aktiv. Einen Griff wählen, um die Quelle anzupassen oder zu verschieben.',
			'Las fuentes siguen activas al soltar. Selecciona un control para ajustarlas o moverlas.',
			'Les sources restent actives après le relâchement. Sélectionnez une poignée pour les régler ou les déplacer.',
			'Le fonti restano attive dopo il rilascio. Seleziona una maniglia per regolarle o spostarle.',
			'As fontes permanecem ativas ao soltar. Selecione uma alça para ajustá-las ou movê-las.',
			'Bronnen blijven actief na het loslaten. Selecteer een greep om ze aan te passen of te verplaatsen.',
		],
	'Magnetic particles in an oil carrier. Mixing with plain oil dilutes the magnetic response.':
		[
			'Magnetische Partikel in einem Trägeröl. Vermischen mit gewöhnlichem Öl schwächt die magnetische Wirkung.',
			'Partículas magnéticas en un aceite portador. Mezclarlas con aceite común reduce la respuesta magnética.',
			'Particules magnétiques dans une huile porteuse. Le mélange avec une huile ordinaire réduit la réponse magnétique.',
			'Particelle magnetiche in un olio vettore. Mescolarle con olio comune riduce la risposta magnetica.',
			'Partículas magnéticas em um óleo transportador. Misturar com óleo comum reduz a resposta magnética.',
			'Magnetische deeltjes in een draagolie. Mengen met gewone olie vermindert de magnetische reactie.',
		],
	'Acid and base are clear and neutralize each other. Indicator ink reveals acidity using the palette selected under Indicator ink.':
		[
			'Säure und Base sind klar und neutralisieren sich gegenseitig. Die Indikatortinte zeigt den Säuregrad mit der unter Indikatortinte gewählten Palette.',
			'El ácido y la base son transparentes y se neutralizan entre sí. La tinta indicadora revela la acidez con la paleta elegida en Tinta indicadora.',
			'L’acide et la base sont transparents et se neutralisent. L’encre indicatrice révèle l’acidité avec la palette choisie sous Encre indicatrice.',
			'Acido e base sono trasparenti e si neutralizzano. L’inchiostro indicatore rivela l’acidità con la palette scelta in Inchiostro indicatore.',
			'O ácido e a base são transparentes e se neutralizam. A tinta indicadora revela a acidez com a paleta escolhida em Tinta indicadora.',
			'Zuur en base zijn helder en neutraliseren elkaar. Indicatorinkt toont de zuurgraad met het palet dat onder Indicatorinkt is gekozen.',
		],
	'Warmth lowers viscosity and speeds mixing and alcohol evaporation. Temperature differences also move the surface.':
		[
			'Wärme senkt die Zähigkeit und beschleunigt Vermischung und Alkoholverdunstung. Temperaturunterschiede bewegen auch die Oberfläche.',
			'El calor reduce la viscosidad y acelera la mezcla y la evaporación del alcohol. Las diferencias de temperatura también mueven la superficie.',
			'La chaleur réduit la viscosité et accélère le mélange et l’évaporation de l’alcool. Les différences de température déplacent aussi la surface.',
			'Il calore riduce la viscosità e accelera la miscelazione e l’evaporazione dell’alcol. Le differenze di temperatura muovono anche la superficie.',
			'O calor reduz a viscosidade e acelera a mistura e a evaporação do álcool. Diferenças de temperatura também movem a superfície.',
			'Warmte verlaagt de viscositeit en versnelt menging en alcoholverdamping. Temperatuurverschillen bewegen ook het oppervlak.',
		],
	'Remove a source before adding another.': [
		'Vor dem Hinzufügen einer weiteren Quelle eine vorhandene entfernen.',
		'Elimina una fuente antes de añadir otra.',
		'Supprimez une source avant d’en ajouter une autre.',
		'Rimuovi una fonte prima di aggiungerne un’altra.',
		'Remova uma fonte antes de adicionar outra.',
		'Verwijder een bron voordat je een nieuwe toevoegt.',
	],
	'Red meets yellow': [
		'Rot trifft Gelb',
		'Rojo y amarillo',
		'Rouge et jaune',
		'Rosso e giallo',
		'Vermelho e amarelo',
		'Rood ontmoet geel',
	],
	'Blue meets yellow': [
		'Blau trifft Gelb',
		'Azul y amarillo',
		'Bleu et jaune',
		'Blu e giallo',
		'Azul e amarelo',
		'Blauw ontmoet geel',
	],
	'Warm currents': [
		'Warme Strömungen',
		'Corrientes cálidas',
		'Courants chauds',
		'Correnti calde',
		'Correntes quentes',
		'Warme stromingen',
	],
	'Hot and cold': [
		'Warm und kalt',
		'Calor y frío',
		'Chaud et froid',
		'Caldo e freddo',
		'Quente e frio',
		'Warm en koud',
	],
	'Magnetic pool': [
		'Magnetisches Bad',
		'Baño magnético',
		'Bain magnétique',
		'Bagno magnetico',
		'Banho magnético',
		'Magnetisch bad',
	],
	'Two magnets': [
		'Zwei Magnete',
		'Dos imanes',
		'Deux aimants',
		'Due magneti',
		'Dois ímãs',
		'Twee magneten',
	],
	'Warm magnetism': [
		'Warmer Magnetismus',
		'Magnetismo cálido',
		'Magnétisme chaud',
		'Magnetismo caldo',
		'Magnetismo quente',
		'Warm magnetisme',
	],
	'Reaction fronts': [
		'Reaktionsfronten',
		'Frentes de reacción',
		'Fronts de réaction',
		'Fronti di reazione',
		'Frentes de reação',
		'Reactiefronten',
	],
	'Reactive swirls': [
		'Reaktive Wirbel',
		'Remolinos reactivos',
		'Tourbillons réactifs',
		'Vortici reattivi',
		'Vórtices reativos',
		'Reactieve wervels',
	],
	'Heated reactions': [
		'Erwärmte Reaktionen',
		'Reacciones calentadas',
		'Réactions chauffées',
		'Reazioni riscaldate',
		'Reações aquecidas',
		'Verwarmde reacties',
	],
};
