// English keys; de, es, fr, it, pt_BR, nl.
export const LIBRARY_STRINGS = {
	'Water-based color that spreads easily and blends with other water inks. Oil remains separate.':
		[
			'Farbe auf Wasserbasis, die sich leicht verteilt und mit anderen Wassertinten mischt. Öl bleibt getrennt.',
			'Color a base de agua que se extiende fácilmente y se mezcla con otras tintas acuosas. El aceite permanece separado.',
			'Une couleur à base d’eau qui se diffuse facilement et se mélange aux autres encres aqueuses. L’huile reste séparée.',
			'Colore a base d’acqua che si diffonde facilmente e si mescola con altri inchiostri acquosi. L’olio resta separato.',
			'Cor à base de água que se espalha facilmente e se mistura com outras tintas aquosas. O óleo permanece separado.',
			'Kleur op waterbasis die gemakkelijk uitvloeit en met andere waterinkten mengt. Olie blijft gescheiden.',
		],
	'A freely flowing oil that forms islands on water. Its pigment mixes with other oils when they meet.':
		[
			'Ein dünnflüssiges Öl, das auf Wasser Inseln bildet. Seine Farbe vermischt sich mit anderen Ölfarben, wenn sie sich berühren.',
			'Un aceite fluido que forma islas sobre el agua. Su pigmento se mezcla con el de otros aceites al entrar en contacto.',
			'Une huile fluide qui forme des îlots sur l’eau. Ses pigments se mélangent à ceux des autres huiles au contact.',
			'Un olio fluido che forma isole sull’acqua. I suoi pigmenti si mescolano con quelli degli altri oli a contatto.',
			'Um óleo fluido que forma ilhas sobre a água. Seu pigmento se mistura com o de outros óleos ao entrar em contato.',
			'Een dunne olie die eilanden op water vormt. De kleur mengt met andere olieverven zodra ze elkaar raken.',
		],
	'A viscous oil that moves slowly and holds folds longer. Heat makes it flow more easily; cold thickens it.':
		[
			'Ein zähflüssiges Öl, das langsam fließt und Falten länger hält. Wärme macht es flüssiger, Kälte macht es zäher.',
			'Un aceite viscoso que fluye lentamente y conserva los pliegues. El calor lo vuelve más fluido; el frío lo espesa.',
			'Une huile visqueuse qui s’écoule lentement et garde ses plis plus longtemps. La chaleur la fluidifie, le froid l’épaissit.',
			'Un olio viscoso che scorre lentamente e mantiene le pieghe. Il calore lo rende più fluido, il freddo lo addensa.',
			'Um óleo viscoso que flui devagar e mantém as dobras por mais tempo. O calor o torna mais fluido; o frio o engrossa.',
			'Een stroperige olie die langzaam stroomt en plooien langer vasthoudt. Warmte maakt haar vloeibaarder; kou maakt haar dikker.',
		],
	'A heavy, reflective liquid that gathers into beads. It stays separate from water and oil and sinks in deep baths.':
		[
			'Eine schwere, spiegelnde Flüssigkeit, die sich zu Tropfen zusammenzieht. Sie bleibt von Wasser und Öl getrennt und sinkt im tiefen Becken ab.',
			'Un líquido pesado y reflectante que forma gotas. No se mezcla con agua ni aceite y se hunde en baños profundos.',
			'Un liquide lourd et réfléchissant qui forme des gouttes. Il reste séparé de l’eau et de l’huile et coule dans les bains profonds.',
			'Un liquido pesante e riflettente che forma gocce. Resta separato da acqua e olio e affonda nelle vasche profonde.',
			'Um líquido pesado e reflexivo que forma gotas. Permanece separado da água e do óleo e afunda em banhos profundos.',
			'Een zware, spiegelende vloeistof die druppels vormt. Ze blijft gescheiden van water en olie en zinkt in diepe baden.',
		],
	'A volatile liquid that lowers surface tension and pushes nearby color aside. It evaporates, leaving its pigment in the water.':
		[
			'Eine flüchtige Flüssigkeit, die die Oberflächenspannung senkt und benachbarte Farbe verdrängt. Sie verdunstet, ihre Farbe bleibt im Wasser.',
			'Un líquido volátil que reduce la tensión superficial y aparta el color cercano. Se evapora y deja su pigmento en el agua.',
			'Un liquide volatil qui réduit la tension de surface et repousse la couleur voisine. Il s’évapore et laisse ses pigments dans l’eau.',
			'Un liquido volatile che riduce la tensione superficiale e sposta il colore vicino. Evapora lasciando il pigmento nell’acqua.',
			'Um líquido volátil que reduz a tensão superficial e afasta a cor próxima. Ele evapora e deixa seu pigmento na água.',
			'Een vluchtige vloeistof die de oppervlaktespanning verlaagt en nabije kleur opzijduwt. Ze verdampt en laat haar pigment in het water achter.',
		],
	'A soap-like additive that lowers surface tension and opens paths through color. In deep baths it also makes foam last longer.':
		[
			'Ein seifenähnlicher Zusatz, der die Oberflächenspannung senkt und Wege durch die Farbe öffnet. Im tiefen Becken hält er Schaum länger stabil.',
			'Un aditivo similar al jabón que reduce la tensión superficial y abre caminos entre los colores. En baños profundos prolonga la espuma.',
			'Un additif semblable au savon qui réduit la tension de surface et ouvre des chemins dans la couleur. Dans les bains profonds, il prolonge la mousse.',
			'Un additivo simile al sapone che riduce la tensione superficiale e apre percorsi nel colore. Nelle vasche profonde fa durare la schiuma più a lungo.',
			'Um aditivo parecido com sabão que reduz a tensão superficial e abre caminhos na cor. Em banhos profundos também prolonga a espuma.',
			'Een zeepachtig middel dat de oppervlaktespanning verlaagt en paden door de kleur opent. In diepe baden houdt het schuim langer in stand.',
		],
	'Oil containing magnetic particles, in any pigment color. Magnets draw it together; adding plain oil weakens its magnetic response.':
		[
			'Öl mit magnetischen Partikeln in jeder Pigmentfarbe. Magnete ziehen es zusammen; gewöhnliches Öl verdünnt es und schwächt seine magnetische Reaktion.',
			'Aceite con partículas magnéticas en cualquier color de pigmento. Los imanes lo concentran; añadir aceite normal debilita su respuesta magnética.',
			'Une huile contenant des particules magnétiques, dans la couleur de votre choix. Les aimants la rassemblent ; l’ajout d’huile ordinaire affaiblit sa réaction magnétique.',
			'Olio con particelle magnetiche, in qualsiasi colore. I magneti lo raccolgono; aggiungere olio normale ne indebolisce la risposta magnetica.',
			'Óleo com partículas magnéticas em qualquer cor de pigmento. Os ímãs o concentram; adicionar óleo comum enfraquece sua resposta magnética.',
			'Olie met magnetische deeltjes in elke pigmentkleur. Magneten trekken haar samen; gewone olie toevoegen verzwakt de magnetische reactie.',
		],
	'A water ink that changes color with acidity. Choose its acidic, neutral and alkaline colors; acid and base move the transition.':
		[
			'Eine Wassertinte, deren Farbe sich mit dem Säuregrad verändert. Wähle ihre saure, neutrale und basische Farbe; Säure und Base steuern den Farbumschlag.',
			'Una tinta acuosa que cambia de color con la acidez. Elige sus colores ácido, neutro y básico; el ácido y la base controlan la transición.',
			'Une encre aqueuse qui change de couleur selon l’acidité. Choisissez ses couleurs acide, neutre et basique ; l’acide et la base contrôlent la transition.',
			'Un inchiostro acquoso che cambia colore con l’acidità. Scegli i colori acido, neutro e basico; acido e base controllano la transizione.',
			'Uma tinta aquosa que muda de cor com a acidez. Escolha suas cores ácida, neutra e básica; o ácido e a base controlam a transição.',
			'Een waterinkt die met de zuurgraad van kleur verandert. Kies haar zure, neutrale en basische kleuren; zuur en base bepalen de overgang.',
		],
	'A clear reagent that shifts indicator ink toward its acidic color and neutralizes base. With bicarbonate in a deep bath, it releases gas bubbles.':
		[
			'Ein klarer Zusatz, der Indikatortinte in Richtung ihrer sauren Farbe verschiebt und Base neutralisiert. Mit Natronlösung entstehen im tiefen Becken Gasblasen.',
			'Un reactivo transparente que lleva la tinta indicadora hacia su color ácido y neutraliza la base. Con bicarbonato en un baño profundo libera burbujas de gas.',
			'Un réactif transparent qui fait évoluer l’encre indicatrice vers sa couleur acide et neutralise la base. Avec du bicarbonate dans un bain profond, il libère des bulles de gaz.',
			'Un reagente trasparente che porta l’inchiostro indicatore verso il suo colore acido e neutralizza la base. Con bicarbonato in una vasca profonda libera bolle di gas.',
			'Um reagente transparente que leva a tinta indicadora para sua cor ácida e neutraliza a base. Com bicarbonato em um banho profundo, libera bolhas de gás.',
			'Een helder reagens dat indicatorinkt naar haar zure kleur verschuift en base neutraliseert. Met bicarbonaat in een diep bad komen gasbellen vrij.',
		],
	'A clear alkaline reagent that shifts indicator ink toward its alkaline color. Acid neutralizes it, returning the indicator toward its neutral color.':
		[
			'Ein klarer, basischer Zusatz, der Indikatortinte in Richtung ihrer basischen Farbe verschiebt. Säure neutralisiert ihn und bringt den Indikator wieder zur neutralen Farbe.',
			'Un reactivo básico transparente que lleva la tinta indicadora hacia su color básico. El ácido lo neutraliza y devuelve el indicador hacia su color neutro.',
			'Un réactif basique transparent qui fait évoluer l’encre indicatrice vers sa couleur basique. L’acide le neutralise et ramène l’indicateur vers sa couleur neutre.',
			'Un reagente basico trasparente che porta l’inchiostro indicatore verso il suo colore basico. L’acido lo neutralizza e riporta l’indicatore verso il colore neutro.',
			'Um reagente básico transparente que leva a tinta indicadora para sua cor básica. O ácido o neutraliza e traz o indicador de volta à cor neutra.',
			'Een helder basisch reagens dat indicatorinkt naar haar basische kleur verschuift. Zuur neutraliseert het en brengt de indicator terug naar haar neutrale kleur.',
		],
	'Bicarbonate dissolved in water. Add acid to release rising gas bubbles; add surfactant to keep more foam at the surface.':
		[
			'In Wasser gelöstes Natron. Säure erzeugt aufsteigende Gasblasen; Tensid hält mehr Schaum an der Oberfläche.',
			'Bicarbonato disuelto en agua. Añade ácido para liberar burbujas ascendentes y tensioactivo para mantener más espuma en la superficie.',
			'Du bicarbonate dissous dans l’eau. Ajoutez de l’acide pour libérer des bulles montantes et du tensioactif pour garder davantage de mousse en surface.',
			'Bicarbonato sciolto in acqua. Aggiungi acido per liberare bolle che risalgono e tensioattivo per mantenere più schiuma in superficie.',
			'Bicarbonato dissolvido em água. Adicione ácido para liberar bolhas que sobem e surfactante para manter mais espuma na superfície.',
			'Bicarbonaat opgelost in water. Voeg zuur toe voor opstijgende gasbellen en een oppervlakteactieve stof om schuim langer vast te houden.',
		],
	'Water containing a dissolved crystal-forming substance. Cooling grows crystals; warming dissolves them back into the liquid.':
		[
			'Wasser mit einem gelösten, kristallbildenden Stoff. Beim Abkühlen wachsen Kristalle; Wärme löst sie wieder in der Flüssigkeit auf.',
			'Agua con una sustancia disuelta que forma cristales. El frío hace crecer los cristales y el calor los vuelve a disolver.',
			'De l’eau contenant une substance dissoute qui forme des cristaux. Le froid fait croître les cristaux ; la chaleur les redissout.',
			'Acqua con una sostanza disciolta che forma cristalli. Il freddo fa crescere i cristalli; il calore li scioglie di nuovo.',
			'Água com uma substância dissolvida que forma cristais. O frio faz os cristais crescerem; o calor os dissolve novamente.',
			'Water met een opgeloste kristalvormende stof. Afkoelen laat kristallen groeien; opwarmen lost ze weer op.',
		],
	'A liquid prepared for traveling color reactions. Add a reaction trigger to start a wave; each wave uses up some of its fuel.':
		[
			'Eine Flüssigkeit für wandernde Farbreaktionen. Ein Reaktionsstarter löst eine Welle aus; jede Welle verbraucht einen Teil des Reaktionsvorrats.',
			'Un líquido preparado para reacciones de color viajeras. Añade un activador para iniciar una onda; cada onda consume parte del reactivo disponible.',
			'Un liquide préparé pour des réactions colorées qui se propagent. Ajoutez un déclencheur pour lancer une onde ; chaque onde consomme une partie de la réserve réactive.',
			'Un liquido preparato per reazioni di colore in movimento. Aggiungi un innesco per avviare un’onda; ogni onda consuma parte della riserva reattiva.',
			'Um líquido preparado para reações de cor que se propagam. Adicione um ativador para iniciar uma onda; cada onda consome parte da reserva reativa.',
			'Een vloeistof voor voortbewegende kleurreacties. Voeg een reactiestarter toe om een golf te starten; elke golf verbruikt een deel van de reactiestof.',
		],
	'A starter for the reactive medium. A small drop launches a local color wave; it needs reactive medium to work.':
		[
			'Ein Starter für das reaktive Medium. Ein kleiner Tropfen startet eine örtliche Farbwelle; dafür muss reaktives Medium vorhanden sein.',
			'Un iniciador para el medio reactivo. Una pequeña gota lanza una onda de color local; necesita medio reactivo para funcionar.',
			'Un déclencheur pour le milieu réactif. Une petite goutte lance une onde colorée locale ; le milieu réactif doit être présent.',
			'Un innesco per il mezzo reattivo. Una piccola goccia avvia un’onda di colore locale; serve del mezzo reattivo perché funzioni.',
			'Um iniciador para o meio reativo. Uma pequena gota lança uma onda de cor local; é necessário haver meio reativo para funcionar.',
			'Een starter voor het reactieve medium. Een kleine druppel start een plaatselijke kleurgolf; daarvoor moet reactief medium aanwezig zijn.',
		],
	Perspective: [
		'Perspektive',
		'Perspectiva',
		'Perspective',
		'Prospettiva',
		'Perspectiva',
		'Perspectief',
	],
	'Side view': [
		'Seitenansicht',
		'Vista lateral',
		'Vue de côté',
		'Vista laterale',
		'Vista lateral',
		'Zijaanzicht',
	],
	'Bottom view': [
		'Unterseite',
		'Vista inferior',
		'Vue de dessous',
		'Vista dal basso',
		'Vista inferior',
		'Onderaanzicht',
	],
	'Thin and thick oil': [
		'Dünnes und zähes Öl',
		'Aceite fluido y viscoso',
		'Huile fluide et visqueuse',
		'Olio fluido e viscoso',
		'Óleo fluido e viscoso',
		'Dunne en dikke olie',
	],
	'Oil on blue water': [
		'Öl auf blauem Wasser',
		'Aceite sobre agua azul',
		'Huile sur eau bleue',
		'Olio sull’acqua blu',
		'Óleo sobre água azul',
		'Olie op blauw water',
	],
	'Quiet color blending': [
		'Sanfte Farbmischung',
		'Mezcla de color en reposo',
		'Mélange au repos',
		'Miscela di colori a riposo',
		'Mistura de cores em repouso',
		'Rustige kleurmenging',
	],
	'Warm oil, cold oil': [
		'Warmes Öl, kaltes Öl',
		'Aceite caliente, aceite frío',
		'Huile chaude, huile froide',
		'Olio caldo, olio freddo',
		'Óleo quente, óleo frio',
		'Warme olie, koude olie',
	],
	'Evaporating bloom': [
		'Verdunstende Blüte',
		'Flor que se evapora',
		'Floraison évanescente',
		'Fioritura che evapora',
		'Flor que evapora',
		'Verdampende bloem',
	],
	'Surfactant channel': [
		'Tensidkanal',
		'Canal de tensioactivo',
		'Canal de tensioactif',
		'Canale di tensioattivo',
		'Canal de surfactante',
		'Kanaal door oppervlaktespanning',
	],
	'Magnetic bridge': [
		'Magnetische Brücke',
		'Puente magnético',
		'Pont magnétique',
		'Ponte magnetico',
		'Ponte magnética',
		'Magnetische brug',
	],
	'Magnetic triangle': [
		'Magnetisches Dreieck',
		'Triángulo magnético',
		'Triangle magnétique',
		'Triangolo magnetico',
		'Triângulo magnético',
		'Magnetische driehoek',
	],
	'Diluted ferrofluid': [
		'Verdünntes Ferrofluid',
		'Ferrofluido diluido',
		'Ferrofluide dilué',
		'Ferrofluido diluito',
		'Ferrofluido diluído',
		'Verdunde ferrovloeistof',
	],
	'Metal among oil islands': [
		'Metall zwischen Ölinseln',
		'Metal entre islas de aceite',
		'Métal entre îlots d’huile',
		'Metallo tra isole d’olio',
		'Metal entre ilhas de óleo',
		'Metaal tussen olie-eilanden',
	],
	'Acid and base mosaic': [
		'Säure-Lauge-Mosaik',
		'Mosaico de ácido y base',
		'Mosaïque acide et base',
		'Mosaico di acido e base',
		'Mosaico de ácido e base',
		'Mozaïek van zuur en base',
	],
	'Buffered color fronts': [
		'Gepufferte Farbfronten',
		'Frentes de color amortiguados',
		'Fronts colorés tamponnés',
		'Fronti di colore tamponati',
		'Frentes de cor tamponadas',
		'Gebufferde kleurfronten',
	],
	'Oil mixing above water': [
		'Ölmischung über Wasser',
		'Aceite que se mezcla sobre agua',
		'Mélange d’huiles sur l’eau',
		'Oli che si mescolano sull’acqua',
		'Óleos se misturando sobre água',
		'Olie mengen boven water',
	],
	'Rising bubbles, sinking metal': [
		'Blasen steigen, Metall sinkt',
		'Burbujas que suben, metal que baja',
		'Bulles montantes, métal coulant',
		'Bolle che salgono, metallo che affonda',
		'Bolhas sobem, metal afunda',
		'Bellen stijgen, metaal zinkt',
	],
	'Meeting reaction waves': [
		'Reaktionswellen treffen sich',
		'Ondas de reacción que se encuentran',
		'Rencontre d’ondes réactives',
		'Onde di reazione che si incontrano',
		'Encontro de ondas de reação',
		'Botsende reactiegolven',
	],
	'Warm and cold crystals': [
		'Warme und kalte Kristalle',
		'Cristales calientes y fríos',
		'Cristaux chauds et froids',
		'Cristalli caldi e freddi',
		'Cristais quentes e frios',
		'Warme en koude kristallen',
	],
	'Tilted oil layer': [
		'Geneigte Ölschicht',
		'Capa de aceite inclinada',
		'Couche d’huile inclinée',
		'Strato d’olio inclinato',
		'Camada de óleo inclinada',
		'Gekantelde olielaag',
	],
	'Magnetic oil in water': [
		'Magnetisches Öl im Wasser',
		'Aceite magnético en agua',
		'Huile magnétique dans l’eau',
		'Olio magnetico nell’acqua',
		'Óleo magnético na água',
		'Magnetische olie in water',
	],
	'Stir both pools: thin oil flows readily, while thick oil holds its folds longer.':
		[
			'Rühre in beiden Pfützen: Dünnes Öl fließt leicht, zähes Öl hält seine Falten länger.',
			'Remueve ambos charcos: el aceite fluido se mueve fácilmente y el viscoso conserva los pliegues.',
			'Remuez les deux flaques : l’huile fluide s’écoule facilement, l’huile visqueuse garde ses plis plus longtemps.',
			'Mescola entrambe le pozze: l’olio fluido scorre facilmente, quello viscoso mantiene le pieghe più a lungo.',
			'Mexa nas duas poças: o óleo fluido corre facilmente, enquanto o viscoso mantém suas dobras por mais tempo.',
			'Roer in beide plassen: dunne olie stroomt gemakkelijk, terwijl dikke olie haar plooien langer vasthoudt.',
		],
	'Stir the orange oil through blue water. The colors share the bath but stay in separate liquids.':
		[
			'Rühre das orange Öl durch das blaue Wasser. Die Farben teilen sich das Becken, bleiben aber in getrennten Flüssigkeiten.',
			'Remueve el aceite naranja en el agua azul. Los colores comparten el baño, pero permanecen en líquidos separados.',
			'Remuez l’huile orange dans l’eau bleue. Les couleurs partagent le bain mais restent dans des liquides séparés.',
			'Mescola l’olio arancione nell’acqua blu. I colori condividono la vasca ma restano in liquidi separati.',
			'Mexa o óleo laranja na água azul. As cores compartilham o banho, mas ficam em líquidos separados.',
			'Roer de oranje olie door het blauwe water. De kleuren delen het bad maar blijven in gescheiden vloeistoffen.',
		],
	'Touching oil colors blend even without stirring. Stir gently to speed up the mixing.':
		[
			'Ölfarben mischen sich bei Berührung auch ohne Rühren. Sanftes Rühren beschleunigt die Mischung.',
			'Los colores de aceite se mezclan al tocarse, incluso sin remover. Remueve suavemente para acelerar la mezcla.',
			'Les couleurs à l’huile se mélangent au contact, même sans remuer. Remuez doucement pour accélérer le mélange.',
			'I colori a olio si mescolano a contatto anche senza mescolare. Mescola delicatamente per accelerare la miscela.',
			'As cores de óleo se misturam ao se tocar, mesmo sem mexer. Mexa suavemente para acelerar a mistura.',
			'Olieverven mengen bij aanraking ook zonder roeren. Roer zachtjes om het mengen te versnellen.',
		],
	'Both pools start with the same thick oil. Heat loosens one, while cold makes the other flow more slowly.':
		[
			'Beide Pfützen starten mit demselben zähen Öl. Wärme verflüssigt die eine, Kälte bremst die andere.',
			'Ambos charcos empiezan con el mismo aceite viscoso. El calor fluidifica uno y el frío ralentiza el otro.',
			'Les deux flaques contiennent la même huile visqueuse. La chaleur fluidifie l’une, le froid ralentit l’autre.',
			'Entrambe le pozze iniziano con lo stesso olio viscoso. Il calore ne fluidifica una, il freddo rallenta l’altra.',
			'As duas poças começam com o mesmo óleo viscoso. O calor fluidifica uma, enquanto o frio desacelera a outra.',
			'Beide plassen beginnen met dezelfde dikke olie. Warmte maakt de ene vloeibaarder, kou laat de andere langzamer stromen.',
		],
	'Alcohol opens the oil ring as it spreads. Its pushing effect fades as the alcohol evaporates.':
		[
			'Alkohol öffnet beim Ausbreiten den Ölring. Seine verdrängende Wirkung lässt beim Verdunsten nach.',
			'El alcohol abre el anillo de aceite al extenderse. Su efecto de empuje disminuye al evaporarse.',
			'L’alcool ouvre l’anneau d’huile en se répandant. Son effet de poussée diminue lorsqu’il s’évapore.',
			'L’alcol apre l’anello d’olio mentre si diffonde. La sua spinta diminuisce quando evapora.',
			'O álcool abre o anel de óleo ao se espalhar. Seu efeito de empurrar diminui conforme evapora.',
			'Alcohol opent de oliering terwijl hij zich verspreidt. Het duwende effect neemt af als de alcohol verdampt.',
		],
	'Add surfactant near the narrow opening. Its surface pull carries color through the gap.':
		[
			'Gib Tensid nahe der schmalen Öffnung hinzu. Der Zug an der Oberfläche transportiert Farbe durch die Lücke.',
			'Añade tensioactivo cerca de la abertura estrecha. Su arrastre superficial lleva el color por el hueco.',
			'Ajoutez du tensioactif près de l’ouverture étroite. La traction de surface entraîne la couleur dans le passage.',
			'Aggiungi tensioattivo vicino alla stretta apertura. La trazione superficiale porta il colore attraverso il varco.',
			'Adicione surfactante perto da abertura estreita. A tração na superfície leva a cor pela passagem.',
			'Voeg een oppervlakteactieve stof toe bij de smalle opening. De oppervlaktestroming voert kleur door de spleet.',
		],
	'Two nearby magnets stretch a shared ferrofluid pool. Move a magnet to reshape the bridge.':
		[
			'Zwei nahe Magnete ziehen eine gemeinsame Ferrofluid-Pfütze auseinander. Verschiebe einen Magneten, um die Brücke zu formen.',
			'Dos imanes cercanos estiran un charco de ferrofluido. Mueve un imán para cambiar la forma del puente.',
			'Deux aimants voisins étirent une flaque de ferrofluide. Déplacez un aimant pour remodeler le pont.',
			'Due magneti vicini allungano una pozza di ferrofluido. Sposta un magnete per rimodellare il ponte.',
			'Dois ímãs próximos esticam uma poça de ferrofluido. Mova um ímã para remodelar a ponte.',
			'Twee nabije magneten rekken een gedeelde plas ferrovloeistof uit. Verplaats een magneet om de brug te vervormen.',
		],
	'Three magnets compete for one pool. Move their handles to change where the ferrofluid gathers.':
		[
			'Drei Magnete ziehen an derselben Pfütze. Verschiebe ihre Griffe, um die Sammelpunkte des Ferrofluids zu verändern.',
			'Tres imanes compiten por un charco. Mueve sus controles para cambiar dónde se concentra el ferrofluido.',
			'Trois aimants attirent une même flaque. Déplacez leurs poignées pour changer les points d’accumulation du ferrofluide.',
			'Tre magneti attirano la stessa pozza. Sposta le maniglie per cambiare dove si raccoglie il ferrofluido.',
			'Três ímãs disputam uma poça. Mova suas alças para mudar onde o ferrofluido se concentra.',
			'Drie magneten trekken aan één plas. Verplaats hun handvatten om te veranderen waar de ferrovloeistof samenkomt.',
		],
	'The right pool contains plain oil as well as ferrofluid. Equal magnets reveal its weaker response.':
		[
			'Die rechte Pfütze enthält zusätzlich gewöhnliches Öl. Gleich starke Magnete zeigen ihre schwächere Reaktion.',
			'El charco derecho contiene aceite normal además de ferrofluido. Imanes iguales revelan su respuesta más débil.',
			'La flaque de droite contient aussi de l’huile ordinaire. Des aimants identiques révèlent sa réaction plus faible.',
			'La pozza a destra contiene anche olio normale. Magneti uguali mostrano la sua risposta più debole.',
			'A poça à direita contém óleo comum além de ferrofluido. Ímãs iguais revelam sua resposta mais fraca.',
			'De rechter plas bevat ook gewone olie. Even sterke magneten laten de zwakkere reactie zien.',
		],
	'Stir reflective metal through oil and water. All three liquids keep their own boundaries.':
		[
			'Rühre spiegelndes Metall durch Öl und Wasser. Alle drei Flüssigkeiten behalten ihre eigenen Grenzen.',
			'Remueve metal reflectante entre aceite y agua. Los tres líquidos conservan sus propios límites.',
			'Remuez du métal réfléchissant dans l’huile et l’eau. Les trois liquides gardent leurs propres frontières.',
			'Mescola metallo riflettente tra olio e acqua. Tutti e tre i liquidi mantengono i propri confini.',
			'Mexa metal reflexivo entre óleo e água. Os três líquidos mantêm seus próprios limites.',
			'Roer spiegelend metaal door olie en water. Alle drie de vloeistoffen behouden hun eigen grenzen.',
		],
	'Yellow acidic patches meet blue alkaline patches. Stir them together to reveal neutral green.':
		[
			'Gelbe saure Flecken treffen auf blaue alkalische Flecken. Rühre sie zusammen, bis neutrales Grün sichtbar wird.',
			'Manchas ácidas amarillas se encuentran con manchas alcalinas azules. Mézclalas para revelar el verde neutro.',
			'Des taches acides jaunes rencontrent des taches alcalines bleues. Mélangez-les pour faire apparaître le vert neutre.',
			'Macchie acide gialle incontrano macchie alcaline blu. Mescolale per rivelare il verde neutro.',
			'Manchas ácidas amarelas encontram manchas alcalinas azuis. Misture-as para revelar o verde neutro.',
			'Gele zure vlekken ontmoeten blauwe alkalische vlekken. Roer ze samen om neutraal groen zichtbaar te maken.',
		],
	'A stronger buffer softens the color change. Compare small and concentrated drops of acid or base.':
		[
			'Ein stärkerer Puffer dämpft den Farbwechsel. Vergleiche kleine und konzentrierte Tropfen Säure oder Lauge.',
			'Un tampón más fuerte suaviza el cambio de color. Compara gotas pequeñas y concentradas de ácido o base.',
			'Un tampon plus fort atténue le changement de couleur. Comparez de petites gouttes et des gouttes concentrées d’acide ou de base.',
			'Un tampone più forte attenua il cambiamento di colore. Confronta gocce piccole e concentrate di acido o base.',
			'Um tampão mais forte suaviza a mudança de cor. Compare gotas pequenas e concentradas de ácido ou base.',
			'Een sterkere buffer verzacht de kleurverandering. Vergelijk kleine en geconcentreerde druppels zuur of base.',
		],
	'Red and yellow oil mix above blue water. The water stays separate from the oil layer.':
		[
			'Rotes und gelbes Öl vermischen sich über blauem Wasser. Das Wasser bleibt von der Ölschicht getrennt.',
			'El aceite rojo y amarillo se mezcla sobre agua azul. El agua permanece separada de la capa de aceite.',
			'Les huiles rouge et jaune se mélangent au-dessus de l’eau bleue. L’eau reste séparée de la couche d’huile.',
			'L’olio rosso e giallo si mescola sopra l’acqua blu. L’acqua resta separata dallo strato d’olio.',
			'Óleos vermelho e amarelo se misturam sobre água azul. A água permanece separada da camada de óleo.',
			'Rode en gele olie mengen boven blauw water. Het water blijft gescheiden van de olielaag.',
		],
	'Acid releases bubbles in bicarbonate solution while a metal drop sinks through the bath.':
		[
			'Säure setzt in Natronlösung Blasen frei, während ein Metalltropfen durch das Becken sinkt.',
			'El ácido libera burbujas en la solución de bicarbonato mientras una gota de metal se hunde en el baño.',
			'L’acide libère des bulles dans la solution de bicarbonate pendant qu’une goutte de métal coule dans le bain.',
			'L’acido libera bolle nella soluzione di bicarbonato mentre una goccia di metallo affonda nella vasca.',
			'O ácido libera bolhas na solução de bicarbonato enquanto uma gota de metal afunda no banho.',
			'Zuur laat bellen vrijkomen in de bicarbonaatoplossing terwijl een metaaldruppel door het bad zinkt.',
		],
	'Two reaction triggers send waves toward each other. Watch their fronts meet and use up the local fuel.':
		[
			'Zwei Reaktionsstarter schicken Wellen aufeinander zu. Beobachte, wie ihre Fronten zusammentreffen und den örtlichen Reaktionsvorrat verbrauchen.',
			'Dos activadores envían ondas una hacia la otra. Observa cómo se encuentran sus frentes y consumen el reactivo local.',
			'Deux déclencheurs envoient des ondes l’une vers l’autre. Observez leurs fronts se rencontrer et consommer la réserve réactive locale.',
			'Due inneschi inviano onde l’una verso l’altra. Osserva i fronti incontrarsi e consumare la riserva reattiva locale.',
			'Dois ativadores enviam ondas uma em direção à outra. Observe as frentes se encontrarem e consumirem a reserva reativa local.',
			'Twee reactiestarters sturen golven naar elkaar toe. Kijk hoe de fronten elkaar ontmoeten en de plaatselijke reactiestof verbruiken.',
		],
	'Cool one side to grow crystals and warm the other to dissolve them. Move the sources to shift the boundary.':
		[
			'Kühle eine Seite für Kristallwachstum und erwärme die andere zum Auflösen. Verschiebe die Quellen, um die Grenze zu verlagern.',
			'Enfría un lado para formar cristales y calienta el otro para disolverlos. Mueve las fuentes para desplazar la frontera.',
			'Refroidissez un côté pour faire croître les cristaux, réchauffez l’autre pour les dissoudre. Déplacez les sources pour déplacer la frontière.',
			'Raffredda un lato per far crescere i cristalli e scalda l’altro per scioglierli. Sposta le sorgenti per muovere il confine.',
			'Resfrie um lado para crescer cristais e aqueça o outro para dissolvê-los. Mova as fontes para deslocar a fronteira.',
			'Koel één kant af om kristallen te laten groeien en verwarm de andere om ze op te lossen. Verplaats de bronnen om de grens te verschuiven.',
		],
	'Gravity pulls the liquids toward the low side of the tilted basin. Adjust the bath tilt to send them back.':
		[
			'Die Schwerkraft zieht die Flüssigkeiten zur tieferen Seite des geneigten Beckens. Ändere die Beckenneigung, um sie zurückfließen zu lassen.',
			'La gravedad lleva los líquidos al lado bajo de la cubeta inclinada. Ajusta la inclinación para que vuelvan.',
			'La gravité attire les liquides vers le côté bas du bassin incliné. Modifiez l’inclinaison pour les faire revenir.',
			'La gravità attira i liquidi verso il lato basso della vasca inclinata. Regola l’inclinazione per farli tornare indietro.',
			'A gravidade puxa os líquidos para o lado baixo da bacia inclinada. Ajuste a inclinação para fazê-los voltar.',
			'De zwaartekracht trekt de vloeistoffen naar de lage kant van het gekantelde bad. Pas de kanteling aan om ze terug te laten stromen.',
		],
	'A magnet draws the dark magnetic oil through clear water. Move the magnet and watch the oil follow.':
		[
			'Ein Magnet zieht das dunkle magnetische Öl durch klares Wasser. Verschiebe den Magneten und beobachte, wie das Öl folgt.',
			'Un imán atrae el aceite magnético oscuro a través del agua clara. Mueve el imán y observa cómo lo sigue el aceite.',
			'Un aimant attire l’huile magnétique sombre dans l’eau claire. Déplacez l’aimant et observez l’huile le suivre.',
			'Un magnete attira l’olio magnetico scuro nell’acqua limpida. Sposta il magnete e osserva l’olio seguirlo.',
			'Um ímã atrai o óleo magnético escuro pela água clara. Mova o ímã e observe o óleo seguir.',
			'Een magneet trekt de donkere magnetische olie door helder water. Verplaats de magneet en kijk hoe de olie volgt.',
		],
};
