/** English keys; de, es, fr, it, pt_BR, nl. */
export const MATERIAL_STRINGS = {
	'Silicone oil': [
		'Silikonöl',
		'Aceite de silicona',
		'Huile de silicone',
		'Olio di silicone',
		'Óleo de silicone',
		'Siliconenolie',
	],
	'Liquid wax': [
		'Flüssiges Wachs',
		'Cera líquida',
		'Cire liquide',
		'Cera liquida',
		'Cera líquida',
		'Vloeibare was',
	],
	'A silky oil with low surface tension. It spreads into smooth cells, stays separate from water and the studio oils, and changes viscosity only gently with temperature.':
		[
			'Ein glattes Öl mit geringer Oberflächenspannung. Es bildet weiche Zellen, bleibt von Wasser und den Studio-Ölen getrennt und verändert seine Zähigkeit bei Wärme nur wenig.',
			'Un aceite sedoso de baja tensión superficial. Forma celdas suaves, permanece separado del agua y los aceites del estudio y cambia poco de viscosidad con la temperatura.',
			'Une huile soyeuse à faible tension superficielle. Elle forme des cellules lisses, reste séparée de l’eau et des huiles du studio et sa viscosité varie peu avec la température.',
			'Un olio setoso a bassa tensione superficiale. Forma celle morbide, resta separato dall’acqua e dagli oli dello studio e cambia poco viscosità con la temperatura.',
			'Um óleo sedoso de baixa tensão superficial. Forma células suaves, fica separado da água e dos óleos do estúdio e muda pouco de viscosidade com a temperatura.',
			'Een zijdezachte olie met lage oppervlaktespanning. Ze vormt gladde cellen, blijft gescheiden van water en de studio-oliën en verandert weinig van stroperigheid bij warmte.',
		],
	'Warm colored wax that sets as it cools. Heat softens and melts it again; cold preserves its folds. Pour temperature and melting point control the transition.':
		[
			'Warmes, farbiges Wachs, das beim Abkühlen fest wird. Wärme macht es wieder weich und flüssig; Kälte erhält seine Falten. Gießtemperatur und Schmelzpunkt steuern den Übergang.',
			'Cera coloreada caliente que se endurece al enfriarse. El calor la ablanda y funde; el frío conserva sus pliegues. La temperatura de vertido y el punto de fusión controlan la transición.',
			'Une cire colorée chaude qui se fige en refroidissant. La chaleur la ramollit et la fait fondre ; le froid préserve ses plis. La température de coulée et le point de fusion règlent la transition.',
			'Cera colorata calda che si solidifica raffreddandosi. Il calore la ammorbidisce e la scioglie; il freddo conserva le pieghe. Temperatura di colata e punto di fusione regolano il passaggio.',
			'Cera colorida quente que endurece ao esfriar. O calor amolece e derrete a cera; o frio preserva suas dobras. A temperatura de despejo e o ponto de fusão controlam a transição.',
			'Warme gekleurde was die stolt bij afkoeling. Warmte maakt haar weer zacht en vloeibaar; kou bewaart de plooien. Giettemperatuur en smeltpunt bepalen de overgang.',
		],
	'Pour temperature (°C)': [
		'Gießtemperatur (°C)',
		'Temperatura de vertido (°C)',
		'Température de coulée (°C)',
		'Temperatura di colata (°C)',
		'Temperatura de despejo (°C)',
		'Giettemperatuur (°C)',
	],
	'Melting point (°C)': [
		'Schmelzpunkt (°C)',
		'Punto de fusión (°C)',
		'Point de fusion (°C)',
		'Punto di fusione (°C)',
		'Ponto de fusão (°C)',
		'Smeltpunt (°C)',
	],
	'Silicone cells': [
		'Silikonzellen',
		'Celdas de silicona',
		'Cellules de silicone',
		'Celle di silicone',
		'Células de silicone',
		'Siliconencellen',
	],
	'Silky color ribbons': [
		'Seidige Farbbänder',
		'Cintas de color sedosas',
		'Rubans de couleur soyeux',
		'Nastri di colore setosi',
		'Fitas de cor sedosas',
		'Zijdezachte kleurlinten',
	],
	'Melt and set': [
		'Schmelzen und Erstarren',
		'Fundir y solidificar',
		'Fondre et figer',
		'Fondere e solidificare',
		'Derreter e endurecer',
		'Smelten en stollen',
	],
	'Wax islands': [
		'Wachsinseln',
		'Islas de cera',
		'Îlots de cire',
		'Isole di cera',
		'Ilhas de cera',
		'Waseilanden',
	],
	'Silicone over water': [
		'Silikon über Wasser',
		'Silicona sobre agua',
		'Silicone sur l’eau',
		'Silicone sull’acqua',
		'Silicone sobre água',
		'Siliconen op water',
	],
	'Melting wax pools': [
		'Schmelzende Wachspools',
		'Charcos de cera fundiéndose',
		'Flaques de cire en fusion',
		'Pozze di cera in fusione',
		'Poças de cera derretendo',
		'Smeltende waspoelen',
	],
	'Silicone spreads through an oil film and opens smooth cells. Add small drops and stir gently.':
		[
			'Silikon breitet sich im Ölfilm aus und öffnet weiche Zellen. Gib kleine Tropfen hinzu und rühre vorsichtig.',
			'La silicona se extiende por una película de aceite y abre celdas suaves. Añade gotas pequeñas y remueve suavemente.',
			'Le silicone s’étale dans un film d’huile et ouvre des cellules lisses. Ajoutez de petites gouttes et remuez doucement.',
			'Il silicone si espande nel film d’olio e apre celle morbide. Aggiungi piccole gocce e mescola delicatamente.',
			'O silicone se espalha pelo filme de óleo e abre células suaves. Adicione gotas pequenas e mexa devagar.',
			'Siliconen verspreiden zich door een oliefilm en openen gladde cellen. Voeg kleine druppels toe en roer rustig.',
		],
	'Two silicone colors meet and blend while the surrounding water color stays separate. Pull a slow curve through them.':
		[
			'Zwei Silikonfarben treffen sich und vermischen sich. Die umgebende Wasserfarbe bleibt getrennt. Ziehe eine langsame Kurve hindurch.',
			'Dos colores de silicona se encuentran y mezclan mientras el color del agua circundante permanece separado. Traza una curva lenta entre ellos.',
			'Deux couleurs de silicone se rencontrent et se mélangent, tandis que la couleur de l’eau reste séparée. Tracez une courbe lente à travers elles.',
			'Due colori di silicone si incontrano e si mescolano, mentre il colore dell’acqua resta separato. Traccia una curva lenta tra i colori.',
			'Duas cores de silicone se encontram e se misturam, enquanto a cor da água ao redor fica separada. Trace uma curva lenta entre elas.',
			'Twee siliconenkleuren raken elkaar en mengen, terwijl de waterkleur eromheen apart blijft. Trek er langzaam een bocht doorheen.',
		],
	'The warm wax stays glossy and mobile; the cold wax holds its shape. Move the heat and cold sources to swap their roles.':
		[
			'Das warme Wachs bleibt glänzend und beweglich; das kalte hält seine Form. Verschiebe die Wärme- und Kältequellen, um die Rollen zu tauschen.',
			'La cera caliente sigue brillante y móvil; la fría conserva su forma. Mueve las fuentes de calor y frío para intercambiar sus papeles.',
			'La cire chaude reste brillante et mobile ; la cire froide garde sa forme. Déplacez les sources de chaleur et de froid pour inverser leurs rôles.',
			'La cera calda resta lucida e mobile; quella fredda mantiene la forma. Sposta le fonti di caldo e freddo per scambiarne i ruoli.',
			'A cera quente fica brilhante e móvel; a fria mantém a forma. Mova as fontes de calor e frio para trocar seus papéis.',
			'Warme was blijft glanzend en beweeglijk; koude was behoudt haar vorm. Verplaats warmte- en koudebronnen om de rollen om te draaien.',
		],
	'Cold wax forms pale islands among the oils. Move a heat source over an island to soften its edge and release its color.':
		[
			'Kaltes Wachs bildet helle Inseln zwischen den Ölen. Bewege eine Wärmequelle darüber, um den Rand aufzuweichen und die Farbe fließen zu lassen.',
			'La cera fría forma islas pálidas entre los aceites. Mueve una fuente de calor sobre una isla para ablandar su borde y liberar su color.',
			'La cire froide forme des îlots pâles parmi les huiles. Déplacez une source de chaleur sur un îlot pour ramollir son bord et libérer sa couleur.',
			'La cera fredda forma isole chiare tra gli oli. Sposta una fonte di calore su un’isola per ammorbidire il bordo e liberarne il colore.',
			'A cera fria forma ilhas claras entre os óleos. Mova uma fonte de calor sobre uma ilha para amolecer a borda e liberar a cor.',
			'Koude was vormt lichte eilanden tussen de oliën. Beweeg een warmtebron over een eiland om de rand zachter te maken en de kleur te laten vloeien.',
		],
	'Silicone floats above blue water as its own liquid. Stir the colors or tilt the bath to move the layers.':
		[
			'Silikon schwimmt als eigene Flüssigkeit über blauem Wasser. Rühre die Farben oder neige das Bad, um die Schichten zu bewegen.',
			'La silicona flota como un líquido separado sobre agua azul. Remueve los colores o inclina el baño para mover las capas.',
			'Le silicone flotte comme un liquide distinct sur l’eau bleue. Remuez les couleurs ou inclinez le bain pour déplacer les couches.',
			'Il silicone galleggia come liquido separato sull’acqua blu. Mescola i colori o inclina il bagno per muovere gli strati.',
			'O silicone flutua como um líquido separado sobre a água azul. Mexa as cores ou incline o banho para mover as camadas.',
			'Siliconen drijven als aparte vloeistof boven blauw water. Roer de kleuren of kantel het bad om de lagen te bewegen.',
		],
	'Two wax pools share the water. Heat keeps one soft and flowing; cooling makes the other denser in texture and slower to deform.':
		[
			'Zwei Wachspools teilen sich das Wasser. Wärme hält einen weich und fließend; Kälte macht den anderen kompakter und schwerer verformbar.',
			'Dos charcos de cera comparten el agua. El calor mantiene uno blando y fluido; el frío da al otro una textura más compacta y menos deformable.',
			'Deux flaques de cire partagent l’eau. La chaleur garde l’une souple et fluide ; le froid rend l’autre plus compacte et moins déformable.',
			'Due pozze di cera condividono l’acqua. Il calore ne mantiene una morbida e fluida; il freddo rende l’altra più compatta e meno deformabile.',
			'Duas poças de cera compartilham a água. O calor mantém uma macia e fluida; o frio torna a outra mais compacta e difícil de deformar.',
			'Twee waspoelen delen het water. Warmte houdt de ene zacht en vloeiend; kou maakt de andere compacter en moeilijker vervormbaar.',
		],
};
