// English keys; German, Spanish, French, Italian, Brazilian Portuguese, Dutch.
export const OBSTACLE_STRINGS = {
	'Obstacle shapes': [
		'Hindernisformen',
		'Formas de obstáculos',
		'Formes des obstacles',
		'Forme degli ostacoli',
		'Formas dos obstáculos',
		'Obstakelvormen',
	],
	'Obstacle mode': [
		'Hindernismodus',
		'Modo de obstáculos',
		'Mode obstacle',
		'Modalità ostacoli',
		'Modo de obstáculos',
		'Obstakelmodus',
	],
	'Place and move': [
		'Platzieren und bewegen',
		'Colocar y mover',
		'Placer et déplacer',
		'Posiziona e sposta',
		'Posicionar e mover',
		'Plaatsen en verplaatsen',
	],
	'Paint shape stamps': [
		'Formen als Pinsel malen',
		'Pintar sellos de formas',
		'Peindre avec des formes',
		'Dipingi con timbri',
		'Pintar carimbos de formas',
		'Met vormstempels schilderen',
	],
	'Selected obstacle': [
		'Ausgewähltes Hindernis',
		'Obstáculo seleccionado',
		'Obstacle sélectionné',
		'Ostacolo selezionato',
		'Obstáculo selecionado',
		'Geselecteerd obstakel',
	],
	'New obstacle': [
		'Neues Hindernis',
		'Nuevo obstáculo',
		'Nouvel obstacle',
		'Nuovo ostacolo',
		'Novo obstáculo',
		'Nieuw obstakel',
	],
	'Obstacle shape': [
		'Hindernisform',
		'Forma del obstáculo',
		'Forme de l’obstacle',
		'Forma dell’ostacolo',
		'Forma do obstáculo',
		'Obstakelvorm',
	],
	Circle: [ 'Kreis', 'Círculo', 'Cercle', 'Cerchio', 'Círculo', 'Cirkel' ],
	Heart: [ 'Herz', 'Corazón', 'Cœur', 'Cuore', 'Coração', 'Hart' ],
	Star: [ 'Stern', 'Estrella', 'Étoile', 'Stella', 'Estrela', 'Ster' ],
	Pebble: [ 'Kiesel', 'Guijarro', 'Galet', 'Ciottolo', 'Seixo', 'Kiezel' ],
	Ring: [ 'Ring', 'Anillo', 'Anneau', 'Anello', 'Anel', 'Ring' ],
	'Canvas layer': [
		'Canvas-Ebene',
		'Capa del lienzo',
		'Calque du canevas',
		'Livello della tela',
		'Camada da tela',
		'Canvaslaag',
	],
	'Reading silhouette…': [
		'Kontur wird gelesen…',
		'Leyendo silueta…',
		'Lecture de la silhouette…',
		'Lettura della sagoma…',
		'Lendo silhueta…',
		'Silhouet lezen…',
	],
	'Use layer silhouette': [
		'Ebenenkontur übernehmen',
		'Usar silueta de la capa',
		'Utiliser la silhouette du calque',
		'Usa sagoma del livello',
		'Usar silhueta da camada',
		'Laagsilhouet gebruiken',
	],
	'Obstacle size': [
		'Hindernisgröße',
		'Tamaño del obstáculo',
		'Taille de l’obstacle',
		'Dimensione dell’ostacolo',
		'Tamanho do obstáculo',
		'Obstakelgrootte',
	],
	'Obstacle rotation': [
		'Hindernis drehen',
		'Rotación del obstáculo',
		'Rotation de l’obstacle',
		'Rotazione dell’ostacolo',
		'Rotação do obstáculo',
		'Obstakelrotatie',
	],
	'Obstacle color': [
		'Hindernisfarbe',
		'Color del obstáculo',
		'Couleur de l’obstacle',
		'Colore dell’ostacolo',
		'Cor do obstáculo',
		'Obstakelkleur',
	],
	'Remove selected obstacle': [
		'Ausgewähltes Hindernis entfernen',
		'Eliminar obstáculo seleccionado',
		'Supprimer l’obstacle sélectionné',
		'Rimuovi ostacolo selezionato',
		'Remover obstáculo selecionado',
		'Geselecteerd obstakel verwijderen',
	],
	'Remove an obstacle before adding another.': [
		'Entferne zuerst ein Hindernis. Das Bad fasst bis zu 128 Formen.',
		'Elimina un obstáculo primero. El baño admite 128 formas.',
		'Supprimez d’abord un obstacle. Le bain accepte 128 formes.',
		'Rimuovi prima un ostacolo. La vasca accoglie 128 forme.',
		'Remova um obstáculo primeiro. O banho aceita 128 formas.',
		'Verwijder eerst een obstakel. Het bad ondersteunt 128 vormen.',
	],
	'Drag to stamp the selected shape. Brush size controls the stamps.': [
		'Ziehe, um die gewählte Form als Pinsel zu malen. Die Pinselgröße bestimmt die Stempelgröße.',
		'Arrastra para estampar la forma elegida. El tamaño del pincel controla los sellos.',
		'Glissez pour tamponner la forme choisie. La taille du pinceau règle les tampons.',
		'Trascina per timbrare la forma scelta. La dimensione del pennello regola i timbri.',
		'Arraste para carimbar a forma escolhida. O tamanho do pincel controla os carimbos.',
		'Sleep om de gekozen vorm te stempelen. De penseelgrootte bepaalt de stempels.',
	],
	'Click empty space to place a form. Drag a form to move it. Size, rotation and color change the selected form.':
		[
			'Klicke auf eine freie Stelle, um eine Form zu platzieren. Ziehe eine Form zum Verschieben. Größe, Drehung und Farbe ändern die ausgewählte Form.',
			'Haz clic en un espacio libre para colocar una forma. Arrástrala para moverla. Tamaño, rotación y color cambian la forma seleccionada.',
			'Cliquez dans un espace libre pour placer une forme. Glissez-la pour la déplacer. Taille, rotation et couleur modifient la forme sélectionnée.',
			'Fai clic in uno spazio libero per posizionare una forma. Trascinala per spostarla. Dimensione, rotazione e colore modificano la forma selezionata.',
			'Clique em um espaço livre para posicionar uma forma. Arraste para movê-la. Tamanho, rotação e cor alteram a forma selecionada.',
			'Klik op een lege plek om een vorm te plaatsen. Sleep een vorm om deze te verplaatsen. Grootte, rotatie en kleur wijzigen de geselecteerde vorm.',
		],
	'Select Obstacle to place or move forms. Remove obstacle deletes the form under the pointer.':
		[
			'Mit Hindernis platzierst und bewegst du Formen. Hindernis entfernen löscht die Form unter dem Zeiger.',
			'Obstáculo coloca y mueve formas. Eliminar obstáculo borra la forma bajo el cursor.',
			'Obstacle place et déplace les formes. Supprimer l’obstacle efface la forme sous le pointeur.',
			'Ostacolo posiziona e sposta le forme. Rimuovi ostacolo cancella la forma sotto il puntatore.',
			'Obstáculo posiciona e move formas. Remover obstáculo apaga a forma sob o ponteiro.',
			'Obstakel plaatst en verplaatst vormen. Obstakel verwijderen wist de vorm onder de aanwijzer.',
		],
	'Choose a canvas layer first.': [
		'Wähle zuerst eine Canvas-Ebene.',
		'Elige primero una capa del lienzo.',
		'Choisissez d’abord un calque du canevas.',
		'Scegli prima un livello della tela.',
		'Escolha primeiro uma camada da tela.',
		'Kies eerst een canvaslaag.',
	],
	'This layer has no visible silhouette.': [
		'Diese Ebene hat keine sichtbare Kontur.',
		'Esta capa no tiene silueta visible.',
		'Ce calque n’a pas de silhouette visible.',
		'Questo livello non ha una sagoma visibile.',
		'Esta camada não tem silhueta visível.',
		'Deze laag heeft geen zichtbaar silhouet.',
	],
	'This silhouette is too complex.': [
		'Diese Kontur ist zu komplex. Verwende eine einfachere Ebene.',
		'Esta silueta es demasiado compleja. Usa una capa más sencilla.',
		'Cette silhouette est trop complexe. Utilisez un calque plus simple.',
		'Questa sagoma è troppo complessa. Usa un livello più semplice.',
		'Esta silhueta é complexa demais. Use uma camada mais simples.',
		'Dit silhouet is te complex. Gebruik een eenvoudigere laag.',
	],
	'Canvas layer import is unavailable.': [
		'Die Ebenenübernahme ist hier nicht verfügbar.',
		'La importación de capas no está disponible.',
		'L’importation de calques est indisponible.',
		'L’importazione dei livelli non è disponibile.',
		'A importação de camadas não está disponível.',
		'Laagimport is hier niet beschikbaar.',
	],
	'Obstacle shape limit': [
		'Es sind höchstens 16 eigene Konturen mit insgesamt 12.000 Punkten möglich.',
		'Se admiten 16 siluetas propias con 12.000 puntos en total.',
		'16 silhouettes personnelles avec 12 000 points au total sont possibles.',
		'Sono ammesse 16 sagome personali con 12.000 punti totali.',
		'São permitidas 16 silhuetas próprias com 12.000 pontos no total.',
		'Maximaal 16 eigen silhouetten met samen 12.000 punten zijn mogelijk.',
	],
	'Obstacle covers the entire bath': [
		'Das Hindernis lässt keinen Platz für Flüssigkeit.',
		'El obstáculo no deja espacio para el líquido.',
		'L’obstacle ne laisse aucune place au liquide.',
		'L’ostacolo non lascia spazio al liquido.',
		'O obstáculo não deixa espaço para o líquido.',
		'Het obstakel laat geen ruimte voor vloeistof.',
	],
};
