import { EXTRA_TOOL_STRINGS } from './extra-tool-strings.js';
import { FEATURE_STRINGS } from './feature-strings.js';
import { TOOL_STRINGS } from './tool-strings.js';
import { OBSTACLE_STRINGS } from './obstacle-strings.js';
import { MATERIAL_STRINGS } from './material-strings.js';
import { LIBRARY_STRINGS } from './library-strings.js';
import { VOLUME_STRINGS } from './volume-strings.js';
import { FORCE_STRINGS } from './forces-strings.js';
// English keys; German, Spanish, French, Italian, Brazilian Portuguese, Dutch.
export const FLUID_STRINGS = {
	...EXTRA_TOOL_STRINGS,
	...FEATURE_STRINGS,
	...TOOL_STRINGS,
	...OBSTACLE_STRINGS,
	'Indicator colors': [
		'Indikatorfarben',
		'Colores del indicador',
		'Couleurs de l’indicateur',
		'Colori dell’indicatore',
		'Cores do indicador',
		'Indicatorkleuren',
	],
	'Indicator color': [
		'Indikatorfarbe',
		'Color del indicador',
		'Couleur de l’indicateur',
		'Colore dell’indicatore',
		'Cor do indicador',
		'Indicatorkleur',
	],
	'Reset indicator colors': [
		'Indikatorfarben zurücksetzen',
		'Restablecer colores del indicador',
		'Réinitialiser les couleurs de l’indicateur',
		'Ripristina colori dell’indicatore',
		'Redefinir cores do indicador',
		'Indicatorkleuren herstellen',
	],
	'Choose the acidic, neutral and alkaline colors. The palette applies to all indicator ink in the bath; acidity controls the transition.':
		[
			'Wähle die Farben für sauer, neutral und basisch. Die Palette gilt für die gesamte Indikatortinte im Bad; der Säuregrad steuert den Übergang.',
			'Elige los colores ácido, neutro y básico. La paleta se aplica a toda la tinta indicadora del baño; la acidez controla la transición.',
			'Choisissez les couleurs acide, neutre et basique. La palette s’applique à toute l’encre indicatrice du bain ; l’acidité contrôle la transition.',
			'Scegli i colori acido, neutro e basico. La palette si applica a tutto l’inchiostro indicatore nella vasca; l’acidità controlla la transizione.',
			'Escolha as cores ácida, neutra e básica. A paleta vale para toda a tinta indicadora no banho; a acidez controla a transição.',
			'Kies de zure, neutrale en basische kleuren. Het palet geldt voor alle indicatorinkt in het bad; de zuurgraad bepaalt de overgang.',
		],
	Fluorescence: [
		'Fluoreszenz',
		'Fluorescencia',
		'Fluorescence',
		'Fluorescenza',
		'Fluorescência',
		'Fluorescentie',
	],
	'Colored glow for all liquids in Wet surface. Choose a bright pigment and lower Light to make it stand out.':
		[
			'Farbiges Leuchten für alle Flüssigkeiten in der nassen Oberfläche. Wähle ein helles Pigment und reduziere das Licht, damit es stärker hervortritt.',
			'Brillo de color para todos los líquidos en Superficie húmeda. Elige un pigmento vivo y reduce la Luz para resaltarlo.',
			'Une lueur colorée pour tous les liquides en Surface humide. Choisissez un pigment vif et baissez la Lumière pour la faire ressortir.',
			'Un bagliore colorato per tutti i liquidi in Superficie bagnata. Scegli un pigmento brillante e riduci la Luce per farlo risaltare.',
			'Brilho colorido para todos os líquidos em Superfície molhada. Escolha um pigmento vivo e reduza a Luz para destacá-lo.',
			'Gekleurde gloed voor alle vloeistoffen in Nat oppervlak. Kies een helder pigment en verlaag Licht om de gloed te versterken.',
		],
	...MATERIAL_STRINGS,
	Edges: [ 'Ränder', 'Bordes', 'Bords', 'Bordi', 'Bordas', 'Randen' ],
	'Open edges': [
		'Offen',
		'Abiertos',
		'Ouverts',
		'Aperti',
		'Abertas',
		'Open',
	],
	'Closed edges': [
		'Geschlossen',
		'Cerrados',
		'Fermés',
		'Chiusi',
		'Fechadas',
		'Gesloten',
	],
	'Open edges let liquid flow out of the artwork. The wet surface fills the document without a basin border.':
		[
			'An offenen Rändern kann Flüssigkeit aus dem Bild fließen. Die nasse Oberfläche füllt das Dokument ohne Beckenrahmen.',
			'Los bordes abiertos dejan salir el líquido de la imagen. La superficie húmeda llena el documento sin el borde de una cubeta.',
			'Les bords ouverts laissent le liquide sortir de l’image. La surface humide remplit le document sans bord de bassin.',
			'I bordi aperti lasciano scorrere il liquido fuori dall’immagine. La superficie bagnata riempie il documento senza il bordo della vasca.',
			'Bordas abertas permitem que o líquido saia da imagem. A superfície molhada preenche o documento sem a borda de uma bacia.',
			'Open randen laten vloeistof uit het beeld stromen. Het natte oppervlak vult het document zonder een badrand.',
		],

	...LIBRARY_STRINGS,
	...FORCE_STRINGS,
	...VOLUME_STRINGS,
	'Rotate view': [
		'Ansicht drehen',
		'Girar vista',
		'Tourner la vue',
		'Ruota vista',
		'Girar visualização',
		'Weergave draaien',
	],
	View: [ 'Ansicht', 'Vista', 'Vue', 'Vista', 'Visualização', 'Weergave' ],
	'View rotation': [
		'Drehung',
		'Rotación de vista',
		'Rotation de la vue',
		'Rotazione vista',
		'Rotação da visualização',
		'Draaiing',
	],
	Zoom: [ 'Zoom', 'Zoom', 'Zoom', 'Zoom', 'Zoom', 'Zoom' ],
	'Reset view': [
		'Ansicht zurücksetzen',
		'Restablecer vista',
		'Réinitialiser la vue',
		'Ripristina vista',
		'Redefinir visualização',
		'Weergave herstellen',
	],
	'Right-drag to orbit. Scroll to zoom. Rotate view also works with left-drag or touch. The camera does not move the liquid.':
		[
			'Mit rechts ziehen zum Drehen, mit dem Mausrad zoomen. „Ansicht drehen“ funktioniert auch mit linker Maustaste oder Touch. Die Kamera bewegt die Flüssigkeit nicht.',
			'Arrastra con el botón derecho para girar. Usa la rueda para acercar. Girar vista también funciona con el botón izquierdo o de forma táctil. La cámara no mueve el líquido.',
			'Glissez avec le bouton droit pour tourner, utilisez la molette pour zoomer. Tourner la vue fonctionne aussi avec le bouton gauche ou au toucher. La caméra ne déplace pas le liquide.',
			'Trascina con il tasto destro per ruotare, usa la rotella per lo zoom. Ruota vista funziona anche con il tasto sinistro o il tocco. La fotocamera non muove il liquido.',
			'Arraste com o botão direito para girar. Use a roda para ampliar. Girar visualização também funciona com o botão esquerdo ou por toque. A câmera não move o líquido.',
			'Sleep met rechts om te draaien, gebruik het muiswiel om te zoomen. Weergave draaien werkt ook met de linkermuisknop of aanraking. De camera verplaatst de vloeistof niet.',
		],
	'Drag to orbit · scroll to zoom · camera movement leaves the bath unchanged':
		[
			'Ziehen zum Drehen · Mausrad zum Zoomen · die Kamera beeinflusst das Bad nicht',
			'Arrastra para girar · rueda para acercar · la cámara no altera el baño',
			'Glisser pour tourner · molette pour zoomer · la caméra ne modifie pas le bain',
			'Trascina per ruotare · rotella per lo zoom · la fotocamera non modifica il bagno',
			'Arraste para girar · roda para ampliar · a câmera não altera o banho',
			'Sleep om te draaien · muiswiel om te zoomen · de camera verandert het bad niet',
		],
	'Experiment with liquids, stir the bath and catch the light.': [
		'Mit Flüssigkeiten experimentieren, das Bad bewegen und das Licht einfangen.',
		'Experimenta con líquidos, remueve el baño y atrapa la luz.',
		'Expérimentez avec les liquides, remuez le bain et captez la lumière.',
		'Sperimenta con i liquidi, muovi il bagno e cattura la luce.',
		'Experimente com líquidos, agite o banho e capture a luz.',
		'Experimenteer met vloeistoffen, roer in het bad en vang het licht.',
	],
	'Liquid metal': [
		'Flüssigmetall',
		'Metal líquido',
		'Métal liquide',
		'Metallo liquido',
		'Metal líquido',
		'Vloeibaar metaal',
	],
	Alcohol: [ 'Alkohol', 'Alcohol', 'Alcool', 'Alcol', 'Álcool', 'Alcohol' ],
	Surfactant: [
		'Tensid',
		'Tensioactivo',
		'Tensioactif',
		'Tensioattivo',
		'Surfactante',
		'Oppervlakteactieve stof',
	],
	Cohesion: [
		'Zusammenhalt',
		'Cohesión',
		'Cohésion',
		'Coesione',
		'Coesão',
		'Samenhang',
	],
	'Spreading strength': [
		'Ausbreitungsstärke',
		'Intensidad de expansión',
		'Force de dispersion',
		'Intensità di diffusione',
		'Força de expansão',
		'Verspreidingskracht',
	],
	Evaporation: [
		'Verdunstung',
		'Evaporación',
		'Évaporation',
		'Evaporazione',
		'Evaporação',
		'Verdamping',
	],
	'Reflective beads stay separate from water and oil. Stir to stretch them into veins.':
		[
			'Spiegelnde Perlen bleiben von Wasser und Öl getrennt. Durch Rühren entstehen Adern.',
			'Las perlas reflectantes se separan del agua y del aceite. Remueve para formar vetas.',
			'Les perles réfléchissantes restent séparées de l’eau et de l’huile. Remuez pour former des veines.',
			'Le perle riflettenti restano separate da acqua e olio. Mescola per creare venature.',
			'As gotas refletoras ficam separadas da água e do óleo. Mexa para formar veios.',
			'Spiegelende druppels blijven apart van water en olie. Roer om aders te vormen.',
		],
	'Add to a colored area to push the surface outward. The alcohol fades; its dye remains in the water.':
		[
			'In einen farbigen Bereich geben, um die Oberfläche nach außen zu treiben. Der Alkohol verflüchtigt sich; sein Farbstoff bleibt im Wasser.',
			'Añade en una zona de color para desplazar la superficie hacia fuera. El alcohol se evapora; el tinte queda en el agua.',
			'Versez dans une zone colorée pour repousser la surface. L’alcool s’évapore ; son colorant reste dans l’eau.',
			'Versa in una zona colorata per spingere la superficie verso l’esterno. L’alcol evapora; il colore resta nell’acqua.',
			'Adicione numa área colorida para empurrar a superfície para fora. O álcool evapora; o corante fica na água.',
			'Voeg toe aan een gekleurd gebied om het oppervlak naar buiten te duwen. De alcohol verdampt; de kleurstof blijft in het water.',
		],
	'Lowers local surface tension and opens paths through oil. The additive remains active as it spreads.':
		[
			'Senkt örtlich die Oberflächenspannung und öffnet Wege durch das Öl. Der Zusatz bleibt beim Ausbreiten wirksam.',
			'Reduce la tensión superficial local y abre caminos en el aceite. El aditivo sigue activo al expandirse.',
			'Réduit la tension superficielle locale et ouvre des passages dans l’huile. L’additif reste actif en se dispersant.',
			'Riduce la tensione superficiale locale e apre passaggi nell’olio. L’additivo resta attivo mentre si diffonde.',
			'Reduz a tensão superficial local e abre caminhos no óleo. O aditivo continua ativo ao se espalhar.',
			'Verlaagt plaatselijk de oppervlaktespanning en opent banen door olie. Het middel blijft actief tijdens de verspreiding.',
		],
	'Silver beads': [
		'Silberperlen',
		'Perlas de plata',
		'Perles d’argent',
		'Perle d’argento',
		'Gotas de prata',
		'Zilverdruppels',
	],
	'Silver stream': [
		'Silberstrom',
		'Corriente de plata',
		'Courant d’argent',
		'Flusso d’argento',
		'Fluxo de prata',
		'Zilverstroom',
	],
	'Alcohol bloom': [
		'Alkoholblüte',
		'Flor de alcohol',
		'Fleur d’alcool',
		'Fiore d’alcol',
		'Flor de álcool',
		'Alcoholbloem',
	],
	'Alcohol lagoon': [
		'Alkohollagune',
		'Laguna de alcohol',
		'Lagune d’alcool',
		'Laguna d’alcol',
		'Lagoa de álcool',
		'Alcohollagune',
	],
	'Open cells': [
		'Offene Zellen',
		'Celdas abiertas',
		'Cellules ouvertes',
		'Celle aperte',
		'Células abertas',
		'Open cellen',
	],
	'Moving channels': [
		'Wandernde Kanäle',
		'Canales móviles',
		'Canaux mouvants',
		'Canali in movimento',
		'Canais em movimento',
		'Bewegende kanalen',
	],
	Classic: [
		'Klassik',
		'Clásico',
		'Classique',
		'Classico',
		'Clássico',
		'Klassiek',
	],
	'Fluid Lab': [
		'Fluid Lab',
		'Fluid Lab',
		'Fluid Lab',
		'Fluid Lab',
		'Fluid Lab',
		'Fluid Lab',
	],
	'Mix water and oils, stir the bath and catch the light.': [
		'Wasser und Öle mischen, das Bad bewegen und das Licht einfangen.',
		'Mezcla agua y aceites, remueve el baño y atrapa la luz.',
		'Mélangez eau et huiles, remuez le bain et captez la lumière.',
		'Mescola acqua e oli, muovi il bagno e cattura la luce.',
		'Misture água e óleos, agite o banho e capture a luz.',
		'Meng water en olie, roer in het bad en vang het licht.',
	],
	'Fluid bath': [
		'Flüssigkeitsbad',
		'Baño de líquidos',
		'Bain de liquides',
		'Bagno di liquidi',
		'Banho de líquidos',
		'Vloeistofbad',
	],
	'Hold to add liquid · drag to stir · capture a moment with PNG': [
		'Halten: Flüssigkeit zugeben · Ziehen: rühren · Mit PNG einen Moment festhalten',
		'Mantén para añadir · arrastra para remover · captura un instante en PNG',
		'Maintenez pour verser · glissez pour remuer · capturez un instant en PNG',
		'Tieni premuto per versare · trascina per mescolare · cattura un istante in PNG',
		'Segure para adicionar · arraste para mexer · capture um instante em PNG',
		'Vasthouden: toevoegen · slepen: roeren · leg een moment vast als PNG',
	],
	Liquids: [
		'Flüssigkeiten',
		'Líquidos',
		'Liquides',
		'Liquidi',
		'Líquidos',
		'Vloeistoffen',
	],
	Experiments: [
		'Experimente',
		'Experimentos',
		'Expériences',
		'Esperimenti',
		'Experimentos',
		'Experimenten',
	],
	'Water ink': [
		'Wassertinte',
		'Tinta acuosa',
		'Encre aqueuse',
		'Inchiostro acquoso',
		'Tinta aquosa',
		'Waterinkt',
	],
	'Thin oil': [
		'Dünnes Öl',
		'Aceite fluido',
		'Huile fluide',
		'Olio fluido',
		'Óleo fluido',
		'Dunne olie',
	],
	'Thick oil': [
		'Zähes Öl',
		'Aceite viscoso',
		'Huile épaisse',
		'Olio viscoso',
		'Óleo viscoso',
		'Dikke olie',
	],
	Pipette: [ 'Pipette', 'Pipeta', 'Pipette', 'Pipetta', 'Pipeta', 'Pipet' ],
	Pour: [ 'Eingießen', 'Verter', 'Verser', 'Versa', 'Despejar', 'Gieten' ],
	Stir: [ 'Rühren', 'Remover', 'Remuer', 'Mescola', 'Mexer', 'Roeren' ],
	Air: [ 'Luftstoß', 'Aire', 'Souffle', 'Aria', 'Ar', 'Lucht' ],
	Whirlpool: [
		'Strudel',
		'Remolino',
		'Tourbillon',
		'Vortice',
		'Redemoinho',
		'Draaikolk',
	],
	Obstacle: [
		'Hindernis',
		'Obstáculo',
		'Obstacle',
		'Ostacolo',
		'Obstáculo',
		'Obstakel',
	],
	'Remove obstacle': [
		'Hindernis löschen',
		'Quitar obstáculo',
		'Retirer un obstacle',
		'Rimuovi ostacolo',
		'Remover obstáculo',
		'Obstakel wissen',
	],
	'Brush size': [
		'Werkzeuggröße',
		'Tamaño',
		'Taille',
		'Dimensione',
		'Tamanho',
		'Grootte',
	],
	'Flow rate': [
		'Fördermenge',
		'Caudal',
		'Débit',
		'Portata',
		'Vazão',
		'Debiet',
	],
	'Pigment color': [
		'Pigmentfarbe',
		'Color del pigmento',
		'Couleur du pigment',
		'Colore del pigmento',
		'Cor do pigmento',
		'Pigmentkleur',
	],
	Viscosity: [
		'Viskosität',
		'Viscosidad',
		'Viscosité',
		'Viscosità',
		'Viscosidade',
		'Viscositeit',
	],
	'Color applies to new drops. Viscosity affects this liquid throughout the bath.':
		[
			'Die Farbe gilt für neue Tropfen. Die Viskosität wirkt auf diese Flüssigkeit im ganzen Bad.',
			'El color se aplica a gotas nuevas. La viscosidad afecta a este líquido en todo el baño.',
			'La couleur concerne les nouvelles gouttes. La viscosité agit sur ce liquide dans tout le bain.',
			'Il colore vale per le nuove gocce. La viscosità agisce su questo liquido in tutto il bagno.',
			'A cor vale para novas gotas. A viscosidade afeta este líquido em todo o banho.',
			'De kleur geldt voor nieuwe druppels. De viscositeit beïnvloedt deze vloeistof in het hele bad.',
		],
	'Surface tension': [
		'Oberflächenspannung',
		'Tensión superficial',
		'Tension superficielle',
		'Tensione superficiale',
		'Tensão superficial',
		'Oppervlaktespanning',
	],
	'Ink diffusion': [
		'Tintenausbreitung',
		'Difusión de tinta',
		'Diffusion de l’encre',
		'Diffusione inchiostro',
		'Difusão da tinta',
		'Inktdiffusie',
	],
	'Bath color': [
		'Badfarbe',
		'Color del baño',
		'Couleur du bain',
		'Colore del bagno',
		'Cor do banho',
		'Badkleur',
	],
	Surface: [
		'Oberfläche',
		'Superficie',
		'Surface',
		'Superficie',
		'Superfície',
		'Oppervlak',
	],
	Relief: [ 'Relief', 'Relieve', 'Relief', 'Rilievo', 'Relevo', 'Reliëf' ],
	Gloss: [ 'Glanz', 'Brillo', 'Brillance', 'Lucentezza', 'Brilho', 'Glans' ],
	Transparency: [
		'Transparenz',
		'Transparencia',
		'Transparence',
		'Trasparenza',
		'Transparência',
		'Transparantie',
	],
	'Oil iridescence': [
		'Ölschillern',
		'Iridescencia del aceite',
		'Iridescence de l’huile',
		'Iridescenza dell’olio',
		'Iridescência do óleo',
		'Irisering van olie',
	],
	Light: [ 'Licht', 'Luz', 'Lumière', 'Luce', 'Luz', 'Licht' ],
	'View angle': [
		'Blickwinkel',
		'Ángulo de vista',
		'Angle de vue',
		'Angolo di vista',
		'Ângulo de visão',
		'Kijkhoek',
	],
	Output: [ 'Ausgabe', 'Salida', 'Sortie', 'Risultato', 'Saída', 'Uitvoer' ],
	Appearance: [
		'Darstellung',
		'Aspecto',
		'Aspect',
		'Aspetto',
		'Aparência',
		'Weergave',
	],
	'Wet surface': [
		'Nasse Oberfläche',
		'Superficie húmeda',
		'Surface humide',
		'Superficie bagnata',
		'Superfície molhada',
		'Nat oppervlak',
	],
	'Paper print': [
		'Papierabzug',
		'Impresión en papel',
		'Empreinte papier',
		'Stampa su carta',
		'Impressão em papel',
		'Papierafdruk',
	],
	'Download PNG': [
		'PNG herunterladen',
		'Descargar PNG',
		'Télécharger le PNG',
		'Scarica PNG',
		'Baixar PNG',
		'PNG downloaden',
	],
	'Record 6 seconds': [
		'6 Sekunden aufnehmen',
		'Grabar 6 segundos',
		'Enregistrer 6 secondes',
		'Registra 6 secondi',
		'Gravar 6 segundos',
		'6 seconden opnemen',
	],
	'Save experiment': [
		'Experiment speichern',
		'Guardar experimento',
		'Enregistrer l’expérience',
		'Salva esperimento',
		'Salvar experimento',
		'Experiment opslaan',
	],
	'Open experiment': [
		'Experiment öffnen',
		'Abrir experimento',
		'Ouvrir une expérience',
		'Apri esperimento',
		'Abrir experimento',
		'Experiment openen',
	],
	'This experiment could not be opened.': [
		'Dieses Experiment konnte nicht geöffnet werden.',
		'No se pudo abrir este experimento.',
		'Impossible d’ouvrir cette expérience.',
		'Impossibile aprire questo esperimento.',
		'Não foi possível abrir este experimento.',
		'Dit experiment kon niet worden geopend.',
	],
	'Could not export.': [
		'Der Export ist fehlgeschlagen.',
		'No se pudo exportar.',
		'Échec de l’exportation.',
		'Esportazione non riuscita.',
		'Não foi possível exportar.',
		'Exporteren is mislukt.',
	],
	'Insert fluid bath': [
		'Flüssigkeitsbad einfügen',
		'Insertar baño de líquidos',
		'Insérer le bain',
		'Inserisci bagno',
		'Inserir banho de líquidos',
		'Vloeistofbad invoegen',
	],
	'Update fluid bath': [
		'Flüssigkeitsbad aktualisieren',
		'Actualizar baño de líquidos',
		'Actualiser le bain',
		'Aggiorna bagno',
		'Atualizar banho de líquidos',
		'Vloeistofbad bijwerken',
	],
	'Video recording is unavailable in this browser.': [
		'Dieser Browser kann kein Video aufnehmen.',
		'Este navegador no puede grabar vídeo.',
		'Ce navigateur ne peut pas enregistrer de vidéo.',
		'Questo browser non può registrare video.',
		'Este navegador não pode gravar vídeo.',
		'Deze browser kan geen video opnemen.',
	],
	'Graphics interrupted. Save the experiment and reopen it.': [
		'Grafik unterbrochen. Speichere das Experiment und öffne es erneut.',
		'Gráficos interrumpidos. Guarda el experimento y ábrelo de nuevo.',
		'Affichage interrompu. Enregistrez l’expérience puis rouvrez-la.',
		'Grafica interrotta. Salva e riapri l’esperimento.',
		'Gráficos interrompidos. Salve e reabra o experimento.',
		'Weergave onderbroken. Sla het experiment op en open het opnieuw.',
	],
	'Fluid Lab needs WebGL2. Classic marbling is still available.': [
		'Fluid Lab benötigt WebGL2. Die klassische Marmorierung ist weiterhin verfügbar.',
		'Fluid Lab necesita WebGL2. El marmoleado clásico sigue disponible.',
		'Fluid Lab nécessite WebGL2. La marbrure classique reste disponible.',
		'Fluid Lab richiede WebGL2. La marmorizzazione classica resta disponibile.',
		'Fluid Lab precisa de WebGL2. A marmorização clássica continua disponível.',
		'Fluid Lab vereist WebGL2. Klassiek marmeren blijft beschikbaar.',
	],
	'New variation': [
		'Neue Variante',
		'Nueva variante',
		'Nouvelle variante',
		'Nuova variante',
		'Nova variação',
		'Nieuwe variant',
	],
	Play: [ 'Start', 'Iniciar', 'Démarrer', 'Avvia', 'Iniciar', 'Start' ],
	Pause: [ 'Pause', 'Pausa', 'Pause', 'Pausa', 'Pausar', 'Pauze' ],
	Paused: [
		'Angehalten',
		'En pausa',
		'En pause',
		'In pausa',
		'Pausado',
		'Gepauzeerd',
	],
	Undo: [
		'Zurück',
		'Deshacer',
		'Annuler',
		'Annulla',
		'Desfazer',
		'Ongedaan',
	],
	Redo: [
		'Wiederholen',
		'Rehacer',
		'Rétablir',
		'Ripeti',
		'Refazer',
		'Opnieuw',
	],
	Restart: [
		'Neustart',
		'Reiniciar',
		'Recommencer',
		'Ricomincia',
		'Reiniciar',
		'Herstarten',
	],
	Speed: [
		'Geschwindigkeit',
		'Velocidad',
		'Vitesse',
		'Velocità',
		'Velocidade',
		'Snelheid',
	],
	'Normal speed': [
		'Normales Tempo',
		'Velocidad normal',
		'Vitesse normale',
		'Velocità normale',
		'Velocidade normal',
		'Normale snelheid',
	],
	'Half speed': [
		'Halbes Tempo',
		'Media velocidad',
		'Demi-vitesse',
		'Metà velocità',
		'Metade da velocidade',
		'Halve snelheid',
	],
	'Quarter speed': [
		'Vierteltempo',
		'Un cuarto de velocidad',
		'Quart de vitesse',
		'Un quarto di velocità',
		'Um quarto da velocidade',
		'Kwartsnelheid',
	],
	'Oil islands': [
		'Ölinseln',
		'Islas de aceite',
		'Îlots d’huile',
		'Isole d’olio',
		'Ilhas de óleo',
		'Olie-eilanden',
	],
	'Twin vortices': [
		'Zwillingswirbel',
		'Vórtices gemelos',
		'Tourbillons jumeaux',
		'Vortici gemelli',
		'Vórtices gêmeos',
		'Tweelingwervels',
	],
	'Honey glass': [
		'Honigglas',
		'Cristal de miel',
		'Verre de miel',
		'Vetro di miele',
		'Vidro de mel',
		'Honingglas',
	],
	'Blue lagoon': [
		'Blaue Lagune',
		'Laguna azul',
		'Lagon bleu',
		'Laguna blu',
		'Lagoa azul',
		'Blauwe lagune',
	],
	'Silk ribbons': [
		'Seidenbänder',
		'Cintas de seda',
		'Rubans de soie',
		'Nastri di seta',
		'Fitas de seda',
		'Zijden linten',
	],
	'Oil pearls': [
		'Ölperlen',
		'Perlas de aceite',
		'Perles d’huile',
		'Perle d’olio',
		'Pérolas de óleo',
		'Olieparels',
	],
	'Petal pool': [
		'Blütenbad',
		'Baño de pétalos',
		'Bain de pétales',
		'Bagno di petali',
		'Banho de pétalas',
		'Bloemblaadjesbad',
	],
	Countercurrent: [
		'Gegenstrom',
		'Contracorriente',
		'Contre-courant',
		'Controcorrente',
		'Contracorrente',
		'Tegenstroom',
	],
	Archipelago: [
		'Inselkette',
		'Archipiélago',
		'Archipel',
		'Arcipelago',
		'Arquipélago',
		'Archipel',
	],
	'Color river': [
		'Farbstrom',
		'Río de color',
		'Rivière de couleurs',
		'Fiume di colore',
		'Rio de cores',
		'Kleurenrivier',
	],
	'Slow folds': [
		'Langsame Falten',
		'Pliegues lentos',
		'Plis lents',
		'Pieghe lente',
		'Dobras lentas',
		'Langzame plooien',
	],
	'Orbital flow': [
		'Umlaufströmung',
		'Flujo orbital',
		'Flux orbital',
		'Flusso orbitale',
		'Fluxo orbital',
		'Omloopstroming',
	],
	'Cell garden': [
		'Zellgarten',
		'Jardín celular',
		'Jardin de cellules',
		'Giardino cellulare',
		'Jardim celular',
		'Celtuin',
	],
	'Aurora ink': [
		'Auroratinte',
		'Tinta aurora',
		'Encre aurore',
		'Inchiostro aurora',
		'Tinta aurora',
		'Aurora-inkt',
	],
	'Amber tides': [
		'Bernsteinflut',
		'Mareas ámbar',
		'Marées ambrées',
		'Maree ambrate',
		'Marés de âmbar',
		'Ambergolven',
	],
	'Clear bath': [
		'Klares Bad',
		'Baño limpio',
		'Bain clair',
		'Bagno limpido',
		'Banho limpo',
		'Helder bad',
	],
};
