// English keys; German, Spanish, French, Italian, Brazilian Portuguese, Dutch.
export const TOOL_STRINGS = {
	Remove: [
		'Entfernen',
		'Quitar',
		'Retirer',
		'Rimuovere',
		'Remover',
		'Verwijderen',
	],
	Rotate: [ 'Drehen', 'Girar', 'Tourner', 'Ruotare', 'Girar', 'Draaien' ],
	'Apply liquid': [
		'Auftragen',
		'Aplicar',
		'Appliquer',
		'Applicare',
		'Aplicar',
		'Aanbrengen',
	],
	Flow: [ 'Strömung', 'Flujo', 'Écoulement', 'Flusso', 'Fluxo', 'Stroming' ],
	Obstacles: [
		'Hindernisse',
		'Obstáculos',
		'Obstacles',
		'Ostacoli',
		'Obstáculos',
		'Obstakels',
	],
	Extract: [
		'Entnehmen',
		'Extraer',
		'Retirer',
		'Prelevare',
		'Retirar',
		'Wegnemen',
	],
	Lift: [
		'Anheben',
		'Elevar',
		'Soulever',
		'Sollevare',
		'Elevar',
		'Optillen',
	],
	Heat: [ 'Wärme', 'Calor', 'Chaleur', 'Calore', 'Calor', 'Warmte' ],
	Cold: [ 'Kälte', 'Frío', 'Froid', 'Freddo', 'Frio', 'Koude' ],
	'Hold to add drops of the selected liquid. Drag to draw a trail.': [
		'Gedrückt halten, um die gewählte Flüssigkeit einzutropfen. Ziehen erzeugt eine Spur.',
		'Mantén pulsado para añadir gotas del líquido elegido. Arrastra para trazar una estela.',
		'Maintenez pour ajouter des gouttes du liquide choisi. Faites glisser pour tracer une traînée.',
		'Tieni premuto per aggiungere gocce del liquido scelto. Trascina per disegnare una scia.',
		'Mantenha pressionado para adicionar gotas do líquido escolhido. Arraste para traçar um rastro.',
		'Houd ingedrukt om druppels van de gekozen vloeistof toe te voegen. Sleep om een spoor te maken.',
	],
	'Hold to pour the selected liquid. The stream spreads as you hold.': [
		'Gedrückt halten, um die gewählte Flüssigkeit einzugießen. Der Strom breitet sich dabei aus.',
		'Mantén pulsado para verter el líquido elegido. El chorro se extiende mientras mantienes pulsado.',
		'Maintenez pour verser le liquide choisi. Le jet s’étale tant que vous maintenez.',
		'Tieni premuto per versare il liquido scelto. Il flusso si allarga mentre tieni premuto.',
		'Mantenha pressionado para despejar o líquido escolhido. O fluxo se espalha enquanto você pressiona.',
		'Houd ingedrukt om de gekozen vloeistof te gieten. De stroom spreidt zich daarbij uit.',
	],
	'Drag through the bath to move the liquid. The flow continues after release.':
		[
			'Durch das Bad ziehen, um die Flüssigkeit zu bewegen. Die Strömung läuft nach dem Loslassen weiter.',
			'Arrastra por el baño para mover el líquido. El flujo continúa después de soltar.',
			'Faites glisser dans le bain pour déplacer le liquide. L’écoulement continue après le relâchement.',
			'Trascina nel bagno per muovere il liquido. Il flusso continua dopo il rilascio.',
			'Arraste pelo banho para mover o líquido. O fluxo continua após soltar.',
			'Sleep door het bad om de vloeistof te bewegen. De stroming gaat door na het loslaten.',
		],
	'Hold to blow liquid away from the pointer.': [
		'Gedrückt halten, um Flüssigkeit vom Zeiger wegzublasen.',
		'Mantén pulsado para alejar el líquido del puntero con aire.',
		'Maintenez pour souffler le liquide loin du pointeur.',
		'Tieni premuto per soffiare il liquido lontano dal puntatore.',
		'Mantenha pressionado para soprar o líquido para longe do ponteiro.',
		'Houd ingedrukt om vloeistof van de aanwijzer weg te blazen.',
	],
	'Hold to spin the liquid around the pointer.': [
		'Gedrückt halten, um die Flüssigkeit um den Zeiger wirbeln zu lassen.',
		'Mantén pulsado para hacer girar el líquido alrededor del puntero.',
		'Maintenez pour faire tourbillonner le liquide autour du pointeur.',
		'Tieni premuto per far ruotare il liquido intorno al puntatore.',
		'Mantenha pressionado para girar o líquido ao redor do ponteiro.',
		'Houd ingedrukt om de vloeistof rond de aanwijzer te laten draaien.',
	],
	'Hold to lift liquid in the deep bath and let it splash back.': [
		'Gedrückt halten, um Flüssigkeit im tiefen Bad anzuheben und zurückspritzen zu lassen.',
		'Mantén pulsado para elevar líquido en el baño profundo y dejarlo caer con salpicaduras.',
		'Maintenez pour soulever le liquide dans le bain profond et le laisser retomber en éclaboussant.',
		'Tieni premuto per sollevare il liquido nel bagno profondo e lasciarlo ricadere con schizzi.',
		'Mantenha pressionado para elevar o líquido no banho profundo e deixá-lo cair com respingos.',
		'Houd ingedrukt om vloeistof in het diepe bad op te tillen en terug te laten spatten.',
	],
	'Click to place a lasting heat source. Drag its handle to move it.': [
		'Klicken setzt eine dauerhafte Wärmequelle. Zum Verschieben ihren Griff ziehen.',
		'Haz clic para colocar una fuente de calor permanente. Arrastra su control para moverla.',
		'Cliquez pour placer une source de chaleur persistante. Déplacez-la en faisant glisser sa poignée.',
		'Fai clic per posizionare una fonte di calore persistente. Trascina la maniglia per spostarla.',
		'Clique para posicionar uma fonte de calor permanente. Arraste a alça para movê-la.',
		'Klik om een blijvende warmtebron te plaatsen. Sleep de greep om deze te verplaatsen.',
	],
	'Click to place a lasting cold source. Drag its handle to move it.': [
		'Klicken setzt eine dauerhafte Kältequelle. Zum Verschieben ihren Griff ziehen.',
		'Haz clic para colocar una fuente de frío permanente. Arrastra su control para moverla.',
		'Cliquez pour placer une source de froid persistante. Déplacez-la en faisant glisser sa poignée.',
		'Fai clic per posizionare una fonte di freddo persistente. Trascina la maniglia per spostarla.',
		'Clique para posicionar uma fonte de frio permanente. Arraste a alça para movê-la.',
		'Klik om een blijvende koudebron te plaatsen. Sleep de greep om deze te verplaatsen.',
	],
	'Click to place a lasting magnet. Drag its handle to move it. It acts on ferrofluid.':
		[
			'Klicken setzt einen dauerhaften Magneten. Zum Verschieben seinen Griff ziehen. Er wirkt auf Ferrofluid.',
			'Haz clic para colocar un imán permanente. Arrastra su control para moverlo. Actúa sobre el ferrofluido.',
			'Cliquez pour placer un aimant persistant. Déplacez-le par sa poignée. Il agit sur le ferrofluide.',
			'Fai clic per posizionare un magnete persistente. Trascina la maniglia per spostarlo. Agisce sul ferrofluido.',
			'Clique para posicionar um ímã permanente. Arraste a alça para movê-lo. Ele atua sobre o ferrofluido.',
			'Klik om een blijvende magneet te plaatsen. Sleep de greep om deze te verplaatsen. Hij werkt op ferrovloeistof.',
		],
	'Click a source handle to remove its lasting effect.': [
		'Auf den Griff einer Quelle klicken, um ihre dauerhafte Wirkung zu entfernen.',
		'Haz clic en el control de una fuente para eliminar su efecto permanente.',
		'Cliquez sur la poignée d’une source pour supprimer son effet persistant.',
		'Fai clic sulla maniglia di una fonte per rimuovere il suo effetto persistente.',
		'Clique na alça de uma fonte para remover seu efeito permanente.',
		'Klik op de greep van een bron om het blijvende effect te verwijderen.',
	],
	'Click to place a solid shape, or drag a shape to move it. Choose its form on the right.':
		[
			'Klicken platziert eine feste Form, Ziehen verschiebt sie. Die Form wird rechts gewählt.',
			'Haz clic para colocar una forma sólida o arrástrala para moverla. Elige su forma a la derecha.',
			'Cliquez pour placer une forme solide ou faites-la glisser pour la déplacer. Choisissez sa forme à droite.',
			'Fai clic per posizionare una forma solida o trascinala per spostarla. Scegli la forma a destra.',
			'Clique para posicionar uma forma sólida ou arraste para movê-la. Escolha a forma à direita.',
			'Klik om een vaste vorm te plaatsen of sleep een vorm om deze te verplaatsen. Kies de vorm rechts.',
		],
	'Click an obstacle to remove it. Drag to erase painted obstacles.': [
		'Auf ein Hindernis klicken, um es zu entfernen. Ziehen radiert gemalte Hindernisse.',
		'Haz clic en un obstáculo para eliminarlo. Arrastra para borrar obstáculos pintados.',
		'Cliquez sur un obstacle pour le supprimer. Faites glisser pour effacer les obstacles peints.',
		'Fai clic su un ostacolo per rimuoverlo. Trascina per cancellare gli ostacoli dipinti.',
		'Clique em um obstáculo para removê-lo. Arraste para apagar obstáculos pintados.',
		'Klik op een obstakel om het te verwijderen. Sleep om geschilderde obstakels te wissen.',
	],
	'Drag to rotate the view. This changes the camera, not the liquid.': [
		'Ziehen dreht die Ansicht. Dabei bewegt sich die Kamera, die Flüssigkeit bleibt unverändert.',
		'Arrastra para girar la vista. Cambia la cámara, no el líquido.',
		'Faites glisser pour tourner la vue. Cela déplace la caméra, pas le liquide.',
		'Trascina per ruotare la vista. Cambia la fotocamera, non il liquido.',
		'Arraste para girar a vista. Isso muda a câmera, não o líquido.',
		'Sleep om de weergave te draaien. Dit verandert de camera, niet de vloeistof.',
	],
	'Hold to remove liquid from the deep bath at the pointer.': [
		'Gedrückt halten, um am Zeiger Flüssigkeit aus dem tiefen Bad abzusaugen.',
		'Mantén pulsado para extraer líquido del baño profundo en el puntero.',
		'Maintenez pour retirer le liquide du bain profond au niveau du pointeur.',
		'Tieni premuto per rimuovere il liquido dal bagno profondo sotto il puntatore.',
		'Mantenha pressionado para retirar líquido do banho profundo no ponteiro.',
		'Houd ingedrukt om bij de aanwijzer vloeistof uit het diepe bad weg te zuigen.',
	],
};
