// German, Spanish, French, Italian, Brazilian Portuguese, Dutch.
export const VOLUME_STRINGS = {
	Chemistry: [
		'Chemie',
		'Química',
		'Chimie',
		'Chimica',
		'Química',
		'Chemie',
	],
	'Bicarbonate solution': [
		'Natronlösung',
		'Solución de bicarbonato',
		'Solution de bicarbonate',
		'Soluzione di bicarbonato',
		'Solução de bicarbonato',
		'Bicarbonaatoplossing',
	],
	'Crystal solution': [
		'Kristalllösung',
		'Solución cristalina',
		'Solution cristalline',
		'Soluzione cristallina',
		'Solução cristalina',
		'Kristaloplossing',
	],
	'Reactive medium': [
		'Reaktionsmedium',
		'Medio reactivo',
		'Milieu réactif',
		'Mezzo reattivo',
		'Meio reativo',
		'Reactief medium',
	],
	'Reaction trigger': [
		'Reaktionsstarter',
		'Activador de reacción',
		'Déclencheur de réaction',
		'Attivatore di reazione',
		'Ativador de reação',
		'Reactiestarter',
	],
	'Lift and splash': [
		'Anheben und spritzen',
		'Elevar y salpicar',
		'Soulever et éclabousser',
		'Sollevare e spruzzare',
		'Elevar e respingar',
		'Optillen en spatten',
	],
	Drain: [
		'Ablassen',
		'Drenar',
		'Vidanger',
		'Svuotare',
		'Drenar',
		'Aftappen',
	],
	'Relative density': [
		'Relative Dichte',
		'Densidad relativa',
		'Densité relative',
		'Densità relativa',
		'Densidade relativa',
		'Relatieve dichtheid',
	],
	'Injection depth': [
		'Einfülltiefe',
		'Profundidad de inyección',
		'Profondeur d’injection',
		'Profondità di iniezione',
		'Profundidade de injeção',
		'Injectiediepte',
	],
	'Drop height': [
		'Fallhöhe',
		'Altura de caída',
		'Hauteur de chute',
		'Altezza di caduta',
		'Altura de queda',
		'Valhoogte',
	],
	Gravity: [
		'Schwerkraft',
		'Gravedad',
		'Gravité',
		'Gravità',
		'Gravidade',
		'Zwaartekracht',
	],
	'Tilt left / right': [
		'Neigung links / rechts',
		'Inclinación izquierda / derecha',
		'Inclinaison gauche / droite',
		'Inclinazione sinistra / destra',
		'Inclinação esquerda / direita',
		'Kanteling links / rechts',
	],
	'Tilt front / back': [
		'Neigung vorne / hinten',
		'Inclinación frontal / trasera',
		'Inclinaison avant / arrière',
		'Inclinazione avanti / indietro',
		'Inclinação frente / trás',
		'Kanteling voor / achter',
	],
	'Crystal growth': [
		'Kristallwachstum',
		'Crecimiento de cristales',
		'Croissance cristalline',
		'Crescita dei cristalli',
		'Crescimento de cristais',
		'Kristalgroei',
	],
	'Reaction rate': [
		'Reaktionsgeschwindigkeit',
		'Velocidad de reacción',
		'Vitesse de réaction',
		'Velocità di reazione',
		'Velocidade de reação',
		'Reactiesnelheid',
	],
	'Top view': [
		'Draufsicht',
		'Vista superior',
		'Vue de dessus',
		'Vista dall’alto',
		'Vista superior',
		'Bovenaanzicht',
	],
	'Submerged color clouds': [
		'Farbwolken unter Wasser',
		'Nubes de color sumergidas',
		'Nuages de couleur immergés',
		'Nuvole di colore sommerse',
		'Nuvens de cor submersas',
		'Onderwaterkleurwolken',
	],
	'Floating oil, sinking metal': [
		'Schwimmendes Öl, sinkendes Metall',
		'Aceite flotante, metal que se hunde',
		'Huile flottante, métal plongeant',
		'Olio galleggiante, metallo che affonda',
		'Óleo flutuante, metal afundando',
		'Drijvende olie, zinkend metaal',
	],
	'Splash basin': [
		'Spritzbecken',
		'Cubeta de salpicaduras',
		'Bassin à éclaboussures',
		'Vasca degli spruzzi',
		'Bacia de respingos',
		'Spatbassin',
	],
	'Viscous ribbons': [
		'Zähflüssige Bänder',
		'Cintas viscosas',
		'Rubans visqueux',
		'Nastri viscosi',
		'Fitas viscosas',
		'Stroperige linten',
	],
	'Effervescent colors': [
		'Sprudelnde Farben',
		'Colores efervescentes',
		'Couleurs effervescentes',
		'Colori effervescenti',
		'Cores efervescentes',
		'Bruisende kleuren',
	],
	'Foam and currents': [
		'Schaum und Strömung',
		'Espuma y corrientes',
		'Mousse et courants',
		'Schiuma e correnti',
		'Espuma e correntes',
		'Schuim en stroming',
	],
	'Cold crystal garden': [
		'Kalter Kristallgarten',
		'Jardín de cristales fríos',
		'Jardin de cristaux froids',
		'Giardino di cristalli freddi',
		'Jardim de cristais frios',
		'Koude kristaltuin',
	],
	'Dissolving crystals': [
		'Kristalle lösen sich auf',
		'Cristales que se disuelven',
		'Cristaux en dissolution',
		'Cristalli che si dissolvono',
		'Cristais se dissolvendo',
		'Oplossende kristallen',
	],
	'Traveling chemical waves': [
		'Wandernde Reaktionswellen',
		'Ondas químicas viajeras',
		'Ondes chimiques progressives',
		'Onde chimiche viaggianti',
		'Ondas químicas viajantes',
		'Voortplantende reactiegolven',
	],
	'Convection vessel': [
		'Konvektionsbecken',
		'Recipiente de convección',
		'Bassin de convection',
		'Vasca di convezione',
		'Recipiente de convecção',
		'Convectiebassin',
	],
	'Acid and bicarbonate release gas. Surfactant keeps bubbles at the surface longer.':
		[
			'Säure und Natron setzen Gas frei. Tensid hält Blasen länger an der Oberfläche.',
			'El ácido y el bicarbonato liberan gas. El tensioactivo retiene las burbujas en la superficie.',
			'L’acide et le bicarbonate libèrent du gaz. Le tensioactif prolonge la présence des bulles en surface.',
			'Acido e bicarbonato liberano gas. Il tensioattivo trattiene le bolle in superficie.',
			'Ácido e bicarbonato liberam gás. O surfactante mantém as bolhas na superfície por mais tempo.',
			'Zuur en bicarbonaat vormen gas. Oppervlakteactieve stof houdt bellen langer aan het oppervlak.',
		],
	'Cool to grow crystals. Warm to dissolve them back into the liquid.': [
		'Abkühlen lässt Kristalle wachsen. Wärme löst sie wieder in der Flüssigkeit auf.',
		'Enfría para formar cristales. Calienta para disolverlos.',
		'Refroidissez pour faire croître les cristaux. Réchauffez pour les dissoudre.',
		'Raffredda per far crescere i cristalli. Riscalda per scioglierli.',
		'Resfrie para formar cristais. Aqueça para dissolvê-los.',
		'Koel af om kristallen te laten groeien. Verwarm om ze weer op te lossen.',
	],
	'An excitable medium with finite fuel. Add a reaction trigger to start a traveling wave.':
		[
			'Ein anregbares Medium mit begrenztem Vorrat. Ein Reaktionsstarter löst eine wandernde Welle aus.',
			'Un medio excitable con combustible limitado. Añade un activador para iniciar una onda.',
			'Un milieu excitable aux réserves limitées. Ajoutez un déclencheur pour lancer une onde.',
			'Un mezzo eccitabile con riserve finite. Aggiungi un attivatore per avviare un’onda.',
			'Um meio excitável com reserva limitada. Adicione um ativador para iniciar uma onda.',
			'Een prikkelbaar medium met eindige brandstof. Voeg een starter toe om een golf te starten.',
		],
	'Start a local reaction in the reactive medium. Stir to carry the wave through the liquid.':
		[
			'Startet eine lokale Reaktion im Reaktionsmedium. Rühren trägt die Welle durch die Flüssigkeit.',
			'Inicia una reacción local en el medio. Remueve para transportar la onda.',
			'Déclenchez une réaction locale. Remuez pour transporter l’onde dans le liquide.',
			'Avvia una reazione locale. Mescola per trasportare l’onda nel liquido.',
			'Inicie uma reação local. Agite para transportar a onda pelo líquido.',
			'Start een lokale reactie. Roer om de golf door de vloeistof te voeren.',
		],
	'Use Drain to make room for more liquid. Injection depth reaches below the surface; drop height adds a falling stream.':
		[
			'Mit Ablassen Platz für neue Flüssigkeit schaffen. Die Einfülltiefe reicht unter die Oberfläche, die Fallhöhe erzeugt einen fallenden Strahl.',
			'Drena para añadir más líquido. La profundidad llega bajo la superficie; la altura crea un chorro.',
			'Vidangez pour ajouter du liquide. La profondeur atteint le dessous de la surface ; la hauteur crée un jet.',
			'Svuota per aggiungere liquido. La profondità raggiunge il fondo; l’altezza crea un getto.',
			'Drene para adicionar líquido. A profundidade alcança abaixo da superfície; a altura cria um jato.',
			'Tap af om vloeistof toe te voegen. Injectiediepte reikt onder het oppervlak; valhoogte vormt een straal.',
		],
};
