/**
 * Parametric silhouette generators - pure geometry, no canvas.
 *
 * Two sources feed the paper: real traced silhouettes for living
 * things (src/core/silhouettes.js, CC0, generated by
 * tools/build-silhouettes.mjs) and procedural generators for
 * everything that must reroll per seed - ridges, skylines, trees,
 * grasses, reeds and flowers.
 *
 * CONTRACT: every helper returns an array of STAMPS, and one stamp is
 * an array of rings. The rasterizer fills a stamp in ONE even-odd pass
 * (so traced holes stay holes) and different stamps in separate passes
 * (so overlapping trees union instead of cancelling out).
 */

import { rng, valueNoise } from './geom.js';
import { SILHOUETTES } from './silhouettes.js';

const TAU = Math.PI * 2;

const ellipse = ( cx, cy, rx, ry, n = 28, rot = 0 ) => {
	const out = [];
	for ( let i = 0; i < n; i++ ) {
		const a = ( i / n ) * TAU;
		const px = Math.cos( a ) * rx;
		const py = Math.sin( a ) * ry;
		out.push( [
			cx + px * Math.cos( rot ) - py * Math.sin( rot ),
			cy + px * Math.sin( rot ) + py * Math.cos( rot ),
		] );
	}
	return out;
};


/* ------------------------------- profiles ------------------------------- */

/**
 * A profile is y(x) over 0..1 (0 = sheet top). `sheetPolys` turns it
 * into the paper polygon: bottom-anchored sheets keep paper BELOW the
 * line, top-anchored sheets (sky, clouds) keep paper ABOVE it.
 */
export function profileLine(
	kind,
	{ seed = 1, height = 0.35, jag = 0.5, yBase = 0.55 }
) {
	const n = valueNoise( seed, 4 );
	const ridged = valueNoise( seed + 77, 3 );
	const r = rng( seed + 5 );
	const N = 513;
	const ys = new Float32Array( N );
	if ( 'city' === kind ) {
		// A skyline of blocks: varied widths and heights, the odd
		// setback, spire or water tower - never a plain bar chart.
		let i = 0;
		while ( i < N ) {
			const bw = Math.max( 5, Math.round( ( 0.03 + r() * 0.075 ) * N ) );
			const bh = yBase - ( 0.14 + r() * 0.86 ) * height;
			const roll = r();
			const setback = roll > 0.72 ? Math.round( bw * 0.35 ) : 0;
			for ( let k = 0; k < bw && i < N; k++, i++ ) {
				let y = bh;
				if ( setback && k < setback ) {
					y = bh + height * 0.16;
				} else if ( setback && k > bw - setback ) {
					y = bh + height * 0.16;
				}
				ys[ i ] = y;
			}
			// A slender spire or mast on top of some blocks.
			if ( roll < 0.22 && i > 6 ) {
				const at = i - Math.round( bw / 2 );
				const mastH = bh - height * ( 0.12 + r() * 0.22 );
				for ( let k = -2; k <= 2; k++ ) {
					const idx = at + k;
					if ( idx >= 0 && idx < N ) {
						ys[ idx ] = Math.min( ys[ idx ], mastH );
					}
				}
			}
		}
		return ys;
	}
	for ( let i = 0; i < N; i++ ) {
		const x = i / ( N - 1 );
		let v;
		if ( 'ridge' === kind ) {
			// Ridged noise: sharp alpine peaks over a broad massif.
			const base = n( x * 2.4 );
			const sharp = 1 - Math.abs( 2 * ridged( x * 4.6 ) - 1 );
			const fine = 1 - Math.abs( 2 * ridged( x * 11.3 ) - 1 );
			v =
				base * 0.4 +
				sharp * 0.45 * ( 0.5 + jag * 0.5 ) +
				fine * 0.15 * jag;
		} else if ( 'dunes' === kind ) {
			// Soft, wind-blown crests: asymmetric sine plus drift.
			const k = 2 + Math.round( jag * 3 );
			const s = Math.sin( x * k * Math.PI + seed );
			v = ( Math.pow( Math.abs( s ), 0.7 ) * 0.6 + n( x * 1.6 ) * 0.4 );
		} else if ( 'waves' === kind ) {
			// Scalloped water: rounded repeating arcs plus drift.
			const kf = 7 + Math.round( jag * 8 );
			v =
				Math.abs( Math.sin( x * kf * Math.PI + seed ) ) * 0.5 +
				n( x * 2.2 ) * 0.5;
		} else if ( 'clouds' === kind ) {
			// Puffy underside for a top-anchored sky sheet: overlapping
			// arcs of different sizes, never a noisy hem.
			const k1 = 3 + Math.round( jag * 3 );
			const k2 = k1 * 2 + 1;
			v =
				Math.pow(
					Math.abs( Math.sin( x * k1 * Math.PI + seed * 0.7 ) ),
					0.6
				) *
					0.55 +
				Math.pow(
					Math.abs( Math.sin( x * k2 * Math.PI + seed * 1.9 ) ),
					0.6
				) *
					0.2 +
				n( x * 1.7 ) * 0.25;
		} else {
			// hills - the default: calm rolling noise.
			v = n( x * 1.8 ) * ( 0.6 + 0.4 * jag );
		}
		ys[ i ] = yBase - v * height;
	}
	return ys;
}

export function sheetPolys( ys, w, h, anchor = 'bottom' ) {
	const poly = [];
	const N = ys.length;
	for ( let i = 0; i < N; i++ ) {
		poly.push( [
			( i / ( N - 1 ) ) * w,
			Math.max( -0.2, Math.min( 1.2, ys[ i ] ) ) * h,
		] );
	}
	if ( 'top' === anchor ) {
		poly.push( [ w, -h * 0.2 ], [ 0, -h * 0.2 ] );
	} else {
		poly.push( [ w, h * 1.2 ], [ 0, h * 1.2 ] );
	}
	return [ poly ];
}

/** y of the profile at unit x, for placing trees and animals on it. */
export function profileAt( ys, x ) {
	const t = Math.max( 0, Math.min( 1, x ) ) * ( ys.length - 1 );
	const i = Math.floor( t );
	const f = t - i;
	return (
		ys[ i ] * ( 1 - f ) + ys[ Math.min( ys.length - 1, i + 1 ) ] * f
	);
}

/* ------------------------------ silhouettes ------------------------------ */

export const ANIMALS = SILHOUETTES;

/** Ground dwellers stand on a ridge; sky and water have their own lists. */
export const GROUND_ANIMALS = [
	'deer',
	'moose',
	'fox',
	'hare',
	'bear',
	'wolf',
	'cat',
	'dog',
	'owl',
	'horse',
	'squirrel',
	'boar',
	'ibex',
	'robin',
	'gull',
];
export const SKY_ANIMALS = [
	'eagle',
	'heron',
	'gullfly',
	'birdfly',
	'butterfly',
	'owlfly',
];
export const WATER_ANIMALS = [ 'whale', 'dolphin' ];

// Traced poses face whichever way the original artist drew them; these
// are mirrored on bake-out so the whole cast faces left by default.
const FLIPPED = new Set( [ 'wolf', 'horse', 'squirrel', 'dolphin' ] );

/**
 * Place a silhouette: unit box scaled to `size` (share of sheet
 * height), standing at `x` with its feet on the given ground y.
 *
 * @param {string} kind   Silhouette id.
 * @param {Object} at     `{ x, y, size, flip }` - y is unit ground.
 * @param {number} w      Sheet width in px.
 * @param {number} h      Sheet height in px.
 * @return {Array} One stamp (array of rings).
 */
export function silhouetteStamp( kind, { x = 0.5, y = 1, size = 0.2, flip = false }, w, h ) {
	const s = SILHOUETTES[ kind ];
	if ( ! s ) {
		return [];
	}
	const hh = size * h;
	const ww = hh * s.w;
	const mirror = FLIPPED.has( kind ) ? ! flip : flip;
	const cx = x * w;
	const base = y * h;
	return [
		s.polys.map( ( ring ) =>
			ring.map( ( [ px, py ] ) => [
				cx + ( mirror ? 0.5 - px : px - 0.5 ) * ww,
				base - ( 1 - py ) * hh,
			] )
		),
	];
}

/** A silhouette standing on the profile line. */
export function animalStamp( ys, { kind = 'deer', x = 0.5, scale = 0.22, flip = false }, w, h ) {
	return silhouetteStamp(
		kind,
		{ x, y: profileAt( ys, x ) + 0.004, size: scale, flip },
		w,
		h
	);
}

/* --------------------------------- trees -------------------------------- */

/**
 * A conifer: tapering tiers with drooping tips, built as ONE ring so
 * it cuts as one piece. Every seed shifts the tier count, the droop
 * and the slight lean.
 */
function conifer( cx, ground, hgt, r, slim = 0.42 ) {
	const tiers = 5 + Math.floor( r() * 4 );
	const lean = ( r() - 0.5 ) * hgt * 0.05;
	const trunkW = hgt * 0.035;
	const bodyTop = ground - hgt;
	const left = [];
	const right = [];
	for ( let i = 0; i <= tiers; i++ ) {
		const t = i / tiers;
		// Tier y from top down, tier half-width grows toward the base.
		const y = bodyTop + t * hgt * 0.92;
		const wHere =
			hgt * slim * Math.pow( t, 0.78 ) * ( 0.92 + r() * 0.16 );
		const x = cx + lean * ( 1 - t );
		// Each tier: out to the tip, then a small step back inwards.
		left.push( [ x - wHere, y + hgt * 0.055 ] );
		left.push( [ x - wHere * 0.55, y + hgt * 0.075 ] );
		right.push( [ x + wHere, y + hgt * 0.055 ] );
		right.push( [ x + wHere * 0.55, y + hgt * 0.075 ] );
	}
	const ring = [ [ cx + lean, bodyTop ] ];
	for ( const p of left ) {
		ring.push( p );
	}
	ring.push( [ cx - trunkW, ground - hgt * 0.02 ], [ cx - trunkW, ground ] );
	ring.push( [ cx + trunkW, ground ], [ cx + trunkW, ground - hgt * 0.02 ] );
	for ( let i = right.length - 1; i >= 0; i-- ) {
		ring.push( right[ i ] );
	}
	// One stamp holding one ring - the contract is stamps, not rings.
	return [ [ ring ] ];
}

/**
 * A broadleaf tree: tapered trunk with a fork, crown as a cluster of
 * overlapping blobs. Returns SEVERAL stamps (trunk + blobs) so they
 * union on the paper.
 */
function broadleaf( cx, ground, hgt, r, { slim = 1, birch = false } = {} ) {
	const stamps = [];
	const trunkH = hgt * ( birch ? 0.62 : 0.46 );
	const tw = hgt * ( birch ? 0.022 : 0.038 );
	const lean = ( r() - 0.5 ) * hgt * 0.06;
	const topX = cx + lean;
	const topY = ground - trunkH;
	stamps.push( [
		[
			[ cx - tw, ground ],
			[ cx - tw * 0.8, ground - trunkH * 0.5 ],
			[ topX - tw * 0.55, topY ],
			[ topX + tw * 0.55, topY ],
			[ cx + tw * 0.8, ground - trunkH * 0.5 ],
			[ cx + tw, ground ],
		],
	] );
	// Two limbs into the crown.
	for ( const dir of [ -1, 1 ] ) {
		const lx = topX + dir * hgt * 0.14;
		const ly = topY - hgt * 0.1;
		stamps.push( [
			[
				[ topX - tw * 0.5, topY + hgt * 0.04 ],
				[ lx, ly ],
				[ lx + dir * tw * 0.7, ly + hgt * 0.03 ],
				[ topX + tw * 0.5, topY + hgt * 0.06 ],
			],
		] );
	}
	// The crown is a heap of lobes on a slightly flattened dome, dense
	// enough to read as foliage rather than as a lollipop.
	const crownR = hgt * ( birch ? 0.26 : 0.42 ) * slim;
	const crownY = topY - crownR * 0.45;
	stamps.push( [ ellipse( topX, crownY, crownR * 1.02, crownR * 0.78, 34 ) ] );
	const blobs = birch ? 6 : 9 + Math.floor( r() * 4 );
	for ( let i = 0; i < blobs; i++ ) {
		// Lobes ride the upper half of the dome; the underside stays
		// open so the crown does not swallow the trunk.
		const a = Math.PI + ( ( i + 0.5 ) / blobs ) * Math.PI * 1.25 - 0.12;
		const rad = crownR * ( 0.3 + r() * 0.22 );
		stamps.push( [
			ellipse(
				topX + Math.cos( a ) * crownR * ( 0.62 + r() * 0.3 ),
				crownY + Math.sin( a ) * crownR * ( 0.5 + r() * 0.25 ),
				rad * 1.12,
				rad,
				22
			),
		] );
	}
	return stamps;
}

/** A palm: curved trunk plus drooping fronds. */
function palm( cx, ground, hgt, r ) {
	const stamps = [];
	const bend = ( 0.18 + r() * 0.2 ) * hgt * ( r() > 0.5 ? 1 : -1 );
	const tw = hgt * 0.03;
	const seg = 14;
	const leftSide = [];
	const rightSide = [];
	for ( let i = 0; i <= seg; i++ ) {
		const t = i / seg;
		const y = ground - t * hgt;
		const x = cx + bend * t * t;
		const wide = tw * ( 1.35 - t * 0.6 );
		leftSide.push( [ x - wide, y ] );
		rightSide.push( [ x + wide, y ] );
	}
	stamps.push( [ leftSide.concat( rightSide.reverse() ) ] );
	const topX = cx + bend;
	const topY = ground - hgt;
	// Fronds leave the crown upward, then bow out and down - drawn as
	// a spine that is widened symmetrically, so each frond is a leaf,
	// not a spider leg.
	const fronds = 7 + Math.floor( r() * 3 );
	for ( let i = 0; i < fronds; i++ ) {
		const spread = ( ( i + 0.5 ) / fronds - 0.5 ) * 2; // -1..1
		const side = spread < 0 ? -1 : 1;
		const swing = Math.abs( spread );
		const len = hgt * ( 0.4 + r() * 0.16 );
		const spine = ( t ) => {
			// Quadratic bezier: up and out, then down at the tip.
			const p0 = [ topX, topY ];
			const p1 = [
				topX + side * len * 0.45 * ( 0.35 + swing ),
				topY - hgt * ( 0.16 - swing * 0.09 ),
			];
			const p2 = [
				topX + side * len * ( 0.45 + swing * 0.75 ),
				topY + hgt * ( 0.06 + swing * 0.26 ),
			];
			const u = 1 - t;
			return [
				u * u * p0[ 0 ] + 2 * u * t * p1[ 0 ] + t * t * p2[ 0 ],
				u * u * p0[ 1 ] + 2 * u * t * p1[ 1 ] + t * t * p2[ 1 ],
			];
		};
		const N = 16;
		const ring = [];
		for ( let k = 0; k <= N; k++ ) {
			const t = k / N;
			const [ x, y ] = spine( t );
			ring.push( [ x, y - hgt * 0.05 * Math.sin( Math.PI * t ) ] );
		}
		for ( let k = N; k >= 0; k-- ) {
			const t = k / N;
			const [ x, y ] = spine( t );
			ring.push( [ x, y + hgt * 0.055 * Math.sin( Math.PI * t ) ] );
		}
		stamps.push( [ ring ] );
	}
	// A small crown knot ties the fronds together.
	stamps.push( [ ellipse( topX, topY + hgt * 0.01, hgt * 0.045, hgt * 0.04, 18 ) ] );
	return stamps;
}

/** A low shrub: three or four squat blobs. */
function bush( cx, ground, hgt, r ) {
	const stamps = [];
	const n = 3 + Math.floor( r() * 2 );
	for ( let i = 0; i < n; i++ ) {
		const t = ( i + 0.5 ) / n;
		stamps.push( [
			ellipse(
				cx + ( t - 0.5 ) * hgt * 1.5,
				ground - hgt * ( 0.3 + r() * 0.25 ),
				hgt * ( 0.42 + r() * 0.2 ),
				hgt * ( 0.35 + r() * 0.2 ),
				24
			),
		] );
	}
	stamps.push( [
		[
			[ cx - hgt * 0.9, ground ],
			[ cx - hgt * 0.85, ground - hgt * 0.35 ],
			[ cx + hgt * 0.85, ground - hgt * 0.35 ],
			[ cx + hgt * 0.9, ground ],
		],
	] );
	return stamps;
}

export const TREE_KINDS = [ 'conifer', 'broadleaf', 'birch', 'palm', 'bush' ];

const treeFn = {
	conifer,
	broadleaf,
	birch: ( cx, ground, hgt, r ) => broadleaf( cx, ground, hgt, r, { birch: true } ),
	palm,
	bush: ( cx, ground, hgt, r ) => bush( cx, ground, hgt * 0.5, r ),
};

/**
 * A cluster of trees around x, spread over `spread` of the width. One
 * object, many trees - so it can be picked and dragged as one thing.
 *
 * @param {Object} o  `{ species, seed, x, y, spread, count, size }`.
 * @param {number} w  Sheet width.
 * @param {number} h  Sheet height.
 * @param {Array}  ys Profile to stand on, or null for a flat line at y.
 * @return {Array} Stamps.
 */
export function treeCluster( o, w, h, ys ) {
	const make = treeFn[ o.species ] || conifer;
	const r = rng( o.seed + 31 );
	const out = [];
	const n = Math.max( 1, Math.round( o.count ) );
	for ( let i = 0; i < n; i++ ) {
		// Jittered even spacing beats pure random: no clumps, no gaps.
		const t = n === 1 ? 0.5 : ( i + 0.5 + ( r() - 0.5 ) * 0.7 ) / n;
		const x = o.x + ( t - 0.5 ) * o.spread;
		const hgt = o.size * ( 0.68 + r() * 0.7 ) * h;
		const ground = ( ys ? profileAt( ys, x ) : o.y ) * h + hgt * 0.02;
		out.push( ...make( x * w, ground, hgt, r ) );
	}
	return out;
}

/**
 * A patch of ground cover (grass, reeds, flowers, rocks) as one object.
 *
 * @param {Object} o  `{ species, seed, x, y, spread, count, size }`.
 * @param {number} w  Sheet width.
 * @param {number} h  Sheet height.
 * @param {Array}  ys Profile, or null.
 * @return {Array} Stamps.
 */
export function plantCluster( o, w, h, ys ) {
	const r = rng( o.seed + 87 );
	const out = [];
	const n = Math.max( 1, Math.round( o.count ) );
	for ( let i = 0; i < n; i++ ) {
		const t = n === 1 ? 0.5 : ( i + 0.5 + ( r() - 0.5 ) * 0.85 ) / n;
		const x = o.x + ( t - 0.5 ) * o.spread;
		const hgt = o.size * ( 0.6 + r() * 0.85 ) * h;
		const ground = ( ys ? profileAt( ys, x ) : o.y ) * h + hgt * 0.04;
		const cx = x * w;
		if ( 'reeds' === o.species ) {
			out.push( ...reedTuft( cx, ground, hgt, r ) );
		} else if ( 'flowers' === o.species ) {
			out.push( ...flowerStem( cx, ground, hgt, r ) );
		} else if ( 'rocks' === o.species ) {
			out.push( ...boulder( cx, ground, hgt, r ) );
		} else {
			out.push( ...grassTuft( cx, ground, hgt, r ) );
		}
	}
	return out;
}

/** One grass tuft: a fan of tapered blades. */
function grassTuft( cx, ground, hgt, r ) {
	const out = [];
	const blades = 3 + Math.floor( r() * 3 );
	for ( let b = 0; b < blades; b++ ) {
		const lean = ( ( b + 0.5 ) / blades - 0.5 ) * 1.7;
		const bh = hgt * ( 0.6 + r() * 0.5 );
		const base = cx + lean * hgt * 0.22;
		const wBase = Math.max( 1.2, hgt * 0.07 );
		const ring = [];
		const N = 6;
		for ( let k = 0; k <= N; k++ ) {
			const t = k / N;
			ring.push( [ base + lean * bh * 0.5 * t * t, ground - bh * t ] );
		}
		for ( let k = N; k >= 0; k-- ) {
			const t = k / N;
			ring.push( [
				base + lean * bh * 0.5 * t * t + wBase * ( 1 - t ),
				ground - bh * t,
			] );
		}
		out.push( [ ring ] );
	}
	return out;
}

/** One reed with an optional cattail head. */
function reedTuft( cx, ground, hgt, r ) {
	const out = [];
	const lean = ( r() - 0.5 ) * 0.5;
	const stalkW = Math.max( 1.4, hgt * 0.035 );
	const tip = [ cx + lean * hgt * 0.5, ground - hgt ];
	out.push( [
		[
			[ cx - stalkW, ground ],
			[ tip[ 0 ] - stalkW * 0.7, tip[ 1 ] ],
			[ tip[ 0 ] + stalkW * 0.7, tip[ 1 ] ],
			[ cx + stalkW, ground ],
		],
	] );
	if ( r() > 0.35 ) {
		out.push( [
			ellipse(
				tip[ 0 ] + lean * hgt * 0.06,
				tip[ 1 ] + hgt * 0.12,
				hgt * 0.055,
				hgt * 0.14,
				20,
				lean * 0.5
			),
		] );
	}
	return out;
}

/** One flower: stem plus a daisy or round head. */
function flowerStem( cx, ground, hgt, r ) {
	const out = [];
	const lean = ( r() - 0.5 ) * 0.6;
	const headX = cx + lean * hgt * 0.4;
	const headY = ground - hgt;
	const sw = Math.max( 1.2, hgt * 0.03 );
	out.push( [
		[
			[ cx - sw, ground ],
			[ headX - sw * 0.8, headY ],
			[ headX + sw * 0.8, headY ],
			[ cx + sw, ground ],
		],
	] );
	if ( r() > 0.5 ) {
		const petals = 5 + Math.floor( r() * 3 );
		const ring = [];
		const rad = hgt * 0.17;
		for ( let k = 0; k < petals * 2; k++ ) {
			const a = ( k / ( petals * 2 ) ) * TAU;
			const rr = k % 2 ? rad * 0.42 : rad;
			ring.push( [ headX + Math.cos( a ) * rr, headY + Math.sin( a ) * rr ] );
		}
		out.push( [ ring ] );
	} else {
		out.push( [ ellipse( headX, headY, hgt * 0.12, hgt * 0.12, 20 ) ] );
	}
	return out;
}

/** One boulder. */
function boulder( cx, ground, hgt, r ) {
	const rad = hgt * 0.55;
	const n = 9 + Math.floor( r() * 4 );
	const ring = [];
	for ( let k = 0; k < n; k++ ) {
		const a = Math.PI + ( k / ( n - 1 ) ) * Math.PI;
		const rr = rad * ( 0.72 + r() * 0.45 );
		ring.push( [
			cx + Math.cos( a ) * rr * 1.25,
			ground + Math.sin( a ) * rr * 0.85,
		] );
	}
	ring.push( [ cx + rad * 1.3, ground ], [ cx - rad * 1.3, ground ] );
	return [ [ ring ] ];
}

/**
 * A soft mound that carries a standing object down to the horizon, so
 * nothing ever floats on a flat ground sheet.
 *
 * @param {Object} bb     Object bbox in px.
 * @param {number} ground Horizon y in px.
 * @param {number} seed   For a little asymmetry.
 * @return {Array} Stamps.
 */
export function moundStamp( bb, ground, seed ) {
	const r = rng( seed + 401 );
	const cx = ( bb.x0 + bb.x1 ) / 2;
	const halfW = Math.max( ( bb.x1 - bb.x0 ) * 1.5, ( ground - bb.y1 ) * 1.6 );
	const top = bb.y1 - Math.max( 2, ( ground - bb.y1 ) * 0.08 );
	const ring = [];
	const N = 28;
	for ( let i = 0; i <= N; i++ ) {
		const t = i / N;
		const x = cx - halfW + t * halfW * 2;
		// A wide, low cosine hill with a touch of asymmetry.
		const bump = Math.pow( Math.cos( ( t - 0.5 ) * Math.PI ), 1.6 );
		const skew = 1 + ( r() - 0.5 ) * 0.06;
		ring.push( [ x, ground - ( ground - top ) * bump * skew ] );
	}
	ring.push( [ cx + halfW, ground + 4 ], [ cx - halfW, ground + 4 ] );
	return [ [ ring ] ];
}

/**
 * A cumulus cloud as its own object: overlapping lobes on a flat base.
 * `wide` spreads the lobes across the whole sheet (the cloud bank).
 *
 * @param {Object} o `{ seed, x, y, size, wide }`.
 * @param {number} w Sheet width.
 * @param {number} h Sheet height.
 * @return {Array} Stamps.
 */
export function cloudCluster( { seed = 1, x = 0.5, y = 0.25, size = 0.3, wide = false }, w, h ) {
	const r = rng( seed + 211 );
	const stamps = [];
	const groups = wide ? 5 + Math.floor( r() * 3 ) : 1;
	const scale = h * ( wide ? 0.05 + size * 0.075 : size * 0.22 );
	for ( let c = 0; c < groups; c++ ) {
		const cx = wide
			? ( ( c + 0.5 + ( r() - 0.5 ) * 0.7 ) / groups ) * w
			: x * w;
		const cy = y * h;
		const lobes = 4 + Math.floor( r() * 4 );
		const sc = scale * ( wide ? 0.85 + r() * 0.5 : 1 );
		for ( let i = 0; i < lobes; i++ ) {
			const t = ( i + 0.5 ) / lobes;
			const tall = Math.sin( Math.PI * t );
			const rad = sc * ( 0.55 + tall * 0.75 ) * ( 0.85 + r() * 0.3 );
			stamps.push( [
				ellipse(
					cx + ( t - 0.5 ) * sc * 3.1,
					cy - rad * 0.15 + sc * 0.25,
					rad * 1.15,
					rad,
					26
				),
			] );
		}
		if ( ! wide ) {
			// A free cloud needs its own flat underside.
			stamps.push( [
				[
					[ cx - sc * 1.8, cy + sc * 0.2 ],
					[ cx + sc * 1.8, cy + sc * 0.2 ],
					[ cx + sc * 1.8, cy + sc * 0.5 ],
					[ cx - sc * 1.8, cy + sc * 0.5 ],
				],
			] );
		}
	}
	return stamps;
}

/* -------------------------------- punchers ------------------------------ */

const circlePoly = ( cx, cy, r, n = 64 ) => {
	const out = [];
	for ( let i = 0; i < n; i++ ) {
		const a = ( i / n ) * TAU;
		out.push( [ cx + Math.cos( a ) * r, cy + Math.sin( a ) * r ] );
	}
	return out;
};

/** Full moon, or a crescent when `phase` cuts into it. */
export function moonPunch( { x = 0.78, y = 0.2, size = 0.13, crescent = false }, w, h ) {
	const cx = x * w;
	const cy = y * h;
	const r = ( size * h ) / 2;
	if ( ! crescent ) {
		return [ [ circlePoly( cx, cy, r, 80 ) ] ];
	}
	// Crescent as one ring: outer arc out, inner arc back.
	const off = r * 0.55;
	const ring = [];
	for ( let i = 0; i <= 60; i++ ) {
		const a = -Math.PI / 2 + ( i / 60 ) * Math.PI;
		ring.push( [ cx + Math.cos( a ) * r, cy + Math.sin( a ) * r ] );
	}
	for ( let i = 60; i >= 0; i-- ) {
		const a = -Math.PI / 2 + ( i / 60 ) * Math.PI;
		ring.push( [
			cx + off + Math.cos( a ) * r * 0.92,
			cy + Math.sin( a ) * r * 0.92,
		] );
	}
	return [ [ ring ] ];
}

/** A sun with straight rays. */
export function sunPunch( { x = 0.5, y = 0.24, size = 0.16, rays = 12 }, w, h ) {
	const cx = x * w;
	const cy = y * h;
	const r = ( size * h ) / 2;
	const out = [ [ circlePoly( cx, cy, r, 72 ) ] ];
	for ( let i = 0; i < rays; i++ ) {
		const a = ( i / rays ) * TAU;
		const inner = r * 1.28;
		const outer = r * ( 1.75 + ( i % 2 ? 0 : 0.25 ) );
		const wide = r * 0.09;
		const nx = -Math.sin( a ) * wide;
		const ny = Math.cos( a ) * wide;
		out.push( [
			[
				[ cx + Math.cos( a ) * inner + nx, cy + Math.sin( a ) * inner + ny ],
				[ cx + Math.cos( a ) * outer + nx * 0.4, cy + Math.sin( a ) * outer + ny * 0.4 ],
				[ cx + Math.cos( a ) * outer - nx * 0.4, cy + Math.sin( a ) * outer - ny * 0.4 ],
				[ cx + Math.cos( a ) * inner - nx, cy + Math.sin( a ) * inner - ny ],
			],
		] );
	}
	return out;
}

/**
 * A flock as ONE object: real bird silhouettes scattered around x/y.
 *
 * @param {Object} o `{ seed, species, x, y, spread, count, size }`.
 * @param {number} w Sheet width.
 * @param {number} h Sheet height.
 * @return {Array} Stamps.
 */
export function flockStamps( o, w, h ) {
	const r = rng( o.seed + 3 );
	const out = [];
	const n = Math.max( 1, Math.round( o.count ) );
	for ( let i = 0; i < n; i++ ) {
		const x = o.x + ( r() - 0.5 ) * o.spread;
		const y = o.y + ( r() - 0.5 ) * o.spread * 0.42;
		const size = o.size * ( 0.7 + r() * 0.7 );
		out.push(
			...silhouetteStamp(
				o.species,
				{ x, y: y + size / 2, size, flip: r() > 0.5 },
				w,
				h
			)
		);
	}
	return out;
}

/* -------------------------------- frames -------------------------------- */

const heartPoly = ( cx, cy, s ) => {
	const out = [];
	for ( let i = 0; i < 96; i++ ) {
		const t = ( i / 96 ) * TAU;
		// Classic parametric heart, y flipped into screen space.
		const x = 16 * Math.pow( Math.sin( t ), 3 );
		const y =
			13 * Math.cos( t ) -
			5 * Math.cos( 2 * t ) -
			2 * Math.cos( 3 * t ) -
			Math.cos( 4 * t );
		out.push( [ cx + ( x / 17 ) * s, cy - ( y / 17 ) * s ] );
	}
	return out;
};

/**
 * The frame window polygon (the hole in the frontmost frame sheet).
 *
 * @return {Array|null} Polygons to punch, or null for frame 'none'.
 */
export function frameWindow( kind, w, h, inset = 0.08 ) {
	const cx = w / 2;
	const cy = h / 2;
	const rw = w * ( 0.5 - inset );
	const rh = h * ( 0.5 - inset );
	if ( 'circle' === kind ) {
		const r = Math.min( rw, rh );
		return [ circlePoly( cx, cy, r, 128 ) ];
	}
	if ( 'oval' === kind ) {
		return [
			circlePoly( 0, 0, 1, 128 ).map( ( [ x, y ] ) => [
				cx + x * rw,
				cy + y * rh,
			] ),
		];
	}
	if ( 'heart' === kind ) {
		return [
			heartPoly( cx, cy + Math.min( rw, rh ) * 0.08, Math.min( rw, rh ) * 1.12 ),
		];
	}
	if ( 'arch' === kind ) {
		const r = rw;
		const top = cy - rh;
		const poly = [];
		for ( let i = 0; i <= 64; i++ ) {
			const a = Math.PI + ( i / 64 ) * Math.PI;
			poly.push( [ cx + Math.cos( a ) * r, top + r + Math.sin( a ) * r ] );
		}
		poly.push( [ cx + r, cy + rh ], [ cx - r, cy + rh ] );
		return [ poly ];
	}
	if ( 'hex' === kind ) {
		const r = Math.min( rw, rh ) * 1.06;
		const poly = [];
		for ( let i = 0; i < 6; i++ ) {
			const a = -Math.PI / 2 + ( i / 6 ) * TAU;
			poly.push( [ cx + Math.cos( a ) * r, cy + Math.sin( a ) * r ] );
		}
		return [ poly ];
	}
	return null;
}

/* ------------------------------ corner leaves ---------------------------- */

/**
 * Corner foliage: a branch growing in from a corner with leaf clusters
 * along it - the signature framing device of layered papercut art. It
 * stays attached to its corner, so the sheet is one piece by design.
 *
 * @param {Object} opts `{ seed, corner: 'tl'|'tr'|'bl'|'br', reach, leaf }`.
 * @param {number} w    Sheet width.
 * @param {number} h    Sheet height.
 * @return {Array} Stamps.
 */
export function branchStamps( { seed = 1, corner = 'tl', reach = 0.55, leaf = 0.5 }, w, h ) {
	const r = rng( seed + 131 );
	const right = 'tr' === corner || 'br' === corner;
	const bottom = 'bl' === corner || 'br' === corner;
	const ox = right ? w : 0;
	const oy = bottom ? h : 0;
	const sx = right ? -1 : 1;
	const sy = bottom ? -1 : 1;
	const len = reach * Math.hypot( w, h ) * 0.62;
	const stamps = [];
	// The main limb: a bezier from the corner, thick at the root.
	const p0 = [ ox - sx * w * 0.04, oy - sy * h * 0.04 ];
	const p1 = [ ox + sx * len * 0.5, oy + sy * len * 0.12 ];
	const p2 = [ ox + sx * len * 0.92, oy + sy * len * 0.42 ];
	const at = ( t ) => {
		const u = 1 - t;
		return [
			u * u * p0[ 0 ] + 2 * u * t * p1[ 0 ] + t * t * p2[ 0 ],
			u * u * p0[ 1 ] + 2 * u * t * p1[ 1 ] + t * t * p2[ 1 ],
		];
	};
	const thick = h * 0.028;
	const ring = [];
	const N = 20;
	for ( let k = 0; k <= N; k++ ) {
		const t = k / N;
		const [ x, y ] = at( t );
		ring.push( [ x, y - thick * ( 1 - t * 0.75 ) ] );
	}
	for ( let k = N; k >= 0; k-- ) {
		const t = k / N;
		const [ x, y ] = at( t );
		ring.push( [ x, y + thick * ( 1 - t * 0.75 ) ] );
	}
	stamps.push( [ ring ] );
	// Twigs with leaf clusters, alternating along the limb.
	const twigs = 5 + Math.floor( r() * 4 );
	for ( let i = 0; i < twigs; i++ ) {
		const t = 0.18 + ( i / twigs ) * 0.78;
		const [ bx, by ] = at( t );
		const dir = i % 2 ? 1 : -1;
		const tl = len * ( 0.13 + r() * 0.12 );
		const ang =
			Math.atan2( sy * 0.5, sx ) + dir * ( 0.6 + r() * 0.5 ) * ( bottom ? -1 : 1 );
		const tx = bx + Math.cos( ang ) * tl;
		const ty = by + Math.sin( ang ) * tl;
		stamps.push( [
			[
				[ bx, by - thick * 0.45 ],
				[ tx, ty - thick * 0.2 ],
				[ tx, ty + thick * 0.2 ],
				[ bx, by + thick * 0.45 ],
			],
		] );
		// Leaves: pointed ovals along the twig.
		const leaves = 3 + Math.floor( r() * 3 );
		for ( let k = 0; k < leaves; k++ ) {
			const lt = 0.35 + ( k / leaves ) * 0.75;
			const lx = bx + ( tx - bx ) * lt;
			const ly = by + ( ty - by ) * lt;
			const lsz = h * leaf * 0.055 * ( 0.7 + r() * 0.6 );
			const la = ang + ( k % 2 ? 0.9 : -0.9 );
			const leafRing = [];
			for ( let s = 0; s <= 14; s++ ) {
				const u = s / 14;
				const wdt = Math.sin( Math.PI * u ) * lsz * 0.42;
				leafRing.push( [
					lx + Math.cos( la ) * lsz * u - Math.sin( la ) * wdt,
					ly + Math.sin( la ) * lsz * u + Math.cos( la ) * wdt,
				] );
			}
			for ( let s = 14; s >= 0; s-- ) {
				const u = s / 14;
				const wdt = Math.sin( Math.PI * u ) * lsz * 0.42;
				leafRing.push( [
					lx + Math.cos( la ) * lsz * u + Math.sin( la ) * wdt,
					ly + Math.sin( la ) * lsz * u - Math.cos( la ) * wdt,
				] );
			}
			stamps.push( [ leafRing ] );
		}
	}
	return stamps;
}
