<?php
/**
 * System prompt for the `design_markup` action (Design Markup, stage 2a).
 *
 * The model does not fill a template here: it composes a whole design in
 * Design Markup - concept, tokens, grid, areas, elements - and the compiler
 * in src/lib/design-markup/ turns that into real, editable layers.
 *
 * Chapters (design spec 8.3): role, the rules of a VALID design (stage 2b:
 * the nine things that decide accepted vs. rejected), the language with one
 * example per element kind, the capability catalog rendered from the
 * GENERATED data-design-markup-catalog.json, design rules, diversity rules,
 * a skeleton of the smallest complete design, three worked examples from
 * data-design-markup-examples.json, and the request's own context. Only the
 * last chapter changes per request, so everything above it is a stable
 * prefix - that is what prompt caching bills less for.
 *
 * The catalog, schema and examples are generated by
 * tools/design-markup/export-catalog.mjs out of the compiler's own catalog.
 * Never hand-edit them, and never name a vocabulary here that is not in
 * them: cleanMarkup() drops unknown values silently, so a prompt that
 * promises more than the language has produces designs nobody ordered.
 *
 * @package WPImageEditor
 */

namespace WPImageEditor;

defined( 'ABSPATH' ) || exit;

if ( ! function_exists( __NAMESPACE__ . '\\design_markup_data' ) ) {
	/**
	 * One of the generated Design Markup data files, decoded and cached for
	 * the request.
	 *
	 * @param string $name File suffix: catalog|schema|examples.
	 * @return array Decoded data, empty array when the file is missing.
	 */
	function design_markup_data( $name ) {
		static $cache = array();
		if ( isset( $cache[ $name ] ) ) {
			return $cache[ $name ];
		}
		$file = WPIE_DIR . 'includes/data-design-markup-' . $name . '.json';
		$raw  = is_readable( $file ) ? file_get_contents( $file ) : ''; // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- local plugin file, no HTTP.
		$data = json_decode( (string) $raw, true );
		$cache[ $name ] = is_array( $data ) ? $data : array();
		return $cache[ $name ];
	}
}

if ( ! function_exists( __NAMESPACE__ . '\\design_markup_format_name' ) ) {
	/**
	 * A human format name for a canvas, so the model knows what it is
	 * designing for before it reads the pixel numbers.
	 *
	 * @param int $w Width in px.
	 * @param int $h Height in px.
	 * @return string Format name.
	 */
	function design_markup_format_name( $w, $h ) {
		$w = max( 1, (int) $w );
		$h = max( 1, (int) $h );
		$r = $w / $h;
		if ( $r > 0.95 && $r < 1.05 ) {
			return 'square social post';
		}
		if ( $r < 0.62 ) {
			return 'vertical story / reel (9:16)';
		}
		if ( $r < 0.95 ) {
			return 'portrait social post (4:5)';
		}
		if ( $r < 1.5 ) {
			return 'landscape post (4:3)';
		}
		if ( $r < 2.05 ) {
			return 'wide banner / link card (16:9 to 1.91:1)';
		}
		return 'extra-wide banner';
	}
}

if ( ! function_exists( __NAMESPACE__ . '\\design_markup_catalog_text' ) ) {
	/**
	 * The capability catalog as prompt text: every vocabulary the compiler
	 * accepts, and nothing else.
	 *
	 * @return string Catalog chapter.
	 */
	function design_markup_catalog_text() {
		$c = design_markup_data( 'catalog' );
		if ( ! $c ) {
			return '';
		}
		$join = static function ( $list ) {
			return implode( ', ', (array) $list );
		};
		// Enumerations read as pipes, lists as commas: "from: t, b, l, r,
		// strength" is a sentence in which nobody can see where the choice
		// ends and the next field starts.
		$pipe = static function ( $list ) {
			return implode( ' | ', (array) $list );
		};
		$pairs = array();
		foreach ( (array) ( $c['tokens']['typePairings'] ?? array() ) as $p ) {
			$pairs[] = sprintf(
				'["%s", %s] + ["%s", %s]%s',
				$p['hero'][0],
				$p['hero'][1],
				$p['support'][0],
				$p['support'][1],
				! empty( $p['shipped'] ) ? '' : ' (downloaded, prefer the others)'
			);
		}
		$treats = array();
		foreach ( (array) ( $c['photo']['treats'] ?? array() ) as $id => $t ) {
			$keys     = array_keys( (array) ( $t['params'] ?? array() ) );
			$treats[] = $id . ( $keys ? ' (' . $join( $keys ) . ')' : '' );
		}
		$components = array();
		foreach ( (array) ( $c['component'] ?? array() ) as $type => $props ) {
			$components[] = $type . ' (props: ' . $join( array_keys( (array) $props ) ) . ')';
		}
		$bound = array();
		foreach ( (array) ( $c['text']['boundMaxLines'] ?? array() ) as $voice => $lines ) {
			$bound[] = $voice . ' ' . $lines;
		}
		$lines = array(
			'CAPABILITY CATALOG (generated from the compiler; anything not listed here is dropped silently)',
			'',
			'element kinds: ' . $pipe( $c['element']['kinds'] ?? array() ),
			'element role: ' . $pipe( $c['element']['roles'] ?? array() ) . ' - role steers verification and repair, not looks.',
			'blend: ' . $pipe( $c['element']['blends'] ?? array() ),
			'layer styles (element.styles): ' . $join( $c['element']['layerStyles'] ?? array() ) . ' - each one is an object with the fields ' . $join( $c['element']['layerStyleFields'] ?? array() ) . ' (color takes a palette role, opacity 0..1, the rest are pixels or degrees).',
			'rotation: free up to ' . (int) ( $c['element']['rot']['free'] ?? 15 ) . ' degrees, up to ' . (int) ( $c['element']['rot']['max'] ?? 45 ) . ' only with concept.loud >= 4; groups and components cannot rotate.',
			'',
			'concept.mood: ' . $pipe( $c['concept']['moods'] ?? array() ),
			'concept.imagery: ' . $pipe( $c['concept']['imagery'] ?? array() ),
			'concept.loud: ' . (int) ( $c['concept']['loud']['min'] ?? 1 ) . '..' . (int) ( $c['concept']['loud']['max'] ?? 5 ),
			'',
			'tokens.palette.source: ' . $pipe( $c['tokens']['paletteSources'] ?? array() ) . '; roles: ' . $join( $c['tokens']['paletteRoles'] ?? array() ) . '. Every color field takes a ROLE NAME or a #rrggbb hex; roles are the good answer.',
			'tokens.type.pairing (hero + support, family and weight): ' . implode( '; ', $pairs ),
			'tokens.type.scale: ' . ( $c['tokens']['typeScale']['min'] ?? 1.1 ) . '..' . ( $c['tokens']['typeScale']['max'] ?? 1.6 ),
			'tokens.space: margin, gap, radius - fractions of the shorter canvas edge, 0..0.2.',
			'',
			'grid: cols/rows 1..24, margin and gutter 0..0.2 of the shorter edge. areas: [{ id, cell: [c0, r0, c1, r1] }], end-exclusive.',
			'place, exactly one of: ' . $pipe( $c['place']['forms'] ?? array() ) . '. anchor: ' . $pipe( $c['place']['anchors'] ?? array() ) . '. rel.side: ' . $pipe( $c['place']['sides'] ?? array() ) . '; rel.gap in multiples of tokens.space.gap (0..6).',
			'size (required with area and rel): [w, h], each a fraction of the canvas edge or one of ' . $pipe( $c['place']['sizeKeywords'] ?? array() ) . '. "auto" only for text and components.',
			'',
			'background.style: ' . $pipe( $c['background']['styles'] ?? array() ) . '; direction: ' . $pipe( $c['background']['directions'] ?? array() ) . '; colors: a list of palette roles; seed: any integer; grain: 0..1.',
			'photo.fit: ' . $pipe( $c['photo']['fits'] ?? array() ) . '; instance: ' . $pipe( $c['photo']['instances'] ?? array() ) . '; focus: [x, y] 0..1; scrim: { color, from: ' . $pipe( $c['photo']['scrimFrom'] ?? array() ) . ', strength 0..1, height 0..1 }.',
			'photo.treat (each entry is { "fx": <name>, <param>: <value> }): ' . $join( $treats ),
			'photo.maskShape: { family, params } - a clipping shape from the shape families below.',
			'text.voice: ' . $pipe( $c['text']['voices'] ?? array() ) . '; fit: ' . $pipe( $c['text']['fits'] ?? array() ) . '; align: ' . $pipe( $c['text']['aligns'] ?? array() ) . '; lines: ' . (int) ( $c['text']['lines']['min'] ?? 1 ) . '..' . (int) ( $c['text']['lines']['max'] ?? 6 ) . '; upper: true forces caps.',
			'text.emph: { rule: ' . $pipe( $c['text']['emphRules'] ?? array() ) . '; word: only with rule "word"; style: ' . $pipe( $c['text']['emphStyles'] ?? array() ) . ' }. text.fill and text.chip take a palette role.',
			'shape.family: ' . $join( array_keys( (array) ( $c['shape']['modelFamilies'] ?? array() ) ) ),
			'shape: params (the dials of the chosen family, see SHAPE DIALS below), fill, stroke, strokeW 0..0.05, corner 0..1.',
			'component.type: ' . $join( $components ),
			'group.stack: { dir: ' . $pipe( $c['group']['stackDirs'] ?? array() ) . '; gap in multiples of space.gap; align: ' . $pipe( $c['group']['stackAligns'] ?? array() ) . '; justify: the same three }.',
			'',
			'assets[]: { id; kind: ' . $pipe( $c['assets']['kinds'] ?? array() ) . '; query; orientation: ' . $pipe( $c['assets']['orientations'] ?? array() ) . ' }. Use kind "stock" with a literal 2-5 word search phrase; a photo element points at it with "asset": "<id>".',
			'bindings for text and components: ' . $join( $c['bindings']['text'] ?? array() ),
			'bindings for photo (then the photo has no asset): ' . $join( $c['bindings']['image'] ?? array() ),
			'a bound text is measured with the real post value, and its box is capped per voice: ' . $join( $bound ) . ' lines.',
			'',
			'limits: ' . (int) ( $c['limits']['elements'] ?? 24 ) . ' elements, ' . (int) ( $c['limits']['photos'] ?? 3 ) . ' photos, ' . (int) ( $c['limits']['texts'] ?? 6 ) . ' texts, ' . (int) ( $c['limits']['heroes'] ?? 2 ) . ' hero texts, group depth ' . (int) ( $c['limits']['depth'] ?? 3 ) . ', ' . (int) ( $c['limits']['layers'] ?? 60 ) . ' built layers.',
		);
		// The dials of each family, one line each. They used to be in the
		// response schema as 160 named numbers - and Gemini refused the
		// whole schema for it ("Request contains an invalid argument").
		// A schema is a form; a vocabulary belongs in the prompt.
		$families = (array) ( $c['shape']['modelFamilies'] ?? array() );
		if ( $families ) {
			$lines[] = '';
			$lines[] = 'SHAPE DIALS (shape.params and photo.maskShape.params) - the dials each family understands, most useful first. Numbers only; a dial that does not belong to the family is ignored, and every dial has a sane default, so set one only when you mean it.';
			foreach ( $families as $family => $dials ) {
				$lines[] = '  ' . $family . ': ' . ( $dials ? $join( $dials ) : 'no dials (use corner and strokeW)' );
			}
		}
		return implode( "\n", $lines );
	}
}

if ( ! function_exists( __NAMESPACE__ . '\\design_markup_examples_text' ) ) {
	/**
	 * The worked examples: three markups that compile, each with the one
	 * sentence that says which decision it teaches.
	 *
	 * @return string Examples chapter.
	 */
	function design_markup_examples_text() {
		$out = array( 'WORKED EXAMPLES - three complete designs that compile. Learn the DECISIONS, do not copy the layouts.' );
		foreach ( design_markup_data( 'examples' ) as $example ) {
			$out[] = '';
			$out[] = '# ' . (string) ( $example['name'] ?? '' ) . ' - ' . (string) ( $example['why'] ?? '' );
			$out[] = wp_json_encode( $example['markup'] ?? array(), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );
		}
		return implode( "\n", $out );
	}
}

if ( ! function_exists( __NAMESPACE__ . '\\design_markup_prompt' ) ) {
	/**
	 * The full system prompt for one design_markup request.
	 *
	 * @param array $ctx {
	 *     Request context.
	 *
	 *     @type int      $w        Canvas width in px.
	 *     @type int      $h        Canvas height in px.
	 *     @type int      $k        How many designs to return.
	 *     @type string   $lang     Language of the copy (locale or name).
	 *     @type string[] $colors   Brand colors (#rrggbb).
	 *     @type string[] $fonts    Brand font families.
	 *     @type string   $blurb    Brand/company context sentence.
	 *     @type string   $product  Product or context details.
	 *     @type string[] $bindings Binding ids that MUST each sit on exactly one element.
	 *     @type bool     $image    Whether a reference image is attached.
	 * }
	 * @return string
	 */
	function design_markup_prompt( array $ctx ) {
		$w = max( 16, (int) ( $ctx['w'] ?? 1080 ) );
		$h = max( 16, (int) ( $ctx['h'] ?? 1080 ) );
		$k = max( 1, (int) ( $ctx['k'] ?? 1 ) );

		$role = <<<'TXT'
You are an art director and typographer. You do not fill a template: you COMPOSE a finished design in Design Markup, a small JSON language that this editor compiles into real, editable layers (backgrounds, photos with effects, live text, vector shapes, components, groups).

Everything you write is honest instruction, never pixels-on-faith: the compiler measures every text with the real font, solves the layout, checks contrast, overflow, overlap and margins, and REJECTS a design that does not hold. Design so it holds.
TXT;

		// The rules that decide accepted vs. rejected, before any taste
		// question. They stand near the top because the first real run
		// (eight briefs, eight rejections) failed on exactly these: not one
		// element carried a "place", most texts had no "content", two
		// designs named a photo asset they never declared.
		$valid = <<<'TXT'
RULES OF A VALID DESIGN - a design that breaks one of these is thrown away before anyone sees it:

1. EVERY element carries "place". Top level: "place": { "area": "<area id>", "anchor": "<anchor>", "size": [w, h] } or "place": { "rect": [x, y, w, h] } or "place": { "rel": { "to": "<id>", "side": "below", "gap": 1 }, "anchor": "l", "size": [w, h] } or, for a background or full-bleed photo, "place": { "cover": true }. For a child of a group (it has "parent") the PLACE holds only a size: "place": { "size": ["fill", "auto"] } - the group decides where it sits. That is about the place and nothing else: a child writes "content", "voice", "emph", "fill", "chip", "upper", "align", "bind" and everything else exactly like any other element. A text without "content" is invalid, child or not. "area" and "rel" without a "size" are rejected. Without "place" everything lands on top of everything else.
2. Every photo names an asset that EXISTS in "assets": { "id": "<same id>", "kind": "stock", "query": "<2 to 4 concrete words>", "orientation": "<landscape|portrait|square>" }. No stock idea? Then "kind": "placeholder". A photo pointing at an undeclared asset is rejected.
3. Ids are short, lowercase and UNIQUE across the whole design ("bg", "shot", "title", "sub", "cta"). A repeated id is rejected.
4. 6 to 12 elements. Fewer is a sketch, more is a collage; the hard ceiling is 24.
5. Every text has real "content" - the words that will be painted, in the requested language. Never "", never "Text", never lorem ipsum. The hero text also has an "emph" (one emphasised word or phrase, not a decorated line).
6. A button, a chip or a scrim is a component: "kind": "component" plus "type" and "props" ({ "label": "..." } for button and chip). Never a shape with a text on top, and never a component without props - it would paint its default label.
7. A shape that sits under or behind a text is decor for that text: "role": "decor" plus "for": "<the text's id>". Without "for" the overlap check calls it a collision.
8. "canvas" repeats the requested width and height exactly.
9. Write every visible word in the requested language, including labels on buttons and chips.
10. A rect is a wish, the safe margin is the law. Everything except a `cover` photo and a `role: "frame"` decor is kept inside `grid.margin` (typically 0.06) - the compiler shrinks whatever sticks out. So a useful `rect` runs from 0.06 to 0.94: `[0.06, 0.06, 0.88, 0.3]`, never `[0, 0, 1, 0.3]`.
11. Texts that belong together go into ONE `group` with a `stack` - eyebrow, headline, subline, button on one rhythm. Two texts with their own `rect` end up on top of each other; a stack cannot.
12. `for` names an EXISTING element id, and it is the text the decor sits under. A `for` that points nowhere is dropped, and then the shape is just in the way.
13. Text on top of a photo needs a `scrim` on that photo (from the side the text sits on) or a `treat` that darkens or lightens it. Contrast is measured at the glyphs, and a headline over an untreated photo loses that measurement. The compiler NEVER paints a bar behind a text to save it - it recolors the text, and if that is not enough it darkens the photo's own scrim; over anything else the design is simply rejected. So make the ground readable yourself: put copy on the background or on a solid area, or over the calm part of a scrimmed photo, and pick a `fill` that carries - "onAccent" on an accent, "ink" on bg or surface, "surface" or a light hex on a dark photo.
14. Hierarchy comes from `voice` (hero, sub, detail, eyebrow), not from quantity. Three well-sized texts read; six small ones are noise, and small ones fail the minimum size.
TXT;

		$language = <<<'TXT'
THE LANGUAGE

Root: { "v": 1, "name": "two words", "concept": { "idea": "one sentence describing the picture you intend", "mood": <mood>, "loud": 1..5, "imagery": <imagery> }, "canvas": { "w": <given>, "h": <given> }, "tokens": { "palette": {...}, "type": {...}, "space": {...} }, "grid": { "cols": 12, "rows": 12, "margin": 0.06, "gutter": 0.02 }, "areas": [...], "assets": [...], "elements": [...] }

"elements" is a FLAT list in z-order (first painted first). A child of a group carries "parent": "<group id>", and its "place" holds only a size - every other field is written exactly as on a top-level element. Numbers are fractions of a canvas edge, never pixels.

One compact example per element kind:

background: { "id": "bg", "kind": "background", "style": "mesh", "colors": ["bg", "surface", "accent2"], "seed": 11, "grain": 0.15, "place": { "cover": true } }
photo:      { "id": "shot", "kind": "photo", "asset": "a1", "role": "hero", "place": { "area": "hero", "anchor": "t", "size": [0.8, "fill"] }, "fit": "cover", "focus": [0.5, 0.4], "treat": [ { "fx": "duotone", "shadow": "bg", "highlight": "accent2" } ], "maskShape": { "family": "arch", "params": {} }, "scrim": { "color": "bg", "from": "b", "strength": 0.8, "height": 0.6 } }
text:       { "id": "title", "kind": "text", "voice": "hero", "content": "Two weeks of long light", "lines": 3, "fit": "fluid", "align": "left", "fill": "ink", "emph": { "rule": "salient", "style": "accent" }, "place": { "area": "copy", "anchor": "bl", "size": ["fill", "auto"] } }
shape:      { "id": "burst", "kind": "shape", "role": "decor", "for": "stat", "family": "burst", "params": {}, "fill": "accent2", "rot": 12, "place": { "area": "left", "anchor": "tl", "size": [0.42, 0.38] } }
component:  { "id": "cta", "kind": "component", "type": "button", "props": { "label": "Read the story", "pill": true, "arrow": true, "maxW": "fill" }, "place": { "rel": { "to": "title", "side": "below", "gap": 1.5 }, "anchor": "l", "size": ["auto", "auto"] } }
group:      { "id": "stack", "kind": "group", "role": "hero", "stack": { "dir": "col", "gap": 1, "align": "start", "justify": "end" }, "place": { "area": "copy", "size": ["fill", "fill"] } }
group child:{ "id": "eyebrow", "kind": "text", "parent": "stack", "voice": "eyebrow", "content": "New drop", "upper": true, "chip": "accent", "fill": "onAccent", "place": { "size": [0.3, "auto"] } }
area:       { "id": "copy", "cell": [0, 4, 9, 12] }
asset:      { "id": "a1", "kind": "stock", "query": "coffee cup morning light window", "orientation": "portrait" }
binding:    a text with "bind": { "id": "post.title", "fit": "fluid" }, or a photo with "bind": { "id": "post.featured" } and NO asset.
TXT;

		$rules = <<<'TXT'
DESIGN RULES

1. ONE idea per design. Write it into concept.idea first, then build only what serves it. A design that says three things says none.
2. Hierarchy: exactly one element carries the eye (role "hero"). Everything else is support or decor. Two hero texts at most, and only when they are a pair.
3. Contrast is checked at the glyphs, not at your intention: light ink on a dark ground or the other way round. Over a photo, put a scrim under the text (photo.scrim, or a component of type "scrim") or the design is rejected.
4. A photo is material, not wallpaper: treat it (duotone in the palette's own roles, halftone, grain, blur, vignette), mask it into a shape (maskShape), or crop it into an area with a deliberate focus. Full-bleed and untouched is the boring answer.
5. Backgrounds carry the mood: mesh, organic, geo, poly, topo, rings, halftone and confetti are generated with a seed - a solid or a gradient is a decision, not a default.
6. Text: use fit "fluid" for headlines and let the box set the size; set "lines" to the most you would accept. Give the headline ONE emphasis (emph) instead of decorating every word. Eyebrows and CTAs are one line.
7. Components (button, chip, scrim) are finished parts - use them instead of building a button out of a shape plus a text.
8. Group what belongs together: a col stack with a gap keeps eyebrow, headline, subline and button on one rhythm and survives a longer post title. A stack child's "place" carries only its size ("place": { "size": ["fill", "auto"] }); everything that makes it a text - the copy above all - it writes itself.
9. Decoration that sits under or behind a text needs "for": "<text id>" and role "decor" - that is what allows the overlap. Without it the check calls it a collision.
10. Everything lives inside grid.margin. Only a "cover" background, a full-bleed photo and a frame may touch the canvas edge.
11. Bindings: a required binding id must sit on EXACTLY ONE element, and its text is then the real post value - write "content" as a realistic sample of the same length, never "Your title here".
12. Write real copy in the requested language: specific, short, human. No lorem ipsum, no placeholders, no invented facts about the brand.
TXT;

		$diversity = <<<'TXT'
DIVERSITY

Decide the CONCEPT first (what does the picture do?), then the layout that serves it. Never start from a layout you already like.

The forbidden default is: a flat background, a headline in the middle, a button below it, nothing else. If your design would look like that, throw it away.

Across the designs you return, deliberately vary: the background style, the photo treatment (or the decision to use none), the type pairing, the layout family (full-bleed hero, split, stacked editorial, poster with a frame, oversized number, masked photo with copy below), the mood and the loudness. Two designs that differ only in wording are one design.
TXT;

		// The shortest possible complete design, with the place on every
		// element and the asset it points at. It stands directly before the
		// three worked examples: those teach the decisions, this one teaches
		// the SHAPE of an answer that is not thrown away.
		$skeleton = <<<'TXT'
SKELETON - the smallest design that holds. The // notes are for you; never write them into your answer.

{
  "v": 1,
  "name": "Morning Loaf",
  "concept": { "idea": "A warm photo of bread carries a single line of copy", "mood": "earthy", "loud": 2, "imagery": "photo-hero" },
  "canvas": { "w": 1080, "h": 1080 },                          // exactly the requested size
  "tokens": { "palette": { "source": "intent", "intent": "earthy" }, "type": { "pairing": { "hero": ["Playfair Display", 700], "support": ["Inter", 400] }, "scale": 1.3 }, "space": { "margin": 0.07, "gap": 0.02, "radius": 0.02 } },
  "grid": { "cols": 12, "rows": 12, "margin": 0.07, "gutter": 0.02 },
  "areas": [ { "id": "copy", "cell": [1, 7, 11, 11] } ],       // end-exclusive cells
  "assets": [ { "id": "loaf", "kind": "stock", "query": "sourdough bread bakery", "orientation": "square" } ],
  "elements": [
    { "id": "bg", "kind": "background", "style": "solid", "colors": ["bg"], "seed": 7, "grain": 0.08, "place": { "cover": true } },
    { "id": "shot", "kind": "photo", "asset": "loaf", "role": "hero", "fit": "cover", "focus": [0.5, 0.45], "treat": [ { "fx": "grain", "amount": 8 } ], "scrim": { "color": "bg", "from": "b", "strength": 0.75, "height": 0.55 }, "place": { "cover": true } },
    { "id": "stack", "kind": "group", "stack": { "dir": "col", "gap": 1, "align": "start", "justify": "end" }, "place": { "area": "copy", "anchor": "bl", "size": ["fill", "fill"] } },
    { "id": "eyebrow", "kind": "text", "parent": "stack", "voice": "eyebrow", "content": "Baked this morning", "upper": true, "fill": "onAccent", "chip": "accent", "place": { "size": [0.5, "auto"] } },
    { "id": "title", "kind": "text", "parent": "stack", "voice": "hero", "content": "Sixty loaves, then the door closes", "lines": 3, "fit": "fluid", "fill": "surface", "emph": { "rule": "number", "style": "accent" }, "place": { "size": ["fill", "auto"] } },
    { "id": "cta", "kind": "component", "type": "button", "parent": "stack", "props": { "label": "See today's bake", "pill": true, "arrow": true, "maxW": "fill" }, "place": { "size": ["auto", "auto"] } }
  ]
}
TXT;

		$catalog  = design_markup_catalog_text();
		$examples = design_markup_examples_text();

		$context   = array( 'THIS REQUEST' );
		$context[] = 'Canvas: ' . $w . 'x' . $h . ' px - ' . design_markup_format_name( $w, $h ) . '. Copy "canvas" into every design exactly as given; the editor owns the document size.';
		$context[] = 'Copy language: ' . ( ! empty( $ctx['lang'] ) ? (string) $ctx['lang'] : 'the language of the brief' ) . '. Every visible word (headline, subline, labels, button) is written in it.';
		if ( ! empty( $ctx['colors'] ) ) {
			$context[] = 'Brand colors: ' . implode( ', ', (array) $ctx['colors'] ) . '. Set tokens.palette.source to "brand" and let the editor map them onto the roles; add your own hex only for a deliberate accent.';
		}
		if ( ! empty( $ctx['fonts'] ) ) {
			$context[] = 'Brand fonts: ' . implode( ', ', (array) $ctx['fonts'] ) . '. Use them as the pairing when they fit the concept.';
		}
		if ( ! empty( $ctx['blurb'] ) ) {
			$context[] = 'Brand context: ' . (string) $ctx['blurb'] . ' Write on-brand copy in that tone.';
		}
		if ( ! empty( $ctx['product'] ) ) {
			$context[] = 'Product / context details: ' . (string) $ctx['product'];
		}
		if ( ! empty( $ctx['bindings'] ) ) {
			$context[] = 'REQUIRED bindings (each on exactly one element, in every design): ' . implode( ', ', (array) $ctx['bindings'] ) . '. A design that misses one or uses it twice is rejected before it is drawn.';
		} else {
			$context[] = 'No dynamic bindings are required. Do not add a "bind" field.';
		}
		if ( ! empty( $ctx['image'] ) ) {
			$context[] = 'A reference image is attached. Read the palette, the light and the subject from it: let it decide tokens.palette.roles (as hex) and the asset query, not only an adjective in your idea.';
		}
		$context[] = 'Return exactly ' . $k . ' design' . ( 1 === $k ? '' : 's' ) . '.';

		// Never "omit what you do not need" again: that sentence stood here
		// in stage 2a, and the model took it at its word - 536 output tokens
		// per design, no place, no content, no colors. A finished design is
		// long, and it has to be said out loud.
		$output = 'OUTPUT: JSON only, no markdown, no commentary: { "designs": [ <markup>' . ( $k > 1 ? ', <markup>, ...' : '' ) . ' ] } with exactly ' . $k . ' COMPLETE markup object' . ( 1 === $k ? '' : 's' ) . '.'
			. ' Fill in every field that carries a decision - place, content, colors, props, treat, params, scrim, emph - and leave out only what you have truly decided against.'
			. ' A complete design is typically 1 500 to 3 000 tokens of JSON. A short answer is an unfinished design, and an unfinished design is rejected.';

		return implode(
			"\n\n",
			array_filter(
				array(
					$role,
					$valid,
					$language,
					$catalog,
					$rules,
					$diversity,
					$skeleton,
					$examples,
					implode( "\n", $context ),
					$output,
				)
			)
		);
	}
}
