/**
 * SVG icon set, ported verbatim from the design prototype's icons.jsx
 * (24-viewbox, stroke 1.8, round caps). Extra icons for shipped features
 * (flip/rotate/smart object/snapshot/…) follow the same style (spec 10.3).
 *
 * v1.51: ids listed in src/ui-icons.json (generated by
 * tools/build-ui-icons.js from the curated Tabler SVGs in assets/ui-icons,
 * MIT) OVERRIDE the hand-drawn originals below — swap an icon by mapping
 * it there, never by editing this file.
 */

import uiIcons from './ui-icons.json';

export const Icon = ( {
	d,
	size = 16,
	stroke = 'currentColor',
	fill = 'none',
	sw = 1.8,
	children,
	vb = '0 0 24 24',
} ) => (
	<svg
		width={ size }
		height={ size }
		viewBox={ vb }
		fill={ fill }
		stroke={ stroke }
		strokeWidth={ sw }
		strokeLinecap="round"
		strokeLinejoin="round"
		aria-hidden="true"
	>
		{ d ? <path d={ d } /> : children }
	</svg>
);

export const I = {
	// Brand mark (v1.88.0, user-supplied icon-wpie.svg): fill-based, so it
	// skips the stroke Icon wrapper. White source parts render as
	// currentColor to follow the theme; the CI blue stays literal.
	brand: ( { size = 18 } = {} ) => (
		<svg
			width={ size }
			height={ size }
			viewBox="0 0 18.83 18.83"
			aria-hidden="true"
			focusable="false"
		>
			<path
				fill="currentColor"
				d="M13.84,18.83H3.62c-2,0-3.62-1.62-3.62-3.62V3.52h1.72c.7,0,1.28.57,1.28,1.28v10.43c0,.34.28.62.62.62h8.94c.71,0,1.29.58,1.29,1.29v1.71Z"
			/>
			<path
				fill="#3b66ff"
				d="M18.83,14.02h-1.71c-.71,0-1.29-.58-1.29-1.29V3.62c0-.34-.28-.62-.62-.62H4.82c-.7,0-1.28-.57-1.28-1.28V0h11.67c2,0,3.62,1.62,3.62,3.62v10.4Z"
			/>
			<circle fill="currentColor" cx="17.33" cy="17.33" r="1.5" />
			<path
				fill="#3b66ff"
				d="M9.51,5.71l.91,2.45c.03.08.09.14.17.17l2.45.91c.07.03.07.13,0,.16l-2.45.91c-.08.03-.14.09-.17.17l-.91,2.45c-.03.07-.13.07-.16,0l-.91-2.45c-.03-.08-.09-.14-.17-.17l-2.45-.91c-.07-.03-.07-.13,0-.16l2.45-.91c.08-.03.14-.09.17-.17l.91-2.45c.03-.07.13-.07.16,0Z"
			/>
		</svg>
	),
	// Tools
	move: ( p ) => (
		<Icon { ...p }>
			<path d="M12 3v18M3 12h18M12 3l-3 3M12 3l3 3M12 21l-3-3M12 21l3-3M3 12l3-3M3 12l3 3M21 12l-3-3M21 12l-3 3" />
		</Icon>
	),
	marquee: ( p ) => (
		<Icon { ...p }>
			<path
				d="M4 4h3M10 4h4M17 4h3v3M20 10v4M20 17v3h-3M14 20h-4M7 20H4v-3M4 14v-4M4 7V4"
				strokeDasharray="2 2"
			/>
		</Icon>
	),
	lasso: ( p ) => (
		<Icon { ...p }>
			<path d="M5 6c2-3 10-3 13 0s3 7 0 9-7 2-9 0-1-4 1-5 5 0 5 2-3 4-6 3" />
			<circle cx="4" cy="18" r="1.5" />
		</Icon>
	),
	fxbrush: ( p ) => (
		<svg
			viewBox="0 0 24 24"
			width={ p.size }
			height={ p.size }
			fill="none"
			stroke="currentColor"
			strokeWidth="1.8"
			strokeLinecap="round"
		>
			<path d="M14 4l6 6-9 9H5v-6l9-9z" />
			<circle cx="17.5" cy="17.5" r="2.5" strokeDasharray="2 2" />
		</svg>
	),
	crop: ( p ) => (
		<Icon { ...p }>
			<path d="M7 3v14h14M3 7h14v14" />
		</Icon>
	),
	brush: ( p ) => (
		<Icon { ...p }>
			<path d="M3 21c3 0 5-2 5-5 0-1-1-2-2-2s-2 1-2 2-1 1-1 1M8 14l9-9a2 2 0 0 1 3 3l-9 9" />
		</Icon>
	),
	pencil: ( p ) => (
		<Icon { ...p }>
			<path d="M17 3l4 4L8 20l-5 1 1-5L17 3z" />
			<path d="M15 5l4 4" />
		</Icon>
	),
	eraser: ( p ) => (
		<Icon { ...p }>
			<path d="M18 13l-6-6-9 9 3 3h6l9-9-3-3" />
			<path d="M8 22h12" />
		</Icon>
	),
	text: ( p ) => (
		<Icon { ...p }>
			<path d="M5 4h14M12 4v16M9 20h6" />
		</Icon>
	),
	textLayout: ( p ) => (
		<Icon { ...p }>
			<path d="M4 6h16M8 11h8M6 16h12M10 21h4" />
		</Icon>
	),
	shape: ( p ) => (
		<Icon { ...p }>
			<rect x="3" y="3" width="10" height="10" />
			<circle cx="17" cy="17" r="4" />
		</Icon>
	),
	pen: ( p ) => (
		<Icon { ...p }>
			<path d="M12 19l7-7 3 3-7 7-3-3z" />
			<path d="M18 13l-1.5-7.5L2 2l3.5 14.5L13 18" />
			<path d="M2 2l7.586 7.586" />
			<circle cx="11" cy="11" r="2" />
		</Icon>
	),
	eyedropper: ( p ) => (
		<Icon { ...p }>
			<path d="M20 4a2.5 2.5 0 0 0-3.5 0l-1.5 1.5 3 3 1.5-1.5A2.5 2.5 0 0 0 20 4z" />
			<path d="M15 6l-8 8-3 1 1-3 8-8 2 2z" />
		</Icon>
	),
	bucket: ( p ) => (
		<Icon { ...p }>
			<path d="M3 12l9-9 9 9-9 9-9-9z" />
			<path d="M3 12h18" />
			<circle cx="20" cy="18" r="2" />
		</Icon>
	),
	gradient: ( p ) => (
		<Icon { ...p }>
			<rect x="3" y="3" width="18" height="18" rx="1" />
			<path d="M3 3l18 18" strokeDasharray="1 3" />
		</Icon>
	),
	zoom: ( p ) => (
		<Icon { ...p }>
			<circle cx="11" cy="11" r="7" />
			<path d="M16 16l5 5M8 11h6M11 8v6" />
		</Icon>
	),
	hand: ( p ) => (
		<Icon { ...p }>
			<path d="M8 13V5a1.5 1.5 0 0 1 3 0v6M11 11V4a1.5 1.5 0 0 1 3 0v7M14 11V5a1.5 1.5 0 0 1 3 0v8M17 10a1.5 1.5 0 0 1 3 0v6c0 3-2 5-5 5h-3c-3 0-5-2-5-5l-2-5a1.5 1.5 0 0 1 2.5-1.5L8 12" />
		</Icon>
	),

	// Right panel tab icons
	layers: ( p ) => (
		<Icon { ...p }>
			<path d="M12 2l10 6-10 6-10-6 10-6z" />
			<path d="M2 14l10 6 10-6M2 18l10 6 10-6" />
		</Icon>
	),
	sliders: ( p ) => (
		<Icon { ...p }>
			<path d="M4 6h4M12 6h8M4 12h10M18 12h2M4 18h6M14 18h6" />
			<circle cx="10" cy="6" r="2" />
			<circle cx="16" cy="12" r="2" />
			<circle cx="12" cy="18" r="2" />
		</Icon>
	),
	history: ( p ) => (
		<Icon { ...p }>
			<path d="M3 12a9 9 0 1 0 3-6.7L3 8" />
			<path d="M3 3v5h5M12 7v5l3 2" />
		</Icon>
	),
	sparkles: ( p ) => (
		<Icon { ...p }>
			<path d="M12 3l2 5 5 2-5 2-2 5-2-5-5-2 5-2 2-5zM19 14l1 2 2 1-2 1-1 2-1-2-2-1 2-1 1-2z" />
		</Icon>
	),
	cursor: ( p ) => (
		<Icon { ...p }>
			<path d="M6 3l12 9-5.2 1.1L15 19l-2.6 1.2-2.2-5.7L6 17.5V3z" />
		</Icon>
	),
	puzzle: ( p ) => (
		<Icon { ...p }>
			<path d="M4 7h3a1 1 0 0 0 1-1V5a2 2 0 0 1 4 0v1a1 1 0 0 0 1 1h3a1 1 0 0 1 1 1v3a1 1 0 0 0 1 1h1a2 2 0 0 1 0 4h-1a1 1 0 0 0-1 1v3a1 1 0 0 1-1 1h-3a1 1 0 0 1-1-1v-1a2 2 0 0 0-4 0v1a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-3a1 1 0 0 1 1-1h1a2 2 0 0 0 0-4H4a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1" />
		</Icon>
	),
	popout: ( p ) => (
		<Icon { ...p }>
			<path d="M14 4h6v6M20 4l-8 8" />
			<path d="M20 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h5" />
		</Icon>
	),
	dockback: ( p ) => (
		<Icon { ...p }>
			<path d="M10 20H4v-6M4 20l8-8" />
			<path d="M14 4h5a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1h-5" />
		</Icon>
	),

	// Layer icons
	eye: ( p ) => (
		<Icon { ...p }>
			<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12z" />
			<circle cx="12" cy="12" r="3" />
		</Icon>
	),
	eyeOff: ( p ) => (
		<Icon { ...p }>
			<path d="M17 17A10 10 0 0 1 12 19c-6 0-10-7-10-7a18 18 0 0 1 4-5M9 5a10 10 0 0 1 3-.5c6 0 10 7 10 7a18 18 0 0 1-2.5 3.5M10 10a3 3 0 0 0 4 4M2 2l20 20" />
		</Icon>
	),
	lock: ( p ) => (
		<Icon { ...p }>
			<rect x="4" y="11" width="16" height="10" rx="1" />
			<path d="M7 11V8a5 5 0 0 1 10 0v3" />
		</Icon>
	),
	unlock: ( p ) => (
		<Icon { ...p }>
			<rect x="4" y="11" width="16" height="10" rx="1" />
			<path d="M7 11V8a5 5 0 0 1 9-3" />
		</Icon>
	),
	plus: ( p ) => (
		<Icon { ...p }>
			<path d="M12 5v14M5 12h14" />
		</Icon>
	),
	trash: ( p ) => (
		<Icon { ...p }>
			<path d="M4 6h16M9 6V4h6v2M6 6l1 14h10l1-14M10 10v6M14 10v6" />
		</Icon>
	),
	duplicate: ( p ) => (
		<Icon { ...p }>
			<rect x="3" y="3" width="13" height="13" rx="1" />
			<path d="M8 8h13v13H8z" />
		</Icon>
	),
	folder: ( p ) => (
		<Icon { ...p }>
			<path d="M3 6a1 1 0 0 1 1-1h5l2 2h9a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V6z" />
		</Icon>
	),
	mask: ( p ) => (
		<Icon { ...p }>
			<rect x="3" y="3" width="18" height="18" rx="2" />
			<circle cx="12" cy="12" r="5" fill="currentColor" opacity=".3" />
		</Icon>
	),
	chev: ( p ) => (
		<Icon { ...p }>
			<path d="M6 9l6 6 6-6" />
		</Icon>
	),

	// UI
	close: ( p ) => (
		<Icon { ...p }>
			<path d="M6 6l12 12M18 6L6 18" />
		</Icon>
	),
	check: ( p ) => (
		<Icon { ...p }>
			<path d="M5 12l5 5 9-11" />
		</Icon>
	),
	more: ( p ) => (
		<Icon { ...p }>
			<circle cx="5" cy="12" r="1.2" />
			<circle cx="12" cy="12" r="1.2" />
			<circle cx="19" cy="12" r="1.2" />
		</Icon>
	),
	save: ( p ) => (
		<Icon { ...p }>
			<path d="M5 5v14h14V9l-4-4H5z" />
			<path d="M8 5v5h7M8 19v-6h8v6" />
		</Icon>
	),
	download: ( p ) => (
		<Icon { ...p }>
			<path d="M12 4v12M7 11l5 5 5-5M4 20h16" />
		</Icon>
	),
	upload: ( p ) => (
		<Icon { ...p }>
			<path d="M12 20V8M7 13l5-5 5 5M4 4h16" />
		</Icon>
	),
	undo: ( p ) => (
		<Icon { ...p }>
			<path d="M9 5L3 11l6 6M3 11h11a6 6 0 0 1 0 12h-3" />
		</Icon>
	),
	redo: ( p ) => (
		<Icon { ...p }>
			<path d="M15 5l6 6-6 6M21 11H10a6 6 0 0 0 0 12h3" />
		</Icon>
	),
	settings: ( p ) => (
		<Icon { ...p }>
			<circle cx="12" cy="12" r="3" />
			<path d="M19.4 15a1.7 1.7 0 0 0 .3 1.8l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1.7 1.7 0 0 0-1.8-.3 1.7 1.7 0 0 0-1 1.5V21a2 2 0 1 1-4 0v-.1a1.7 1.7 0 0 0-1.1-1.5 1.7 1.7 0 0 0-1.8.3l-.1.1a2 2 0 1 1-2.8-2.8l.1-.1a1.7 1.7 0 0 0 .3-1.8 1.7 1.7 0 0 0-1.5-1H3a2 2 0 1 1 0-4h.1a1.7 1.7 0 0 0 1.5-1.1 1.7 1.7 0 0 0-.3-1.8l-.1-.1a2 2 0 1 1 2.8-2.8l.1.1a1.7 1.7 0 0 0 1.8.3h.1a1.7 1.7 0 0 0 1-1.5V3a2 2 0 1 1 4 0v.1a1.7 1.7 0 0 0 1 1.5 1.7 1.7 0 0 0 1.8-.3l.1-.1a2 2 0 1 1 2.8 2.8l-.1.1a1.7 1.7 0 0 0-.3 1.8v.1a1.7 1.7 0 0 0 1.5 1H21a2 2 0 1 1 0 4h-.1a1.7 1.7 0 0 0-1.5 1z" />
		</Icon>
	),
	sun: ( p ) => (
		<Icon { ...p }>
			<circle cx="12" cy="12" r="4" />
			<path d="M12 2v2M12 20v2M4 12H2M22 12h-2M5 5l1.4 1.4M17.6 17.6L19 19M5 19l1.4-1.4M17.6 6.4L19 5" />
		</Icon>
	),
	moon: ( p ) => (
		<Icon { ...p }>
			<path d="M21 13a9 9 0 1 1-10-10 7 7 0 0 0 10 10z" />
		</Icon>
	),
	image: ( p ) => (
		<Icon { ...p }>
			<rect x="3" y="3" width="18" height="18" rx="2" />
			<circle cx="8.5" cy="8.5" r="1.5" />
			<path d="M21 15l-5-5-11 11" />
		</Icon>
	),
	grid: ( p ) => (
		<Icon { ...p }>
			<rect x="3" y="3" width="7" height="7" />
			<rect x="14" y="3" width="7" height="7" />
			<rect x="3" y="14" width="7" height="7" />
			<rect x="14" y="14" width="7" height="7" />
		</Icon>
	),
	qr: ( p ) => (
		<Icon { ...p }>
			<rect x="3" y="3" width="7" height="7" rx="1" />
			<rect x="14" y="3" width="7" height="7" rx="1" />
			<rect x="3" y="14" width="7" height="7" rx="1" />
			<path d="M14 14h3v3h-3zM21 14v3M17 21h4M14 20v1" />
		</Icon>
	),
	alert: ( p ) => (
		<Icon { ...p }>
			<path d="M10.3 3.9L1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0zM12 9v4M12 17h.01" />
		</Icon>
	),
	palette: ( p ) => (
		<Icon { ...p }>
			<path d="M12 22a10 10 0 1 1 10-10c0 1.7-1.3 3-3 3h-2.6a2 2 0 0 0-1.4 3.4c.5.5.8 1 .8 1.6a2 2 0 0 1-2 2z" />
			<circle cx="7.5" cy="11.5" r=".8" />
			<circle cx="10.5" cy="7.5" r=".8" />
			<circle cx="15" cy="7.8" r=".8" />
			<circle cx="17.5" cy="11.5" r=".8" />
		</Icon>
	),
	list: ( p ) => (
		<Icon { ...p }>
			<path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01" />
		</Icon>
	),
	search: ( p ) => (
		<Icon { ...p }>
			<circle cx="11" cy="11" r="7" />
			<path d="M21 21l-5-5" />
		</Icon>
	),
	filter: ( p ) => (
		<Icon { ...p }>
			<path d="M3 5h18l-7 9v6l-4-2v-4L3 5z" />
		</Icon>
	),
	link: ( p ) => (
		<Icon { ...p }>
			<path d="M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-1 1M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l1-1" />
		</Icon>
	),
	unlink: ( p ) => (
		<Icon { ...p }>
			<path d="M18 9l3-3M3 18l3-3M10 13l4-4M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7" />
		</Icon>
	),
	swap: ( p ) => (
		<Icon { ...p }>
			<path d="M7 16V4M7 4L3 8M7 4l4 4M17 8v12M17 20l4-4M17 20l-4-4" />
		</Icon>
	),
	menu: ( p ) => (
		<Icon { ...p }>
			<path d="M3 6h18M3 12h18M3 18h18" />
		</Icon>
	),
	chevDown: ( p ) => (
		<Icon { ...p }>
			<path d="M6 9l6 6 6-6" />
		</Icon>
	),
	chevRight: ( p ) => (
		<Icon { ...p }>
			<path d="M9 6l6 6-6 6" />
		</Icon>
	),
	arrUp: ( p ) => (
		<Icon { ...p }>
			<path d="M12 19V5M5 12l7-7 7 7" />
		</Icon>
	),
	arrDown: ( p ) => (
		<Icon { ...p }>
			<path d="M12 5v14M5 12l7 7 7-7" />
		</Icon>
	),
	bold: ( p ) => (
		<Icon { ...p }>
			<path d="M6 4h7a4 4 0 0 1 0 8H6zM6 12h8a4 4 0 0 1 0 8H6z" />
		</Icon>
	),
	italic: ( p ) => (
		<Icon { ...p }>
			<path d="M19 4h-9M14 20H5M15 4L9 20" />
		</Icon>
	),
	underline: ( p ) => (
		<Icon { ...p }>
			<path d="M6 3v7a6 6 0 0 0 12 0V3M4 21h16" />
		</Icon>
	),
	caseUpper: ( p ) => (
		<Icon { ...p }>
			<path d="M3 19 8 5l5 14M5.1 14h5.8" />
			<path d="M13.5 19 17 9.5 20.5 19M14.9 15.9h4.2" />
		</Icon>
	),
	tabsFlyout: ( p ) => (
		<Icon { ...p }>
			<rect x="3" y="5" width="18" height="14" rx="2" />
			<path d="M15.5 12h-7" />
			<path d="M11 9.5 8.5 12l2.5 2.5" />
		</Icon>
	),
	textCurve: ( p ) => (
		<Icon { ...p }>
			<path d="M3 15c2.5-5 6-7.5 9-7.5s6.5 2.5 9 7.5" />
			<path d="M5 19v-2M12 15.5v-2M19 19v-2" />
		</Icon>
	),
	valignT: ( p ) => (
		<Icon { ...p }>
			<path d="M4 4h16" />
			<rect x="9" y="8" width="6" height="11" rx="1" />
		</Icon>
	),
	valignM: ( p ) => (
		<Icon { ...p }>
			<path d="M4 12h5M15 12h5" />
			<rect x="9" y="6" width="6" height="12" rx="1" />
		</Icon>
	),
	valignB: ( p ) => (
		<Icon { ...p }>
			<path d="M4 20h16" />
			<rect x="9" y="5" width="6" height="11" rx="1" />
		</Icon>
	),
	alignL: ( p ) => (
		<Icon { ...p }>
			<path d="M3 6h18M3 12h12M3 18h15" />
		</Icon>
	),
	alignC: ( p ) => (
		<Icon { ...p }>
			<path d="M3 6h18M6 12h12M4 18h16" />
		</Icon>
	),
	alignR: ( p ) => (
		<Icon { ...p }>
			<path d="M3 6h18M9 12h12M6 18h15" />
		</Icon>
	),
	alignJustify: ( p ) => (
		<Icon { ...p }>
			<path d="M3 6h18M3 12h18M3 18h18" />
		</Icon>
	),
	objAlignL: ( p ) => (
		<Icon { ...p }>
			<path d="M4 3v18" />
			<rect x="7" y="6" width="10" height="4" rx="1" />
			<rect x="7" y="14" width="14" height="4" rx="1" />
		</Icon>
	),
	objAlignCH: ( p ) => (
		<Icon { ...p }>
			<path d="M12 3v18" />
			<rect x="7" y="6" width="10" height="4" rx="1" />
			<rect x="5" y="14" width="14" height="4" rx="1" />
		</Icon>
	),
	objAlignR: ( p ) => (
		<Icon { ...p }>
			<path d="M20 3v18" />
			<rect x="7" y="6" width="10" height="4" rx="1" />
			<rect x="3" y="14" width="14" height="4" rx="1" />
		</Icon>
	),
	objAlignT: ( p ) => (
		<Icon { ...p }>
			<path d="M3 4h18" />
			<rect x="6" y="7" width="4" height="10" rx="1" />
			<rect x="14" y="7" width="4" height="14" rx="1" />
		</Icon>
	),
	objAlignM: ( p ) => (
		<Icon { ...p }>
			<path d="M3 12h18" />
			<rect x="6" y="7" width="4" height="10" rx="1" />
			<rect x="14" y="5" width="4" height="14" rx="1" />
		</Icon>
	),
	objAlignB: ( p ) => (
		<Icon { ...p }>
			<path d="M3 20h18" />
			<rect x="6" y="7" width="4" height="10" rx="1" />
			<rect x="14" y="3" width="4" height="14" rx="1" />
		</Icon>
	),
	distributeH: ( p ) => (
		<Icon { ...p }>
			<path d="M4 3v18M20 3v18" />
			<rect x="9" y="8" width="6" height="8" rx="1" />
		</Icon>
	),
	distributeV: ( p ) => (
		<Icon { ...p }>
			<path d="M3 4h18M3 20h18" />
			<rect x="8" y="9" width="8" height="6" rx="1" />
		</Icon>
	),
	sparkAI: ( p ) => (
		<Icon { ...p }>
			<path d="M10 3l2 4 4 2-4 2-2 4-2-4-4-2 4-2 2-4zM18 14l1 2 2 1-2 1-1 2-1-2-2-1 2-1 1-2z" />
		</Icon>
	),
	wand: ( p ) => (
		<Icon { ...p }>
			<path d="M15 4V2M15 8V6M11 6H9M21 6h-2M18 9l-1-1M12 3l-1-1M4 20l11-11M6 19l2 2" />
		</Icon>
	),

	// ---- Extra icons for shipped features (same 1.8-stroke style, spec 10.3) ----
	smart: ( p ) => (
		<Icon { ...p }>
			<rect
				x="3"
				y="3"
				width="18"
				height="18"
				rx="2"
				strokeDasharray="3 2"
			/>
			<rect x="8" y="8" width="8" height="8" rx="1" />
		</Icon>
	),
	flipH: ( p ) => (
		<Icon { ...p }>
			<path d="M12 3v18M7 8L3 12l4 4M7 8v8M17 8l4 4-4 4M17 8v8" />
		</Icon>
	),
	flipV: ( p ) => (
		<Icon { ...p }>
			<path d="M3 12h18M8 7l4-4 4 4M8 7h8M8 17l4 4 4-4M8 17h8" />
		</Icon>
	),
	rotateCw: ( p ) => (
		<Icon { ...p }>
			<path d="M21 8a9 9 0 1 0 1 5" />
			<path d="M21 3v5h-5" />
		</Icon>
	),
	refresh: ( p ) => (
		<Icon { ...p }>
			<path d="M20 11a8.1 8.1 0 0 0-15.5-2m-.5-4v4h4" />
			<path d="M4 13a8.1 8.1 0 0 0 15.5 2m.5 4v-4h-4" />
		</Icon>
	),
	rotateCcw: ( p ) => (
		<Icon { ...p }>
			<path d="M3 8a9 9 0 1 1-1 5" />
			<path d="M3 3v5h5" />
		</Icon>
	),
	camera: ( p ) => (
		<Icon { ...p }>
			<path d="M4 8h3l2-3h6l2 3h3a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1z" />
			<circle cx="12" cy="13" r="3.5" />
		</Icon>
	),
	fx: ( p ) => (
		<Icon { ...p }>
			<path d="M4 6c3 0 3-2 6-2M4 6v12c3 0 3 2 6 2M4 6h0M14 9l6 6M20 9l-6 6" />
		</Icon>
	),
	minus: ( p ) => (
		<Icon { ...p }>
			<path d="M5 12h14" />
		</Icon>
	),
	clip: ( p ) => (
		<Icon { ...p }>
			<path d="M12 4v10M8 10l4 4 4-4" />
			<path d="M4 20h16" />
		</Icon>
	),
	stamp: ( p ) => (
		<Icon { ...p }>
			<path d="M9 3h6v5H9zM7 8h10l2 5H5l2-5z" />
			<path d="M4 17h16v4H4zM4 17l1-4h14l1 4" />
		</Icon>
	),
	stopIcon: ( p ) => (
		<Icon { ...p }>
			<rect x="6" y="6" width="12" height="12" rx="1" />
		</Icon>
	),
};

// Apply the curated Tabler replacements (same 24-viewbox stroke wrapper,
// so size/stroke props keep working for every caller).
Object.entries( uiIcons ).forEach( ( [ id, ds ] ) => {
	I[ id ] = ( p ) => (
		<Icon { ...p }>
			{ ds.map( ( d, i ) => (
				<path key={ i } d={ d } />
			) ) }
		</Icon>
	);
} );
